### ISSUE TITLE
Will this page work for dumps other than en?

### ISSUE THREAD

**Issue by RoqueCampos** [tatuylonen/wiktextract#10]
I'm trying to extract the information from the Spanish and German wiktionary dumps, and I receive the following error messages (in the case of the Spanish dump):

rea.la.comp
UNRECOGNIZED PREFIX Plantilla:crea.la.superl
UNRECOGNIZED PREFIX Plantilla:Crea adverbio
UNRECOGNIZED PREFIX Wikcionario:Índice/Por idioma/QU/Q
UNRECOGNIZED PREFIX Plantilla:c-topónimos
UNRECOGNIZED PREFIX Plantilla:Crea sust pl
UNRECOGNIZED PREFIX Plantilla:inflect.es.sust.í
UNRECOGNIZED PREFIX Plantilla:c-ciencias exa

In the case of the german dump the errors are the same (instead of "plantilla", the word "vorlage").

Am I doing something wrong?

**Comment by ArmanKabiri** [comment]
Unfortunately, I have the same problem for all other languages. It seems that the package does not work for any other languages than English, even for French and Finnish!

**Comment by vincentes** [comment]
You can fix this by changing the recognized and ignored prefixes in the wiktwords command source. I'm currently parsing the Spanish dictionary this way, but I don't think the tool will capture the definitions, conjugations, and everything right. I'll report the results soon.

**Comment by ArmanKabiri** [comment]
Thanks @vincentes for your suggestion. On the homepage, it is claimed that the library is tested with English and Finnish, and to some extent German and Spanish. However, I had the "UNRECOGNIZED PREFIX" issue with all the languages mentioned above. Have you been able to pars any of these languages as claimed?

**Comment by vincentes** [comment]
@ArmanKabiri  I've only managed to get this info and it's not correct.

![image](https://user-images.githubusercontent.com/11695552/68534150-c9028600-030f-11ea-8d95-e04409ebd191.png)

**Comment by tatuylonen** [comment]
The English Wiktionary has fairly good coverage of words in other languages too.  I've used it to extract a Finnish dictionary from the *English* Wiktionary.  However I'll do some more testing on other Wiktionaries and check if support for them could be easily added.

**Comment by tatuylonen** [comment]
After looking at the Finnish and German Wiktionaries, I've decided not to implement extraction for them.  So far what I've seen, much of the information seems to be included also in the English dictionary, but all tags have been renamed and inflection is marked up differently (at least for Finnish).  It seems that the easiest way to do it would be to basically copy the whole file that does the parsing of tags, and rewrite it separately for each new language.  I would estimate 1-2 weeks per language, and you need to have some understanding of the language to be able to do it.  Furthermore each of these files would need to be maintained as the taggings evolve over time.  If someone volunteers to maintain extractions for non-English wiktionaries, I can consider including their code (or make them a second maintainer).

Note that you can still extract non-english languages, but you need to extract them from the English wiktionary.  Coverage of non-English languages in that wiktionary varies, but seems to be pretty good for many languages.
