### ISSUE TITLE
Incorrect ; in some glosses

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#102]
An example is the Spanish entry for perderse:
https://en.wiktionary.org/wiki/perderse
It is already really great that the "Compound of..." string and the second definition get split up. It would only be even better if the second gloss would be "To get lost." instead of "; To get lost."

**Comment by tatuylonen** [comment]
Fixed.  "; " is now removed from the start of the second gloss when a gloss is split like this.
