### ISSUE TITLE
Missing form_of tags in some French words (simple future)

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#103]
An example would be the word https://en.wiktionary.org/wiki/affichera or https://en.wiktionary.org/wiki/marneront
All affected words I saw seem to contain "simple future" in their gloss.

**Comment by tatuylonen** [comment]
Thanks, I added recognition of "simple future".  It is tagged as just "future".  Please let me know if a different tagging should be preferred.  This should be reflected on https://kaikki.org next time it is updated (probably on Monday).
