### ISSUE TITLE
Missing phonetic in French

### ISSUE THREAD

**Issue by augnustin** [tatuylonen/wiktextract#104]
Thanks for this amazing work! This is very helpful!

I downloaded the pre-extracted data dump and my script currently uses it successfully!

There is one thing that questioned me:

In many pages, the IPA (Internation Phonetic Alphabet) version is present, but there are cases where it is missing in the extracted version.

Eg. https://kaikki.org/dictionary/French/meaning/s/so/solutionnerait.json

```
{
  pos: "verb",
  word: "solutionnerait",
  lang: "French",
  lang_code: "fr",
  sounds: [
    {
      homophone: "solutionneraient"
    },
    {
      homophone: "solutionnerais"
    }
  ],
  senses: [
    {
      raw_glosses: [
        "third-person singular conditional of solutionner"
      ],
      glosses: [
        "third-person singular conditional of solutionner"
      ],
      tags: [
        "conditional",
        "form-of",
        "singular",
        "third-person"
      ],
      form_of: [
        {
          word: "solutionner"
        }
      ],
      id: "solutionnerait-fr-verb-NowEuoWL",
      categories: [ ]
    }
  ]
}
```

But if I look at the wikitionary page, it is there: https://fr.wiktionary.org/wiki/solutionnerait

![image](https://user-images.githubusercontent.com/1970156/145963328-d528b3ee-a78c-48d4-a375-7c0a973aa4e0.png)

I tried to look at the wikitionary full dump by doing `bzgrep -A 20 -B 20 --color 'solutionnerait' frwiki-20211201-pages-articles.xml.bz2` but I couldn't find the correct dump to look at the raw data. But I know I did find it for some other words.

- Can anyone tell me at which dump I should look?
- Is there any chance to adapt `wiktextract` behavior so that this data goes to the output?

Thanks

**Comment by tatuylonen** [comment]
Wiktextract currently extracts fromt he English Wiktionary, not the French Wiktionary.  The English Wiktionary contains words for many languages and has glosses in English.  The French dictionary has glosses in French.  Thus they are not directly compatible.  Also, the way the pages are internally encoded is completely different for each language edition (template names tend to be in that language).

For this particular word, it has IPA in the French Wiktionary but not in the English Wiktionary.

I have some plans for adding support for parsing other language editions next year, but I haven't yet started working on that.
