### ISSUE TITLE
Future forms extracted from Russian inflection tables are missing a space

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#106]
This applies for words like https://en.wiktionary.org/wiki/%D0%B7%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F#Russian

A future tense in the table is for example "бу́дем здоро́ваться". However, in the JSON file this gets parsed as "бу́демздоро́ваться", with the space missing.

PS: Thank you for fixing the other issues! 👍

**Comment by tatuylonen** [comment]
This should now be fixed. The fix should be reflected on https://kaikki.org after the next update (probably late Thursday European time).

**Comment by tatuylonen** [comment]
Turns out I had temporarily disabled extraction from my update script and yesterday's run didn't actually re-extract.  I just restarted the run and it should re-extract now.
