### ISSUE TITLE
Parenthesized parts become "romanization" (Reconstruction namespace)

### ISSUE THREAD

**Issue by danmysak** [tatuylonen/wiktextract#107]
I’m not sure https://github.com/tatuylonen/wiktextract/issues/95#issuecomment-991964538 has been noticed, so I’m creating an issue out of it just in case.

If a reconstructed word contains parentheses, as in [degut(j)as](https://en.wiktionary.org/wiki/Reconstruction:Proto-Balto-Slavic/degut(j)as), than what is inside the parentheses will become "romanization":

```
{
  "senses": [
    {
      "raw_glosses": [
        "tar"
      ],
      "glosses": [
        "tar"
      ],
      "tags": [
        "reconstruction"
      ],
      "categories": [
        "Proto-Balto-Slavic lemmas",
        "Proto-Balto-Slavic masculine nouns",
        "Proto-Balto-Slavic nouns"
      ]
    }
  ],
  "pos": "noun",
  "head_templates": [
    {
      "name": "head",
      "args": {
        "1": "ine-bsl-pro",
        "2": "noun",
        "cat2": "",
        "sort": "",
        "head": "",
        "g": "m",
        "g2": "",
        "g3": ""
      },
      "expansion": "*degut(j)as m"
    }
  ],
  "forms": [
    {
      "form": "degutas",
      "tags": [
        "canonical",
        "masculine"
      ]
    },
    {
      "form": "j",
      "tags": [
        "romanization"
      ]
    }
  ],
  "etymology_text": "",
  "etymology_templates": [],
  "word": "degut(j)as",
  "lang": "Proto-Balto-Slavic",
  "lang_code": "ine-bsl-pro"
}
```

**Comment by tatuylonen** [comment]
This should now be fixed.  I changed the processing of parenthesized parts in word heads so that they are only processed if the parenthesized part is preceded or followed by whitespace or is at the beginning or end of the head line.

The change should be reflected in the data on https://kaikki.org late Thursday (European time), provided nothing goes wrong with my update run.

**Comment by tatuylonen** [comment]
I had temporarily disabled extraction earlier and thus yesterday's run didn't actually re-extract... now restarted the update.

**Comment by danmysak** [comment]
Thanks. Unfortunately, there still seems to be a problem with inflection tables, such as [here](https://en.wiktionary.org/wiki/Reconstruction:Proto-Celtic/(s)k%C4%ABttos#Inflection):

```json
{
...
    {
      "form": "* kīttos",
      "tags": [
        "nominative",
        "singular"
      ],
      "source": "Inflection",
      "roman": "s"
    }
...
}
```

**Comment by tatuylonen** [comment]
I just changed this so that "**" is removed from the beginning of inflection table entries and the parenthesized part is expanded as optional part in inflection tables.  That is, two entries are generated for each form in such cases, one with the parenthesized part and one without.  Below is an example.  Does this make sense or would you prefer something else?  (Parentheses in inflection tables are generally expanded, as they are used in many languages to express variations/alternatives.)

Note that I still don't handle parentheses in the page title and word head (-> canonical form if it differs from word head).

{
  "categories": [
    "Proto-Celtic adjectives",
    "Proto-Celtic lemmas",
    "Proto-Celtic o/ā-stem adjectives",
    "Proto-Celtic terms derived from Proto-Indo-European",
    "Proto-Celtic terms inherited from Proto-Indo-European"
  ],
  "etymology_templates": [
    {
      "args": {
        "1": "cel-pro",
        "2": "ine-pro",
        "3": "*skh₂ey-"
      },
      "expansion": "Proto-Indo-European *skh₂ey-",
      "name": "inh"
    }
  ],
  "etymology_text": "From Proto-Indo-European *skh₂ey-.",
  "forms": [
    {
      "form": "",
      "source": "Inflection",
      "tags": [
        "table-tags"
      ]
    },
    {
      "form": "O/ā-stem",
      "source": "Inflection",
      "tags": [
        "class"
      ]
    },
    {
      "form": "kīttos",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "skīttos",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "kīttou",
      "source": "Inflection",
      "tags": [
        "dual",
        "nominative"
      ]
    },
    {
      "form": "skīttou",
      "source": "Inflection",
      "tags": [
        "dual",
        "nominative"
      ]
    },
    {
      "form": "kīttoi",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "skīttoi",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "kītte",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "skītte",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "kīttou",
      "source": "Inflection",
      "tags": [
        "dual",
        "vocative"
      ]
    },
    {
      "form": "skīttou",
      "source": "Inflection",
      "tags": [
        "dual",
        "vocative"
      ]
    },
    {
      "form": "kīttūs",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "skīttūs",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "kīttom",
      "source": "Inflection",
      "tags": [
        "accusative",
        "singular"
      ]
    },
    {
      "form": "skīttom",
      "source": "Inflection",
      "tags": [
        "accusative",
        "singular"
      ]
    },
    {
      "form": "kīttou",
      "source": "Inflection",
      "tags": [
        "accusative",
        "dual"
      ]
    },
    {
      "form": "skīttou",
      "source": "Inflection",
      "tags": [
        "accusative",
        "dual"
      ]
    },
    {
      "form": "kīttoms",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    },
    {
      "form": "skīttoms",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    },
    {
      "form": "kīttī",
      "source": "Inflection",
      "tags": [
        "genitive",
        "singular"
      ]
    },
    {
      "form": "skīttī",
      "source": "Inflection",
      "tags": [
        "genitive",
        "singular"
      ]
    },
    {
      "form": "kīttous",
      "source": "Inflection",
      "tags": [
        "dual",
        "genitive"
      ]
    },
    {
      "form": "skīttous",
      "source": "Inflection",
      "tags": [
        "dual",
        "genitive"
      ]
    },
    {
      "form": "kīttom",
      "source": "Inflection",
      "tags": [
        "genitive",
        "plural"
      ]
    },
    {
      "form": "skīttom",
      "source": "Inflection",
      "tags": [
        "genitive",
        "plural"
      ]
    },
    {
      "form": "kīttūi",
      "source": "Inflection",
      "tags": [
        "dative",
        "singular"
      ]
    },
    {
      "form": "skīttūi",
      "source": "Inflection",
      "tags": [
        "dative",
        "singular"
      ]
    },
    {
      "form": "kīttobom",
      "source": "Inflection",
      "tags": [
        "dative",
        "dual"
      ]
    },
    {
      "form": "skīttobom",
      "source": "Inflection",
      "tags": [
        "dative",
        "dual"
      ]
    },
    {
      "form": "kīttobos",
      "source": "Inflection",
      "tags": [
        "dative",
        "plural"
      ]
    },
    {
      "form": "skīttobos",
      "source": "Inflection",
      "tags": [
        "dative",
        "plural"
      ]
    },
    {
      "form": "kīttū",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "singular"
      ]
    },
    {
      "form": "skīttū",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "singular"
      ]
    },
    {
      "form": "kīttobim",
      "source": "Inflection",
      "tags": [
        "dual",
        "instrumental"
      ]
    },
    {
      "form": "skīttobim",
      "source": "Inflection",
      "tags": [
        "dual",
        "instrumental"
      ]
    },
    {
      "form": "kīttobis",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "plural"
      ]
    },
    {
      "form": "skīttobis",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "plural"
      ]
    },
    {
      "form": "kīttā",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "skīttā",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "kīttai",
      "source": "Inflection",
      "tags": [
        "dual",
        "nominative"
      ]
    },
    {
      "form": "skīttai",
      "source": "Inflection",
      "tags": [
        "dual",
        "nominative"
      ]
    },
    {
      "form": "kīttās",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "skīttās",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "kīttā",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "skīttā",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "kīttai",
      "source": "Inflection",
      "tags": [
        "dual",
        "vocative"
      ]
    },
    {
      "form": "skīttai",
      "source": "Inflection",
      "tags": [
        "dual",
        "vocative"
      ]
    },
    {
      "form": "kīttās",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "skīttās",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "kīttam",
      "source": "Inflection",
      "tags": [
        "accusative",
        "singular"
      ]
    },
    {
      "form": "skīttam",
      "source": "Inflection",
      "tags": [
        "accusative",
        "singular"
      ]
    },
    {
      "form": "kīttai",
      "source": "Inflection",
      "tags": [
        "accusative",
        "dual"
      ]
    },
    {
      "form": "skīttai",
      "source": "Inflection",
      "tags": [
        "accusative",
        "dual"
      ]
    },
    {
      "form": "kīttams",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    },
    {
      "form": "skīttams",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    },
    {
      "form": "kīttās",
      "source": "Inflection",
      "tags": [
        "genitive",
        "singular"
      ]
    },
    {
      "form": "skīttās",
      "source": "Inflection",
      "tags": [
        "genitive",
        "singular"
      ]
    },
    {
      "form": "kīttai",
      "source": "Inflection",
      "tags": [
        "dative",
        "singular"
      ]
    },
    {
      "form": "skīttai",
      "source": "Inflection",
      "tags": [
        "dative",
        "singular"
      ]
    },
    {
      "form": "kīttābom",
      "source": "Inflection",
      "tags": [
        "dative",
        "dual"
      ]
    },
    {
      "form": "skīttābom",
      "source": "Inflection",
      "tags": [
        "dative",
        "dual"
      ]
    },
    {
      "form": "kīttābos",
      "source": "Inflection",
      "tags": [
        "dative",
        "plural"
      ]
    },
    {
      "form": "skīttābos",
      "source": "Inflection",
      "tags": [
        "dative",
        "plural"
      ]
    },
    {
      "form": "-",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "singular"
      ]
    },
    {
      "form": "kīttābim",
      "source": "Inflection",
      "tags": [
        "dual",
        "instrumental"
      ]
    },
    {
      "form": "skīttābim",
      "source": "Inflection",
      "tags": [
        "dual",
        "instrumental"
      ]
    },
    {
      "form": "kīttābis",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "plural"
      ]
    },
    {
      "form": "skīttābis",
      "source": "Inflection",
      "tags": [
        "instrumental",
        "plural"
      ]
    },
    {
      "form": "kīttom",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "skīttom",
      "source": "Inflection",
      "tags": [
        "nominative",
        "singular"
      ]
    },
    {
      "form": "kīttā",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "skīttā",
      "source": "Inflection",
      "tags": [
        "nominative",
        "plural"
      ]
    },
    {
      "form": "kīttom",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "skīttom",
      "source": "Inflection",
      "tags": [
        "singular",
        "vocative"
      ]
    },
    {
      "form": "kīttā",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "skīttā",
      "source": "Inflection",
      "tags": [
        "plural",
        "vocative"
      ]
    },
    {
      "form": "kīttā",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    },
    {
      "form": "skīttā",
      "source": "Inflection",
      "tags": [
        "accusative",
        "plural"
      ]
    }
  ],
  "head_templates": [
    {
      "args": {
        "1": "cel-pro",
        "2": "adjective",
        "3": "",
        "4": "",
        "5": "",
        "6": "",
        "cat2": "",
        "head": ""
      },
      "expansion": "*(s)kīttos",
      "name": "head"
    }
  ],
  "inflection_templates": [
    {
      "args": {
        "1": "*(s)kītt"
      },
      "name": "cel-decl-adj-o+a"
    }
  ],
  "lang": "Proto-Celtic",
  "lang_code": "cel-pro",
  "pos": "adj",
  "senses": [
    {
      "glosses": [
        "left, left-handed"
      ],
      "raw_glosses": [
        "left, left-handed"
      ],
      "tags": [
        "reconstruction"
      ]
    },
    {
      "glosses": [
        "clumsy, awkward, wrong"
      ],
      "raw_glosses": [
        "clumsy, awkward, wrong"
      ],
      "tags": [
        "reconstruction"
      ]
    },
    {
      "glosses": [
        "sinister"
      ],
      "raw_glosses": [
        "sinister"
      ],
      "tags": [
        "reconstruction"
      ]
    },
    {
      "glosses": [
        "sad"
      ],
      "raw_glosses": [
        "sad"
      ],
      "tags": [
        "reconstruction"
      ]
    }
  ],
  "word": "(s)kīttos"
}
