### ISSUE TITLE
Missing Dialect tags for the Spanish pronunciations

### ISSUE THREAD

**Issue by chenhaoyu20** [tatuylonen/wiktextract#109]
This is because Spanish words have a different format - the dialect tag is between IPA key and values ([Spanish example](https://en.wiktionary.org/wiki/aceite#Spanish), [English example](https://en.wiktionary.org/wiki/tomato#English)).
I tried parsing a subset of Spanish words (about 1k) and noticed the same pattern. The dialect tags were always in between without other noisy data.
Awesome work and thank you for your help!!

**Comment by tatuylonen** [comment]
Thanks for reporting this and the analysis!  I just committed a fix for this.  The change should be reflected on https://kaikki.org within a couple of days (I have an update currently running but it doesn't yet contain this, so the next update after that).
