### ISSUE TITLE
Possible wrong section for translation section in JSON

### ISSUE THREAD

**Issue by xliiv** [tatuylonen/wiktextract#110]
I just started to use https://kaikki.org and It's awesome piece of work, so I'd like to thank you for it.

While I was exploring the data set from
https://kaikki.org/dictionary/English/kaikki.org-dictionary-English.json
(downloaded on Monday, January 31 2022)

I found that the translation for`zebra` word is placed only for one `sense`, see picture below

![image](https://user-images.githubusercontent.com/298994/151829506-b504f750-b0f6-45f3-b9e7-c2306c43fa1a.png)

In addition, the translation seems to be misplaced (assuming I read the data correctly), because for `Afrikaans` lang, the translation is

> African animal

while the sense is something different, see

![image](https://user-images.githubusercontent.com/298994/151830410-451f6bd1-6971-4df4-9592-af17c22a0393.png)
 
I'm attaching the extracted `zebra` `JSON` from the `kaikki.org-dictionary-English.json` data set below

[found-zebra-en-pretty.json.txt](https://github.com/tatuylonen/wiktextract/files/7972387/found-zebra-en-pretty.json.txt)

(it's txt, because otherwise Github blocks upload of it)

So question is, is it intentional?

**Comment by tatuylonen** [comment]
The sense disambiguation is currently experimental.  For now it may be best to use the "raw wiktextract data" (https://kaikki.org/dictionary/rawdata.html), which has non-disambiguated translations.  I'm planning to get back to improving the sense disambiguation this spring, but for the last couple of months I've been focusing on inflection table extraction and I expect it will be several more weeks before I get back to the sense disambiguation.
