### ISSUE TITLE
"form_of" key is missing for some Russian entries

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#111]
I think the affected word type is participle, for example [начав](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%BD/%D0%BD%D0%B0/%D0%BD%D0%B0%D1%87%D0%B0%D0%B2.html). (Compare it to [начал](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%BD/%D0%BD%D0%B0/%D0%BD%D0%B0%D1%87%D0%B0%D0%BB.html) for example, where everything works great.

**Comment by tatuylonen** [comment]
I just committed a fix for this.  The word "short" is handled specially in these, as it conflicts with some other uses.  It is possible there are other combinations of "short" with other for descriptors that still need to be specially listed.  Please let me know if you find any.

The change should be reflected on https://kaikki.org the next time the update run goes through (probably within a couple of days). I have an update currently running but that was started before this change.

**Comment by tatuylonen** [comment]
I just fixed both of these.  I also fixed several other similar cases, including "short feminine", "short neuter", "short plural", "short singular", "short dative singular" (Polish).  These should be reflected on https://kaikki.org in a couple of days.
