### ISSUE TITLE
Support for Chinese dialectical synonym data

### ISSUE THREAD

**Issue by Manishearth** [tatuylonen/wiktextract#120]
Similar to https://github.com/tatuylonen/wiktextract/issues/119, I do intend to work on this myself but help would be appreciated.

Chinese entries have these dialectical synonyms:

![image](https://user-images.githubusercontent.com/1617736/155685991-1f616128-ef9c-4d49-a5ce-059b7be096c1.png)
![image](https://user-images.githubusercontent.com/1617736/155686094-8ddab7d8-c17a-4dfd-981a-45325b417ad0.png)

which show how each entry maps to various synonyms across dialects. The data is stored in places like https://en.wiktionary.org/wiki/Module:zh/data/dial-syn/%E8%AA%B0, and there are a couple hundred such entries (it's mostly just common words where this happens).

This data is quite important for understanding chinese terms in the cross-dialectical fashion they are presented here.

I think it would be nice if chinese etymologies that are the "parent" of a dialectical synonym entry had the full synonym data, and "child" entries could have a reference back to the parent entry. This would largely involve parsing the lua module data used here.

**Comment by tatuylonen** [comment]
My first attempt would be to expand the template using ctx.expand() and then parsing the resulting table (note that it is still probably Wikitext and not necessarily expanded all the way to HTML).  I welcome contributions related to this!

**Comment by tatuylonen** [comment]
Parsing Chinese dialectal synonyms was implemented in May and they should now be included in the data.  Please let us know if you notice any problems or missing data or have other suggestions on how to improve it. This was implemented by @yoskari and I haven't tested it myself.
