### ISSUE TITLE
Missing form_of tags for "полу"

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#121]
For one etymology of [полу ](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%BF/%D0%BF%D0%BE/%D0%BF%D0%BE%D0%BB%D1%83.html) the form_of tags are missing, probably due to the weird case combination referenced ("dative/partitive").

The same is true for [эйфории](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D1%8D/%D1%8D%D0%B9/%D1%8D%D0%B9%D1%84%D0%BE%D1%80%D0%B8%D0%B8.html), which has 3 cases (genitive/dative/prepositional)

Thanks for this project!

**Comment by tatuylonen** [comment]
I just committed a fix for this (though I wasn't yet able to test it as I'm running another longer test in my development environment right now).  I'll probably still test it today.  https://kaikki.org updates are a bit behind right now as the run hangs in my production environment and I haven't yet been able to reproduce it on my development machine.  This could be due to lupa (Python package for running Lua code) apparently having upgraded from Lua 5.3 to Lua 5.4 and I've already encountered some incompatibilities.

**Comment by Vuizur** [comment]
Thank you very much for fixing those cases! I realized that the number of affected entries is a bit larger and I tried to properly find all similar cases and got this list:

```
dative/instrumental/prepositional
genitive/prepositional
dative/vocative singular
short feminine singular past indicative imperfective/perfective
feminine genitive/dative/instrumental singular
short plural past indicative imperfective/perfective
short neuter singular past indicative imperfective/perfective
short masculine singular past indicative imperfective/perfective
neuter singular past indicative imperfective/perfective
dative/prepositional/vocative singular
genitive/prepositional plural
plural past indicative imperfective/perfective
genitive/accusative/vocative
prepositional/vocative singular
genitive/accusative animate/prepositional plural
second-person plural imperative imperfective/perfective
masculine singular past indicative imperfective/perfective
second-person singular imperative imperfective/perfective
prepositional masculine / neuter singular
prepositional/locative singular
feminine singular past indicative imperfective/perfective
dative/locative/partitive singular
```

(And there came up the those two entries, which maybe would also be useful, but they are possibly another topic)
```
alternative form
acronym
```

**Comment by tatuylonen** [comment]
I implemented support for the combinations you listed.  However without sample words I can't easily test them.  It would help if you could check these again after the database has updated (probably tomorrow).

I'm not sure what the issue regarding "alternative form" and "acronym" was.  Both seem to be recognized, at least in some contexts.  I didn't do anything regarding them.

**Comment by tatuylonen** [comment]
I changed the alt_of/form_of parsing code so that it allows parenthesized topics before the rest of the gloss.   СПИД is now parsed correctly as an alt_of.

The change should be reflected on https://kaikki.org in a couple of days.

**Comment by Vuizur** [comment]
The fix is now visible on the website, looks perfect 👍.
