### ISSUE TITLE
{{rfv-pron|en}} template is confused with IPA transcription

### ISSUE THREAD

**Issue by Tc14Hd** [tatuylonen/wiktextract#124]
Here is the pronunciation section of the word "geeminy":

![pronunciation section](https://user-images.githubusercontent.com/56201517/158402828-5f65b505-6083-4616-b984-ca779fc21339.png)

Source code:

```
===Pronunciation===
* {{rfv-pron|en}} {{IPA|en|/dʒiːməni/}}
```

Here is the parsed result:

```
[
   {
      "ipa":"/2022/"
   },
   {
      "ipa":"/d\u0292i\u02d0m\u0259ni/"
   }
]
```

Somehow, there is the additional IPA transcription `/2022/`. I also found it with other entries using the `{{rfv-pron|en}}` template, so I think this is what's causing the problem.

**Comment by tatuylonen** [comment]
Thanks for reporting this.  I just committed a fix.  The fix should be reflected on https://kaikki.org next time it is updated (probably tomorrow).

**Comment by Tc14Hd** [comment]
Thanks for the quick fix!
