### ISSUE TITLE
Question: what is tag "abbreviation"?

### ISSUE THREAD

**Issue by medmunds** [tatuylonen/wiktextract#127]
I'm looking for a way to filter out abbreviations, and was thinking [tag:abbreviation](https://kaikki.org/dictionary/English/tag/abbreviation.html) would do the job. But the abbreviation tag seems to include several categories of words that I don't think would normally be considered abbreviations. So I'm trying to understand what it actually means, or what results in an entry or sense getting tagged abbreviation.

For example, all of these have tag:abbreviation:
* "[coord](https://kaikki.org/dictionary/English/meaning/c/co/coord.html)"—abbreviation of coordinate
* "[cap'n](https://kaikki.org/dictionary/English/meaning/c/ca/cap'n.html)"—contraction of "captain" (though "[can't]()"—contraction of "cannot"—does *not* have tag:abbreviation)
* "[hippo](https://kaikki.org/dictionary/English/meaning/h/hi/hippo.html)"—clipping of hippopotamus
* "[seltzer](https://kaikki.org/dictionary/English/meaning/s/se/seltzer.html)"—ellipsis of "seltzer water"
* "[corgi](https://kaikki.org/dictionary/English/meaning/c/co/corgi.html)"—short for "Welsh corgi" (a type of dog)

Is the "abbreviation" tag used for *every* type of shortening?

The problem I need to solve is how to distinguish standalone words like "corgi" or "seltzer" from true abbreviations like "coord". Seltzer also has tag:ellipsis, so I could special case that, but "corgi" and "coord" are both tag:abbrevation and tag:alt-of, with no other tags.

[FWIW, the [Wiktionary glossary](https://en.wiktionary.org/wiki/Appendix:Glossary) considers clipping (dropping part of a word) to be a type of abbreviation, but specifically says ellipsis (dropping an entire word from a phrase) is "not to be confused with" clipping. The Wiktionary category tree also implies a hierarchy of shortenings, rooted in [English shortenings](https://en.wiktionary.org/wiki/Category:English_shortenings). The abbreviations category is a subcategory of shortenings—and peer category to clippings, contractions, and ellipses.]

**Comment by tatuylonen** [comment]
The "abbreviation" tag is intended to be included for all the various kinds of abbreviated forms marked in various ways, including "abbreviated", "abbreviation as", "abbrev.", "abbreviation of", "short for", "eclipsed form of", "apocopic form of", "apocopated", "apocope", "acronym of", "acronym", "initialism of", "contraction of", "IUPAC 3-letter abbreviation for", "praenominal abbreviation of", "ellipsis of", "clipping of", "abbreviations".   It will also be included if the gloss starts with "(abbreviation)" or similar.

This tag is usually combined with another tag that indicates what kind of abbreviation it is.

Please let me know if you notice places where it should not be included or is missing.

As to distinguishing the standalone forms, one way might be to see if the raw_gloss field begins with something like "(abbreviation)".  Another way might be to see if the sense has an "alt_of" field; the system attempts to link abbreviations to their main words.

**Comment by medmunds** [comment]
Thanks, that's a helpful answer to my somewhat confused question. The more I've looked into this, the Wiktionary data is really inconsistent around how abbreviated forms are defined. And I couldn't find any real policies or guidelines on them, so it's not clear how the data *should* be in the first place. (It's impressive wiktextract is getting as much useful data as it is.)

I think it _would_ be helpful to distinguish senses specifically identified as "abbreviation" (the raw_gloss has an "(abbreviation)" label, or the definition uses the `{{abbreviation of}}` template) from other specific abbreviated forms. Right now, the "abbreviation" tag seems to be overloaded to cover both.

> [The "abbreviation"] tag is usually combined with another tag that indicates what kind of abbreviation it is.
> Please let me know if you notice places where it should not be included or is missing.

There are around 1000 senses in the 2022-03-09 English extraction that are tagged "abbreviation" but that _don't_ have some other tag identifying a more specific kind of abbreviation ("acronym", "clipping", "contraction", "ellipsis", "initialism", or "shortening"), and that also don't have an identifying "(label)" in the raw_gloss. A few examples:

- abbrevn: Abbreviation of abbreviation. tags:{'abbreviation', 'alt-of'} labels:{}
- ctn: Abbreviation of carton. tags:{'abbreviation', 'alt-of'} labels:{}
- 'Sconset: Short for Siasconset. tags:{'abbreviation', 'alt-of'} labels:{}
- 'boutcha: Alternative spelling of boutcha tags:{'abbreviation', 'alt-of', 'alternative'} labels:{}
- AAR: After-action report; after-action review. tags:{'abbreviation'} labels:{'military', 'management'}
- AAR: Air America Radio tags:{'abbreviation'} labels:{'politics'}
- AAR: Aircraft accident report. tags:{'abbreviation'} labels:{'aviation'}
- Barnetby: Short for Barnetby le Wold. tags:{'abbreviation', 'alt-of'} labels:{}
- I'l: Obsolete form of I'll. tags:{'abbreviation', 'alt-of', 'obsolete'} labels:{}
- Ima: I'm. tags:{'abbreviation', 'nonstandard'} labels:{'nonstandard'}
- binna: has been tags:{'abbreviation', 'nonstandard'} labels:{'nonstandard'}
- camomile: Short for camomile tea. tags:{'abbreviation', 'alt-of', 'countable', 'uncountable'} labels:{}
- cmon: Alternative spelling of c'mon tags:{'abbreviation', 'alt-of', 'alternative'} labels:{}
- helluv: Elision of "hell of". tags:{'abbreviation', 'colloquial'} labels:{'colloquial'}
- supposta: Pronunciation spelling of supposed to. tags:{'abbreviation', 'alt-of', 'pronunciation-spelling', 'US'} labels:{'chiefly US'}

(Let me know if the full list would be helpful, or if I should open a specific new issue for this.)

**Comment by tatuylonen** [comment]
Looking at your list, the ones with alt-of have clearly been identified as an abbreviation of some other form (indicated int he "alt_of" field).  AAR has (abbreviation) in outer-level gloss in a hierarchical set of glosses.  One could argue they should have an alt_of based on the outer gloss, but I'm hesistant to assume that this would always be correct in similar cases.  However in your list of examples, if it doesn't have alt-of, in each case the full gloss would have been a valid value for alt_of (i.e., the expression that it is an abbreviation of).

I think it is possible to distinguish the two cases you mention ("(abbreviation)" in raw_gloss vs. "abbreviation of" in gloss) by whether there is an alt-of tag and "alt_of" field.  For various reasons adding the distinction in code is not entirely trivial and could break things (the whole tag recognition is a bit delicate and complicated).  Unless there are strong arguments why the distinction would need to be made in code, I would be inclined to leave it as-is.

I'm not sure about the "ellipsis" cases.  Should "abbreviation" not be included in them?  Dropping abbreviation from "ellipsis of" would be easy.  However "ellipsis" can also result from "elliptically" (presumably parenthesized at start of gloss).
