### ISSUE TITLE
Missing german verb form

### ISSUE THREAD

**Issue by sayingandparsing** [tatuylonen/wiktextract#13]
When parsing german words in the en.wiktionary dump, I'm seeing a lot of error messages of the format `alptraumhaftesten IN German/adj: ERROR: unknown value 'adjective superlative form' in {{head|de|adjective superlative form}}`.
I think it might be as simple as adding 'adjective superlative form' to the canonical forms dictionary, but I haven't had a chance to investigate further.

**Comment by tatuylonen** [comment]
I just made some fixes related to this.  The generated JSON now looks ok.  (The HTML version at https://kaikki.org/dictionary/ should update in about 24 hours)

**Comment by tatuylonen** [comment]
This now seems to work.
