### ISSUE TITLE
enPR transcription is interpreted as IPA

### ISSUE THREAD

**Issue by Tc14Hd** [tatuylonen/wiktextract#132]
For example, the pronunciation section of the entry "Manx cat" looks like this:

```
===Pronunciation===
* {{IPA|en|/mæŋks kæt/}}, {{enPR|/mănks kăt/}}
```

But in the corresponding JSON, the enPR transcription is additionally interpreted as IPA.

```
"sounds": [
  {
    "ipa": "/mæŋks kæt/"
  },
  {
    "ipa": "/mănks kăt/"
  },
  {
    "enpr": "/mănks kăt/"
  }
]
```

From looking at other cases, I can say that this behavior only happens when the enPR transcription contains a slash or a square bracket (which it actually shouldn't).

**Comment by tatuylonen** [comment]
This happened when the enPR pronunciation contains slashes.  I fixed this in the code; now enPR pronunciations should never get interpreted also as IPA, even if they contain slashes.  I also added code to strip the slashes around enPR (most enPRs don't include slashes and this makes the data more consistent).  Let me know if you think the slashes should not be stripped.

The change should be reflected on https://kaikki.org within a couple of days.

**Comment by Tc14Hd** [comment]
Thanks for the fix. I think the slashes and square brackets should be stripped. In IPA transcriptions they are used to distinguish between phonemic and phonetic transcription, but since enPR transcriptions are always phonemic, adding them makes no sense.
