### ISSUE TITLE
Missing head_templates in some Russian pages

### ISSUE THREAD

**Issue by jsannemo** [tatuylonen/wiktextract#135]
In a few Russian language pages, I've found that `head_templates` field are sometimes lost. For example https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D1%82/%D1%82%D1%80/%D1%82%D1%80%D0%B5%D1%82%D1%8C%D0%B5%D0%BC.html
lack it for one form, and
https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D1%82/%D1%82%D1%80/%D1%82%D1%80%D0%B5%D1%82%D1%8C%D1%8F.html
lack it for both forms.

It's a bit unpredictable to me whether or not a word will have them - maybe it's WAI that they're not always parsed?

**Comment by jsannemo** [comment]
The regex at https://github.com/tatuylonen/wiktextract/blob/e6bdc5657919d5b3479b8cb6b6fc87077c12ad4c/wiktextract/page.py#L45-L211 might not mix well with the `+` in the `ru-noun+` name templates?

**Comment by tatuylonen** [comment]
I changed the regexp to allow + at the end of template names captured in head_templates.  This fixed at least the latter example (I couldn't find the problem in the first example).  Let me know if more changes are still needed.

The fix should be reflected on https://kaikki.org tomorrow.
