### ISSUE TITLE
Documentation: What data is in the post-processed files, but not in the raw files?

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#137]
I wanted to use part of the Russian data which is not available in the post-processed data, but only in the raw data files. (Derived forms, to be exact. If you extract the Russian raw data, it is about 7 percent larger than the the downloadable post-processed data). 

However, I use the data to fill a database and noticed that the database generated from the post-processed data is larger than the one generated from the raw data (and SQLdiff shows that there are many changes). So there must be some data that is only in the post-processed data, but not in the raw data. It would nice to maybe have this documented [here ](https://kaikki.org/dictionary/rawdata.html) or so.

**Comment by tatuylonen** [comment]
For now I would recommend using the raw data.  My intention is to have the post-processed data have disambiguation, more persistent identifiers for word senses, and various additional data imported from other sources.  It should also include the same data as the raw dump, but disambiguated and structured slightly differently.

However, the disambiguation is currently experimental and needs more work.

Derived forms missing from the post-processed data appears to be a but.  I'm looking into it.

**Comment by tatuylonen** [comment]
Turns out there was a bug in my disambiguation code that caused all lexical-semantic relations to be dropped from the post-processed data if they did not have a "sense" field.  This should now be fixed.  The fix should be reflected on https://kaikki.org after the next update (probably Monday afternoon European time).

**Comment by Vuizur** [comment]
Thank you very much for the reply and for fixing it!
