### ISSUE TITLE
No "form of" tag for Spanish voseo entries

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#154]
It is not a big problem, but for many inflections entries containing the word "voseo" the form-of tag is missing. Examples would be [hackeás](https://kaikki.org/dictionary/All%20languages%20combined/meaning/h/ha/hacke%C3%A1s.html), [halagá](https://kaikki.org/dictionary/All%20languages%20combined/meaning/h/ha/halag%C3%A1.html), [rutilés](https://kaikki.org/dictionary/All%20languages%20combined/meaning/r/ru/rutil%C3%A9s.html).

I think it is always these three grammar inflection strings
```
rutilá	second-person singular voseo imperative of rutilar
rutilás	second-person singular voseo present indicative of rutilar
rutilés	second-person singular voseo present subjunctive of rutilar
```

PS: I love this project

**Comment by kristian-clausal** [comment]
This was a recent change in templates last month. We added "voseo" into the list of parsed grammatical terminology, I'll check quickly if there's any other major changes like this in Spanish templates (though I doubt it, I don't think there's 'noseo'...), and with that it should now be fine. The changes should be visible as soon as we get the site update running again, please follow up when the update is online.

**Comment by kristian-clausal** [comment]
The update's gone through and it seems at a quick glance that the term *voseo* now adds a ´with-voseo´ tag in a word head.
