### ISSUE TITLE
Lack of IPA for many english words - only ~10% English words have IPA pronunciation

### ISSUE THREAD

**Issue by michalzmuda** [tatuylonen/wiktextract#157]
File: kaikki.org-dictionary-English-words.json

example word without IPA: member 
wiktionary entry has IPA: https://en.wiktionary.org/wiki/member

All words count: 
`cat kaikki.org-dictionary-English-words.json | wc -l`
returns: 1158999

Words with IPA only ~10%
`cat kaikki.org-dictionary-English-words.json | grep ipa | wc -l`
returns: 109911

**Comment by kristian-clausal** [comment]
Your example word does have "sounds" > "ipa", but only for Etymology 1; Etymology 2 does not have have a pronunciation section in the article, and the phonology section is inside Etymology 1, so it's not propagated from above either.

Wiktextract is not meant to create a dictionary, it's meant to pull data from wiktionary and clean it up a bit; we don't usually add things that aren't present in the original data. It seems likely that it just so happens that out of the 1 000 000+ words in the data, only 100 000 have some kind of IPA data, and the vast majority are short stubs like https://en.wiktionary.org/wiki/propositions#English, https://en.wiktionary.org/wiki/propositioner#English or https://en.wiktionary.org/wiki/propositioning.

I'll leave the thread open for a while in case someone can find examples of entries (etymologies) with IPA that should have them but don't; just post them here.
