### ISSUE TITLE
"noinclude" appears in latest version

### ISSUE THREAD

**Issue by fpw** [tatuylonen/wiktextract#162]
Hello,

the latest version of the Latin dictionary on kaikki.org includes several "noinclude" arguments that break the Lua scripts that make use of these arguments.

Example: https://kaikki.org/dictionary/Latin/meaning/C/Ch/Christiana%20respublica.html#Christiana_respublica-la-name-G-tHrkMt

In the raw data, this "noinclude" tag is scattered across multiple arguments:
```
    {
      "name": "la-proper noun",
      "args": {
        "1": "Chrīstiāna<+> [<noinclude/>[respublica",
        "2": "rēs<5>pūblica<+>]<noinclude/>]"
      },
      "expansion": ""
    }
```` 

Expected would be a single argument: `Chrīstiāna<+> rēs<5>pūblica<+>`. Maybe the issue is that there's a space inside the argument leading to failure in transforming this tag.

Here's the original article: https://en.wiktionary.org/wiki/Christiana_respublica

**Comment by kristian-clausal** [comment]
We have a lot of Lua issues at the moment which are breaking the kaikki.org update, so this might have something to do with it. In the meanwhile, we'll have to sit tight and watch if things get better.

**Comment by tatuylonen** [comment]
This should now be fixed.  The code for parsing links in wikitextprocessor was too restrictive and didn't allow the annotations in angle brackets inside links.  Also the noinclude stuff should no longer appear in captured template arguments (and shouldn't have been triggered here anyway, but was due to the error in parsing the links).

**Comment by fpw** [comment]
Can confirm it's fixed now and the entire Latin dump is in a perfect state right now, thanks a lot!
