### ISSUE TITLE
"lead" translations confused

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#167]
The Wiktionary entry for "lead" has a [translations subpage](https://en.wiktionary.org/wiki/lead/translations) with an usual structure: there are two sections for the two etymologies and the main page links to the corresponding section. The extractor gets confused by this and misses the translations for Etymology 2, such as for the verb, "guide or conduct with the hand, or by means of some physical contact connection", and for the noun, "act of leading or conducting".

Instead, it seems that the translations for Etymology 1 are extracted twice, e.g. those for "chemical element" are [listed](https://kaikki.org/dictionary/All%20languages%20combined/meaning/l/le/lead.html) both under the noun entry for "(uncountable) A heavy, pliable, inelastic metal element" and again as "The following are not (yet) sense-disambiguated" under the second English verb entry.

This is certainly an unusual scenario, but it would be great if the extractor could be fixed to also get the translations for Etymology 2.

**Comment by kristian-clausal** [comment]
I found the culprit in page.py/parse_language/get_subpage_section/recurse():

```python
        def recurse(node, seq):
            # print(f"seq: {seq}")
            if not seq:
                return node
            if not isinstance(node, WikiNode):
                return None
            # print(f"node.kind: {node.kind}")
            if node.kind in LEVEL_KINDS:
                t = clean_node(config, ctx, None, node.args[0])
                # print(f"t: {t} == seq[0]: {seq[0]}?")
                if t.lower() == seq[0].lower():
                    seq = seq[1:]
                    if not seq:
                        return node
            for n in node.children:
                ret = recurse(n, seq)
                if ret is not None:
                    return ret
            return None
```
A possible fix:

```python

**Comment by kristian-clausal** [comment]
Tatu didn't see anything wrong with it, so the issue should now be fixed.

**Comment by ChristianSi** [comment]
Yeah, it's fixed now, thanks!
