### ISSUE TITLE
Missing form_of in some Spanish words

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#170]
Some Spanish infinitive and gerund forms are not marked with form_of properly

One example is [tecnificarse](https://kaikki.org/dictionary/All%20languages%20combined/meaning/t/te/tecnificarse.html) or [tañéndose](https://kaikki.org/dictionary/All%20languages%20combined/meaning/t/ta/ta%C3%B1%C3%A9ndose.html). infinitive and gerund are the only examples I could find, so the rest seems to be working.

PS: Keep up the great work, this is my favourite project on Github.

**Comment by kristian-clausal** [comment]
Added `"combined with se": "reflexive", # tecnificarse/Spanish` to tags/xlat_tags_map as a stopgap measure. This will parse "combined with se" as 'reflexive' (which may or may not be correct but the entry is floating in no-context soup so...), which then allows the form-of parsing to succeed.
