### ISSUE TITLE
Spanish WiktExtract download is missing important words

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#178]
I just noticed that the [file here](https://kaikki.org/dictionary/Spanish/kaikki.org-dictionary-Spanish.json) is missing important Spanish words. These words were present in earlier versions of the same file (unfortunately I have no exact date).

The most prominent of these words is the word [estar](https://en.wiktionary.org/wiki/estar#Spanish), which is one of the most important Spanish words. The word gets referenced by many other words (e.g. `"id": "estaba-es-verb--17FubVa"`), but it is not in the file. A search for `"id": "estar-es-verb` will get no results.

Is this a temporary issue or is there a reason for this?

**Comment by kristian-clausal** [comment]
Currently estar appears in the data correctly. Something might have been borked in the meanwhile or your file download might have cut off at some point. If you are unable to find something in the .json files, check out its https://kaikki.org/dictionary/Spanish/meaning/e/es/estar.html page first and see what form that json is there, which might help with searching.
