### ISSUE TITLE
Partial form text for the word "defunct"

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wiktextract#182]
["defunct"](https://en.wiktionary.org/wiki/defunct) on kaikki.org currently has this forms data:

```json
"forms": [
    {
      "form": "more",
      "tags": [
        "archaic",
        "comparative"
      ]
    },
    {
      "form": "most",
      "tags": [
        "archaic",
        "superlative"
      ]
    }
  ],
```

it should be "more defunct" and "most defunct", and I guess the "archaic" tag was added because the code mistook the text "defunct" as a template argument. The relevant codes are here:

https://github.com/tatuylonen/wiktextract/blob/abd388fc6b1ddbe41fce7a389f2a63b5e6f9c4f1/wiktextract/form_descriptions.py#L167-L175

https://github.com/tatuylonen/wiktextract/blob/abd388fc6b1ddbe41fce7a389f2a63b5e6f9c4f1/wiktextract/form_descriptions.py#L1058-L1080

and the `xlat_head_map` dict has this key-value pair:

https://github.com/tatuylonen/wiktextract/blob/abd388fc6b1ddbe41fce7a389f2a63b5e6f9c4f1/wiktextract/tags.py#L367

**Comment by xxyzz** [comment]
Thanks for the fix!

I tried to delete the "defunct" key from `xlat_head_map` and found the code can still add `archaic` tag correctly for pages that have "defunct" parameter in the head template but I can't find the code does that work. I wonder whether this extract forms feature could be done by checking the template parameters without expanding the template, so it would also works for non-English dump files.

**Comment by kristian-clausal** [comment]
Just to clarify, we don't actually do anything with template arguments `{{template|arguments}}` except use them to expand the templates. You'd have to ask Tatu why, but I am *reasonably* sure (counterexamples in 3, 2...) that we only parse the output of templates. Up to very recently, we didn't even have any way of telling what template a table being parsed was located in/expanded from (if any); the template argument information was saved in the data, as a debug tool and postprocessig tool (I assume), but not used.

If you just deleted the key in xlat_head_map, something might have gone through from xlat_tags_map.
