### ISSUE TITLE
Spanish word día missing from the dump

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#191]
The affected page is [here on Wiktionary](https://en.wiktionary.org/wiki/d%C3%ADa#Spanish), but does not seem to be in the kaikki dump.

As always, thanks for all the great work.

**Comment by kristian-clausal** [comment]
It took me a while to realize it, but it does exist: https://kaikki.org/dictionary/Spanish/meaning/d/d%C3%AD/d%C3%ADa.html

Problems:

* the search doesn't work properly with día specifically, and I have no idea why. Other words with í works swimmingly!
* the json has the í escaped and it took me ages to find the right combination of escaped Python unicode and to grep it

Searching for "dí" on kaikki.org works! "díver" from Spanish works. "díadas" is broken again.

Obviously a bug, possibly a off-by-one error somewhere seeing how it seems to affect "...a".

**Comment by kristian-clausal** [comment]
Tatu has committed a possible fix (which had been written, just waited to be committed), so we'll see how things go in a couple of days when and if the site deigns to update.

**Comment by Vuizur** [comment]
Thanks!

**Comment by kristian-clausal** [comment]
Seems like the fix didn't take, so this will have to wait until next year. Happy New Year!

**Comment by Vuizur** [comment]
Thanks, I also wish a happy new year! 😀

ср, 28 дек. 2022 г., 09:42 kristian-clausal ***@***.***>:

**Comment by castower** [comment]
Hello! This is a wonderful project that I recently stumbled upon and I greatly appreciate all of your hard work! 

For troubleshooting purposes, I thought it might be helpful to share that I ran into a similar issue with pájaro. I checked and discovered that it was in wikitionary (https://en.wiktionary.org/wiki/p%C3%A1jaro) even though it appeared to be missing from kaikki.org since it wasn't listed on the pá page: https://kaikki.org/dictionary/Spanish/words--or---p%C3%A1tico.html

To test, I copied and pasted the same escaped characters that are listed in the wikitionary link into the one for kaikki.org and the link then appeared: https://kaikki.org/dictionary/Spanish/meaning/p/p%C3%A1/p%C3%A1jaro.html

**Comment by kristian-clausal** [comment]
> For troubleshooting purposes, I thought it might be helpful to share that I ran into a similar issue with pájaro. I checked and discovered that it was in wikitionary (https://en.wiktionary.org/wiki/p%C3%A1jaro) even though it appeared to be missing from kaikki.org since it wasn't listed on the pá page: https://kaikki.org/dictionary/Spanish/words--or---p%C3%A1tico.html

Thankfully, this is just a problem with the index pages being hard to browse. To get to pájaro, you have to know (in advance) that kaikki.org alphabetizes á at the end of the alphabet, so you have to go through the page https://kaikki.org/dictionary/Spanish/words-pza--quatrocientos.html to get there. The formatting of the suffixes (using hyphens like in -pático) can also cause confusion.

I'm not sure if there's really a straightforward way to make these more accessible. These index pages aren't actually meant to be the main way for humans to interact with the site, that's the search bar on the upper left (which is broken, but I'm sure it'll get fixed soon).

**Comment by kristian-clausal** [comment]
The search is now fixed, and better indexing/sorting of words is on the todo-list.

**Comment by kristian-clausal** [comment]
Oops, seems the issue with a very specific crash is causing problems with the search still. The search cache files seem to be created (afaict based on tests locally), so probably wrong on the javascript side. But in general unless the word you're searching for is capitalized with a unicode alphabetical letter that gets decomposed into two unicode code points (İ > i+combining diacritic, for example), you're good to go. Or if the capital is later in the first three letters of the word, I guess.

**Comment by kristian-clausal** [comment]
Hopefully a final commit for this in the kaikki repo, we'll see tomorrow.

**Comment by kristian-clausal** [comment]
The kaikki.org search should now be functioning, including when lowercased letters generate more characters. The last problem was a single line fix in the javascript (used length of the original `query` to slice a compared string instead of the length of the lowercased `lcq`).
