### ISSUE TITLE
Italian dump missing IPA

### ISSUE THREAD

**Issue by seth-js** [tatuylonen/wiktextract#192]
Many entries are missing IPA information. The IPA is present on the site, but not in the main JSON with all word senses.

For example:
"sorpresa": https://en.wiktionary.org/wiki/sorpresa#Italian
"grazie": https://en.wiktionary.org/wiki/grazie#Italian

**Comment by kristian-clausal** [comment]
Currently when looking at Pronunciation sections, some of the code I added (though I suspect this might have been true also before) tries to flatten the structure of the list that is expected to be there. However in this case, and cases like Finnish, where the list is contained in the output of a template that doesn't happen. Shouldn't be too hard to fix.

**Comment by seth-js** [comment]
Really appreciate the super quick reply. Hope you can get this fixed.

**Comment by kristian-clausal** [comment]
Fixed for now. If the Pronunciation section has no lists to parse, expand all templates first. Got it right *eventually*.
