### ISSUE TITLE
Unable to run wiktwords script (unexpected keyword argument 'lang_code')

### ISSUE THREAD

**Issue by seth-js** [tatuylonen/wiktextract#194]
I ran the following commands:

```
git clone https://github.com/tatuylonen/wiktextract.git
cd wiktextract && pip3 install -r requirements.txt && pip3 install -e .
```

I went to the directory where the dump file is located and ran:
```
wiktwords --all --all-languages --out data.json enwiktionary-20221201-pages-articles.xml.bz2
```

I then received this error:

```
Capturing words for all available languages
Traceback (most recent call last):
  File "/home/seth/.local/bin/wiktwords", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/seth/downloads/wiktextract/wiktwords", line 288, in <module>
    ctx = Wtp(cache_file=args.cache, num_threads=args.num_threads,
TypeError: __init__() got an unexpected keyword argument 'lang_code'
```

I also tried running it with the flag `--language it` instead, but still encountered the error.

I'm running this on WSL, so that may have something to do with the problem.

**Comment by xxyzz** [comment]
You also need to install [wikitextprocessor](https://github.com/tatuylonen/wikitextprocessor) from source, and only "en" and "zh" language codes are supported so far.

**Comment by seth-js** [comment]
Thanks, that fixed it.
