### ISSUE TITLE
Missing form_of tags for some Spanish compound forms

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#195]
Some examples are reversándome, tergiversándoos, trancándolas, habladme, hazlo. I think quite a lot of words are affected.

I think another question is if the senses of these words should contain form_of or compound_of keys (or both), but the examples above contain neither as far as I can see.

I wish everyone a Merry Christmas 😀-

**Comment by kristian-clausal** [comment]
I ended up spending the whole day figuring out what was wrong with my pages/ folder's files (forgot --all-languages in my script for wiktwords...) and then trying to figure out how to actually implement parsing "combined with ..." in form_of...

Congrats, Spanish! You have yourself a very special *kludge* in parse_alt_or_inflection1()/form_descriptions. I'm just brute-force regexing "combined with" and then extracting the tags from that based on these in xlat_tags_map:
```python
    "combined with se": "reflexive", # tecnificarse/Spanish
    "combined with me":
        "object-first-person object-singular", # tergiver/Spanish
    "combined with te":
        "object-second-person object-singular", # tergiver/Spanish
    "combined with le":
        "object-third-person object-singular dative", # tergiver/Spanish
    "combined with nos": "object-first-person object-plural", # tergiver/Spanish
    "combined with os": "object-second-person object-plural", # tergiver/Spanish
    "combined with les":
        "object-third-person object-plural dative", # tergiver/Spanish
    "combined with lo":
        "object-third-person object-singular object-masculine accusative",
    "combined with la":
        "object-third-person object-singular object-feminine accusative",
    "combined with los":
        "object-third-person object-plural object-masculine accusative",
    "combined with las":
        "object-third-person object-plural object-feminine accusative",
```

Please point out if I missed anything.
