### ISSUE TITLE
Replace "nose" with a newer test framework

### ISSUE THREAD

**Issue by yacoder** [tatuylonen/wiktextract#196]
"nose" seems broken since Python 3.10 changed something in collections: https://github.com/nose-devs/nose/issues/1122
And generally "nose" is not maintained.

I'm not an expert in Python test frameworks so I won't suggest a replacement, but maybe I can help migrate if you have a preference for a replacement framework.

**Comment by kristian-clausal** [comment]
We're definitely using nose2 for testing here at Clausal, but requirements.txt does have just "nose" in it. I'm not really familiar with the pitfalls of this, so I'll ask Tatu about it after New Years. The Makefile has nose2. Changes probably just involve a change in requirements.txt and documentation, but better safe than sorry.

**Comment by kristian-clausal** [comment]
Fixed in #197
