### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by ebadi** [tatuylonen/wiktextract#20]
Hello Tatu Ylonen, Thanks for the awesome tool that you have developed. 

As indirectly mentioned in the document, the tools are not able to parse non-English dumps:

> This tool reads the enwiktionary-<date>-pages-articles.xml.bz2 file and outputs JSON-format dictionaries containing most of the information in Wiktionary.

Is there any plan to support other languages in the near future? If it is not a major change, I would be more than happy to contribute to the project and help you add other languages as well.

**Comment by tatuylonen** [comment]
The current version (also the current new version) only extracts data from the English wiktionary; however, it extracts data for all languages in the English dictionary (see [https://kaikki.org/dictionary/](https://kaikki.org/dictionary/) for a list of the languages extracted).

Each Wiktionary uses its own templates.  Now that the code supports expanding templates and Lua macros, implementing support for other wiktionaries would not be too hard, but I estimate it is still a few weeks of work per Wiktionary.  It might be possible to build a more generic version or a configurable version to make it easier to support other Wiktionaries (I know some earlier extractors have been configurable but they did not support expanding templates and Lua macros which are now quite prevalent).
