### ISSUE TITLE
Russian word, ковёр is missing. Only its alternate spelling ковер exists

### ISSUE THREAD

**Issue by mtak-** [tatuylonen/wiktextract#211]
See this kaikki link:
https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%BA/%D0%BA%D0%BE/%D0%BA%D0%BE%D0%B2%D0%B5%D1%80.html

**ковер** is an alternate spelling of **ковёр** in Russian (as people mostly don't write ё), but for some reason wiktextract has no page for **ковёр** which is, of course, the more important page - including all inflections.

I assume it has something to do with ё => е alternate forms in Russian, however, I could *not* find similar examples so perhaps it is another bug.

**Comment by kristian-clausal** [comment]
Fixed in wikitexprocessor by cba632c2bbb8f4ca2b88708aca689985b225e1dd, see https://github.com/tatuylonen/wiktextract/issues/207#issuecomment-1424017035
