### ISSUE TITLE
20230220 Newest wiktionary dump broken on Kaikki.org, shouldn't take long to fix

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#212]
The newest dump on Feb 20th broke a ton of Lua stuff on our end (2.5 million new errors), but happily this seems like a simple, if a bit tedious fix.

Because Wiktextract and Wikimedia use different version of Lua, we have to do a lot of conversions on the fly to get everything work properl-ish (which should get better when Lupa gets the capability to use different versions of Lua), and there's a bit of code standing in for strings.gsub that does some substitutions to make all replacement strings work: that is, on the Wiki side, you can have replacement strings that contain Lua escaped characters like "%[" or "%.", but those are not allowed in the newer version of Lua we have to work with.

Previously, only a few of these escaped magical characters were handled (%[, %. and %-), but the new dump has introduced a lot more. I suspect that somewhere deep in the bowels of an important function or module someone has decided to escape all magical characters "just in case", which wouldn't break anything on their side, but did on ours.

I've committed a quick fix that fixed a bunch of these that replaces all magical characters that I could google. Tomorrow, if all goes well, Kaikki will update, or if it doesn't it at least should have much less Lua errors, and less for me to comb through to find new magical characters to decompose.

**Comment by xxyzz** [comment]
Lupa master branch already supports multiple lua versions. LuaJIT2 should be compatible with MediaWiki's Lua 5.1.5 version and it's faster. I have successfully built the lupa package on Linux bundled with LuaJIT2 with these commands:

```
$ git clone --recurse-submodules https://github.com/scoder/lupa.git
$ cd lupa
$ python -m venv .venv
$ source .venv/bin/activate
$ python -m pip install -r requirements.txt
$ make
$ python -m pip install .
```

Then LuaJIT could be used in Python code:

```python
import lupa.luajit20 as lupa
lupa.LuaRuntime().lua_implementation
```

**Comment by kristian-clausal** [comment]
We're waiting for the new version to hit pip, or something to that effect.

**Comment by kristian-clausal** [comment]
Taking care of about 90K stragglers, which should resolve this issue, but we'll see how it's gone after the weekend.

The previous commit got the number of Lua errors to fall from 2.5M to 90K, but as I thought there was still a gap in the escape-character hunt: if you have two overlapping patterns in strings.gsub, say `%)%.` (from ")." in the original text), when the pattern engine has matched %) it will start the next match from the the second %, which will not match the pattern I used because we had to check whether the escaped character was preceded by a double-% (`%%%%` a twice-escaped %...).

The solution is simple, dumb and brutish: just run the same pattern twice. I *think* this should take care of patterns with three or more overlapping patterns, because the first iteration will take care of the odd matches and the second will take care of the even matches. In any case, with a quick grep to check for errors that match this bug, I think the number of errors will drop under 5000, which I think is still the threshold for allowed Lua errors in Kaikki's regeneration.

**Comment by kristian-clausal** [comment]
Didn't make it to the weekend, *BUT* happily the issue was that it crashed when generating the HTML! This means the wikitextprocessor and wiktextract portions of the regen both passed.

The html-gen portion failed because of some other ruby-stuff (Japanese furigana) I did last week. :man_shrugging: Failed to realize that sending new data as a list with lists wouldn't fly when it expected strings... Not that the previous situation (where we made word links to random bits of furigana fragments) made that much sense. Anyhow, that's now fixed, and after we've got kaikki.org running *at least once, please*, then I'll add some more formatting to the ruby stuff so that what you see on the presentation page shows all the new stuff and makes sense, and all the other committing I need to do.

**Comment by kristian-clausal** [comment]
Everything got down to the finishing line..! except the kaikki.org build server ran out of memory and the processes blocked.

This is essentially a random occurence, because we randomize the order in which languages are processed for this purpose, but I dropped the amount of parallelism from 32 to 28 so it should run tomorrow.

**Comment by kristian-clausal** [comment]
Like yesterday, one of the processes got killed and left the rest hanging in multiprocessing limbo. Gonna drop the amount of parallelism down again and hopefully that'll fix it.

**Comment by kristian-clausal** [comment]
This is frustrating, but after maybe fixing issues... The newest enwiktionary dump from 230301 breaks things in *wiktextract* in a new way!

It took me a while to figure out that there was something *new* going on, and it's now friday afternoon and I *need* this weekend, so there's just going to be a rough fix that is definitely not correct, but it shouldn't break.

In some random submodule (is that the right term?) of `Module:category tree/poscatboiler/data` someone is putting
first order functions into the LABELS table in the description, which screws up stuff in categories.py which expects
a string (as before).

Weekend temporary fix: tostring() everything, it's the only way to make sure. We'll get some garbage data out of it,
but if it works out at least we have something, and grepping for that garbage data should help when trying to figure out
where these functions come from and what to do with them next week.

**Comment by kristian-clausal** [comment]
Finally, kaikki.org updated over the weekend so I'll be closing this issue. There will be some garbage data from the function memory address prints, but that's minor compared to everything not working and shouldn't be hard to fix.
