### ISSUE TITLE
Strange IPA entries in Burmese dictionary

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#220]
Many Burmese words have slashes in their pronunciation section that aren't used for IPA. These get mistaken for IPA transcriptions.

Some examples:

- [ဝမ်းဆွဲ](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E1%80%9D/%E1%80%9D%E1%80%99/%E1%80%9D%E1%80%99%E1%80%BA%E1%80%B8%E1%80%86%E1%80%BD%E1%80%B2.html)
- [စွမ်းအင်](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E1%80%85/%E1%80%85%E1%80%BD/%E1%80%85%E1%80%BD%E1%80%99%E1%80%BA%E1%80%B8%E1%80%A1%E1%80%84%E1%80%BA.html)
- [ခုနစ်](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E1%80%81/%E1%80%81%E1%80%AF/%E1%80%81%E1%80%AF%E1%80%94%E1%80%85%E1%80%BA.html)
- [ပြည်ထောင်စုမြန်မာနိုင်ငံတော်](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E1%80%95/%E1%80%95%E1%80%BC/%E1%80%95%E1%80%BC%E1%80%8A%E1%80%BA%E1%80%91%E1%80%B1%E1%80%AC%E1%80%84%E1%80%BA%E1%80%85%E1%80%AF%E1%80%99%E1%80%BC%E1%80%94%E1%80%BA%E1%80%99%E1%80%AC%E1%80%94%E1%80%AD%E1%80%AF%E1%80%84%E1%80%BA%E1%80%84%E1%80%B6%E1%80%90%E1%80%B1%E1%80%AC%E1%80%BA.html)

**Comment by kristian-clausal** [comment]
Oooh, that's nasty. Hopefully this is just something needs a check for `\n` somewhere. I'll take a look.

**Comment by kristian-clausal** [comment]
Here's a quick fix to the IPA issue: we didn't forbid newlines inside the /IPA string/, so it just ate it up.

The rest of the Pronunciation block is... Pretty messy, so I'll leave it for some other day. I'm not even sure what the "Phonetic respelling" is meant to convey; it just looks like separating စွ from မ်းအင် in စွမ်းအင်, for exampe.
