### ISSUE TITLE
Better handle inline hieroglyph images

### ISSUE THREAD

**Issue by digitalheir** [tatuylonen/wiktextract#226]
For example, consider the hieroglyph [𓈀](https://kaikki.org/dictionary/Egyptian/meaning/%F0%93%88%80/%F0%93%88%80/%F0%93%88%80.html).

Wiktionary includes pictorial representations, since hieroglyph fonts are not widely installed by default. (Also, sometimes the pictures are necessary to indicate complex grouping, in this example consider the very first image, represented by `<hiero>N18:N21*Z1</hiero>`.)

![image](https://user-images.githubusercontent.com/178797/229519814-379017fa-6a44-47a8-86c9-a9eb57e018c9.png)

Wiktionary handles these glosses weirdly, 

``` 
    {
      "alt_of": [
        {
          "extra": "(",
          "word": "𓋰"
        }
      ],
      "glosses": [
        "Alternative form of 𓋰 (\n\n\n\n).",
        "Alternative form of 𓋰 ("
      ],
      "id": "𓈀-egy-symbol-vPio6IPU",
      "links": [
        [
          "𓋰",
          "𓋰#Egyptian"
        ]
      ],
      "raw_glosses": [
        "Alternative form of 𓋰 (\n"
      ],
      ...
    },
```

Note the gloss is duplicated, although one entry has a preponderance of new-lines and the other misses a closing parenthesis.

The other gloss is handled (more) correctly: `"Alternative form of 𓏒 (X4)."`. The image is at least correctly replaced by its alt tag.

At first, I thought this goes wrong because the former alt tag is quite long (`S208`), messing up a heuristic in the source code. But it seems the template code is actually different for both items:

```
# {{alt form|egy|𓋰}} ({{egy-glyph|S208|h=12}}).
# {{alt form|egy|𓏒}} (<hiero>X4</hiero>).
```

It might be beneficial to generate separate entities for `egy-glyph` and `hiero`.

**Comment by kristian-clausal** [comment]
The `{{egy-glyp}}` and `{{egy-glyph-image}}` templates both create tables. The best we can probably do is extract the arguments and format the code as text, except the arguments can contain other {{egy-glyp-image}} templates. This is a right mess.

**Comment by digitalheir** [comment]
I think the template is simple enough to parse and represent as metadata, or perhaps just leave as-is?

 Converting to Unicode is definitely not always possible, since Unicode does not fully support stacking possibilities and many less common hieroglyphs do not have a codepoint.

https://en.m.wiktionary.org/wiki/Template:egy-glyph

**Comment by kristian-clausal** [comment]
This will have to wait until at least next week, after the holidays. I took a crack at it, but it was kind of a mess and I want to try to do it differently.

I need an example of how to format the arguments of egy-glyph. egy-glyph can contain all sorts of nonsense, including `<hiero>` elements and egy-glyph-image at least, and *formatting* stuff like `<br>`. Give me a very simple way to just take these arguments and put them in a pseudo-human-readable string that we can put into our output. In the worst case scenario, we'll just have to put something like `<HIEROGLYPHIC>` there instead. In any case, egy-glyph and egy-glyph-image have to intercepted somehow.
