### ISSUE TITLE
Handle "Glyph origin" header as Etymology

### ISSUE THREAD

**Issue by digitalheir** [tatuylonen/wiktextract#227]
Consider hieroglyph [𓈀](https://kaikki.org/dictionary/Egyptian/meaning/%F0%93%88%80/%F0%93%88%80/%F0%93%88%80.html).

Wiktionary includes a piece on how the glyph was developed:

> ## Glyph origin
> This was originally three different glyphs: one representing a sandy tract 
of land (an island in the Nile or a sandy hill in the flood plain, etc etc ...

Kaikki processor seems to ignore this section.

**Comment by kristian-clausal** [comment]
This seems like a sensible addition, merged and issue closed.
