### ISSUE TITLE
What is the "buffer" program

### ISSUE THREAD

**Issue by erolm-a** [tatuylonen/wiktextract#23]
[This commit](https://github.com/tatuylonen/wiktextract/commit/c9eddfb6ed6b53c905d8bf65c91d381928a03878) introduced parallel processing to the wiktionary dump. While I applaud this, I can't seem to get which "buffer" program @tatuylonen is referring to that should be in the PATH.
It's not hard to figure out what it does: reads from stdin and writes to stdout in a configurable buffered way, but I don't understand:

1. why it's not documented anywhere but the script alone that you need to have a "buffer" program installed;

2. if there is an official program or script that does this.

Because I couldn't answer those questions I wrote a simple C program to get this to work. It would be cool to add some documentation about that tool and possibly link its source code.

**Comment by vbankov** [comment]
I got the same error on a clean ubuntu installation and solved it by installing `buffer` from `apt-get` (https://launchpad.net/ubuntu/bionic/+package/buffer)

**Comment by tatuylonen** [comment]
Yes apt install buffer is the solution for now.  I'll eliminate the need for buffer as soon as I've finished the other stuff (I've been working on Lua macro expansion, which mostly already works, and it will result in significant changes in other code, so I've been holding off on merging other stuff until then).  I recommend using the version on pypi unti the new version is released.  (In retrospect I should have started making the big changes in a branch but too late now.)

**Comment by tatuylonen** [comment]
I've eliminated the use of the buffer problem entirely.  It allowed a bit more parallelism between bzcat and the extractor, but the overall speedup is too small to justify the extra dependency.
