### ISSUE TITLE
Category "Russian spellings with е instead of ё" missing

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#237]
I think it existed in the older dumps, but in the newer ones words like [ёж](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%B5/%D0%B5%D0%B6/%D0%B5%D0%B6.html) don't have the category "Russian spellings with е instead of ё" that is listed on [Wiktionary ](https://en.wiktionary.org/wiki/%D0%B5%D0%B6) anymore. The same seems to be the case for other words like [емкость](https://en.wiktionary.org/wiki/%D0%B5%D0%BC%D0%BA%D0%BE%D1%81%D1%82%D1%8C)

(This is not a big issue, if it turns out the cause is nontrivial, I could work around it.)

Thanks a lot for maintaining this great library!

**Comment by kristian-clausal** [comment]
Template names like "ru-noun-alt-ё" should be banned. You can't even tell whether that's ё or ë.

I'm going to take a look at this, but it might have to do with some changes made recently-ish to how we... something, something. I did something that affected certain categories generated by heads, I think. Ah, age does not come alone...

**Comment by kristian-clausal** [comment]
I haven't exactly fixed anything, but adding ru-alt-ё to a list templates that should always be expanded seems to have done the trick. We'll see the day after tomorrow if all goes well.

**Comment by Vuizur** [comment]
Thanks a lot! Let's hope it works.

**Comment by kristian-clausal** [comment]
Closing as fixed, if you find more examples open a new issue, because it's probably something else that is broken in that case. It's the Anna Karenina principle, all working examples work in the same way, but all broken examples are broken in their own unique ways... Well, not exactly true, but it *sounds* true.

**Comment by Vuizur** [comment]
Awesome, it works now in at least all of the examples I tested. 👍 Thanks!
