### ISSUE TITLE
distinguish contractions from abbreviations ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [tatuylonen/wiktextract#247]
Hello,

I've noticed contractions (ex: like english "don't" or "can't", and like french "des" or "jusqu'à") are indexed as abbreviations with `"pos": "abbrev"`.

I don't know for other languages, but from a french and english grammatical point of view, mixing them together is not correct, since they are two distinct classes of words. 
And also, when I look at the list of english and french abbreviations, I mostly find contractions.

If it is compatible with all other languages grammar, would it be possible to give contractions their own `"pos": "contraction"` class ?

**Comment by kristian-clausal** [comment]
This seems like a sensible change, I'll see how complicated the code is. Grepping for "Contract" didn't net me anything, so it looks like an oversight, although "Contraction" as a pos is kind of weird; "don't" is still a verb.

**Comment by SuperUserNameMan** [comment]
Yes, you are correct about "don't", it is index as verb. I confused with "dont" (without the apostrophe) which is indexed as abbreviation.

If it is too sensitive change, I think I can solve this detail on my end by looking at the `"head_templates": [{"name": "head", "args": {"1": "fr", "2": "contraction"}, "expansion": "qu'a"}]`.

**Comment by kristian-clausal** [comment]
Committed a quick fix for "Contraction" pos-titles: they are now put under "pos": "contraction", instead of "abbrev". More changes next week probably, found some duplication of data going on with parts_of_speech.py and pos_subtitles.json in the data folders.

**Comment by kristian-clausal** [comment]
Besides "contraction" being spelled with a lowercase c, kaikki has updated with entries under that name ("I've" and "dont"), following what was found on Wiktionary. Closing this as fixed.
