### ISSUE TITLE
Thesaurus entries parsing PoS as language

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#258]
Just a reminder for myself:

https://en.wiktionary.org/wiki/Thesaurus:hieno

`{"word": "hieno", "lang": ["Adioukrou", "Adjukru", "Adyoukrou", "Adyukru", "Ajukru"], "lang_code": "adj", "pos": "fi", "senses": [{"glosses": ["good looking, fine"], "synonyms": [{"word": "aistikas", "source": "Thesaurus:hieno"}, {"word": "edustava", "source": "Thesaurus:hieno"}, {"word": "fiini", "source": "Thesaurus:hieno"}, {"word": "hieno", "source": "Thesaurus:hieno"}, {"word": "huoliteltu", "source": "Thesaurus:hieno"}, {"word": "hyvännäköinen", "source": "Thesaurus:hieno"}, {"word": "kaunis [⇒ thesaurus]", "source": "Thesaurus:hieno"}, {"word": "komea", "source": "Thesaurus:hieno"}, {"word": "korea", "source": "Thesaurus:hieno"}, {"word": "nätti", "source": "Thesaurus:hieno"}, {"word": "näyttävä", "source": "Thesaurus:hieno"}, {"word": "pramea", "source": "Thesaurus:hieno"}, {"word": "siisti", "source": "Thesaurus:hieno"}, {"word": "tyylipuhdas", "source": "Thesaurus:hieno"}, {"word": "uljas", "source": "Thesaurus:hieno"}, {"word": "upea", "source": "Thesaurus:hieno"}], "antonyms": [{"word": "ruma", "source": "Thesaurus:hieno"}]}], "source": "thesaurus"}`

There's a bunch of thesaurus entries that are currently misparsed: the PoS is parsed as a language name. For entries that don't parse as language names (like Noun) you get `null` in the data and `lang_code: "noun"`, BUT for adjectives it gets read as the language Adioukrou (lang code adj) and the list of language names in data/en/languages.json is assigned to `lang`, which breaks Kaikki at one point.

`{"word": "lapsi", "lang": null, "lang_code": "noun", "pos": "fi", "senses": [{"glosses": ["child (underage person)"], "synonyms": [{"word": "lapsi", "source": "Thesaurus:lapsi"}, {"word": "lapsonen", "source": "Thesaurus:lapsi"}, {"word": "alaikäinen", "source": "Thesaurus:lapsi", "topics": ["law"]}, {"word": "ipana", "source": "Thesaurus:lapsi"}, {"word": "kakara", "source": "Thesaurus:lapsi"}, {"word": "kersa", "source": "Thesaurus:lapsi"}, {"word": "laps", "source": "Thesaurus:lapsi"}, {"word": "mukula", "source": "Thesaurus:lapsi"}, {"word": "nappula", "source": "Thesaurus:lapsi"}, {"word": "pentu", "source": "Thesaurus:lapsi"}, {"word": "tenava", "source": "Thesaurus:lapsi"}, {"word": "vekara", "source": "Thesaurus:lapsi"}, {"word": "viikari", "source": "Thesaurus:lapsi"}]}], "source": "thesaurus"}`

At first I thought these were new articles (because the first few I checked out *were* from a few days ago), but I found some older articles, so the thesaurus parsing has gone a big wonky from our side.

**Comment by xxyzz** [comment]
I'll create a pull request to fix this bug, I passed these parameters order incorrectly...
