### ISSUE TITLE
Not all the information is extracted from glosses

### ISSUE THREAD

**Issue by shaked6540** [tatuylonen/wiktextract#27]
I don't really know the pattern, but I found this example: 
For the word 'cat', the extracted json for the first definition looks like: 

```json
{
    "word":"cat",
    "lang":"English",
    "heads":[
        {
            "template_name":"en-noun"
        }
    ],
    "senses":[
        {
            "glosses":[
                "An animal of the family Felidae:"
            ]
        }
    ],
    "pos":"noun"
}

```
 (I removed some parts of the senses that weren't relevant to keep this json easily readable)

however, in wiktionary, it looks like this: (the red part is missing from the glosses)
![](https://i.imgur.com/LyiTlvL.png)

**Comment by tatuylonen** [comment]
I checked and these now seem to be correctly extracted.  There was an issue that I fixed a few weeks ago where nested sense lists like this were not correctly processed.  It should now also include the nested senses.
