### ISSUE TITLE
Pronunciation info not present, etymology info not properly expanded

### ISSUE THREAD

**Issue by thelahunginjeet** [tatuylonen/wiktextract#270]
I'm using python 3.9 on MacOS X 10.14.6. I've installed from source (works fine) and run the tests (all of them pass). I then use the command line tool to extract the test document you've got in your tests directory. When I do so, I get no pronunciation data and none of the etymology templates seem to expand properly or be present. For example, in one of the json records for the word "able", there's no pronunciation field at all (despite the presence of an IPA pronunciation on the Wiktionary page) and here's what's in the etymology section:

'etymology_number': 1,
'etymology_text': 'From , from , variant of , , from , from .',
'etymology_templates': []

Any idea what is going wrong?

**Comment by xxyzz** [comment]
The test file [test-pages-articles.xml.bz2](https://github.com/tatuylonen/wiktextract/blob/master/tests/test-pages-articles.xml.bz2) doesn't have template and module pages, so most templates are not expanded.

**Comment by thelahunginjeet** [comment]
I tried this. During db-file creation/extraction - meaning the first step, command:

`wiktwords --db-path /tmp/wikt-db enwiktionary-20230601-pages-articles-multistream.xml.bz2`

I get through about 67% of the pages and then get:

PANIC: unprotected error in call to Lua API (table overflow)

and nothing is written to the wikt-db file.

**Comment by xxyzz** [comment]
You downloaded the wrong file, should use this one: https://dumps.wikimedia.org/enwiktionary/20230620/enwiktionary-20230620-pages-articles.xml.bz2

**Comment by thelahunginjeet** [comment]
Oh man, dumb mistake.  Thanks!  I'll try it with the correct file.

**Comment by thelahunginjeet** [comment]
Same problem. I get about 72% of the way through the dump and then the Lua error gets thrown.  Any idea what might be causing this?

**Comment by xxyzz** [comment]
Please copy and paste the Lua error.

**Comment by thelahunginjeet** [comment]
Sorry, here it is:

PANIC: unprotected error in call to Lua API (table overflow)

**Comment by xxyzz** [comment]
I don't know what that error message mean... Maybe "table overflow" means your machine doesn't have enough memory?

How's your machine's memory usage when you run the code? And could you post more logs around that panic line?

**Comment by thelahunginjeet** [comment]
Hmm. Ok - seems like my best bet may be to try the extraction on a Unix machine.  I will try to get everything installed on the compute cluster I have access to and run it there on multiple nodes.

**Comment by xxyzz** [comment]
Hi @thelahunginjeet. multiprocessing is supported on macOS and Windows, "table overflow" error should be fixed now.

**Comment by thelahunginjeet** [comment]
Wow, thanks!  I'll give it another try.
