### ISSUE TITLE
When will new release be expected?

### ISSUE THREAD

**Issue by vrnmthr** [tatuylonen/wiktextract#28]
@tatuylonen thanks for a great extractor! When will the latest release be expected? I am thinking of using this for one of my projects and want to be sure to use the new one. If you think the current state of the repository is stable I can also build from source. Let me know what you think is best!

**Comment by tatuylonen** [comment]
I'm expecting to release in 2-4 weeks.  I've been working on template and Lua macro expansion. I concluded that was necessary to keep the code maintainable. I've separated the generic template and Lua macro processing to https://github.com/tatuylonen/wikitextprocessor. That work pretty well; some features are still missing but I'm not expecting significant problems. I'll be integrating that code to wiktextract over the next several days, particularly for expanding templates and Lua macros in glosses, pronunciations, etc.  I'm also planning to change how languages and word senses are recognized, but I may leave that to a later version.  Then increasingly many words now have translations or, e.g., thesaurus entries on separate pages and those need to be merged into the main word entries.

The main benefits of the new version will be:
  - much better support for non-english languages
  - more accurate formatting of glosses (new templates seem to appear very frequently; these will be automatically supported)
  - pronunciation and other part are generated using Lua macros for many languages; these should now be properly captured
  - lots of other bug fixes.
