### ISSUE TITLE
Chinese soft redirect {{zh-see}} support

### ISSUE THREAD

**Issue by hftf** [tatuylonen/wiktextract#287]
Hello and thanks for the project. I'm looking into how to automate getting structured dictionary and pronunciation data for Old and Middle Chinese. I noticed that the soft redirect `{{zh-see}}` is [a TODO](https://github.com/tatuylonen/wiktextract/blob/844c87ee900b5ae0da4bc75e065daca22fd9fec0/TODO#L99). I thought I might be able to work around this by parsing it out of the JSON myself, but the redirect target character does not appear at all it seems. For example, using the entry for [䖏] on Wiktionary, [All languages combined/䖏] does not contain the redirect target character "處" at all (and [Chinese/䖏] is a 404).

Is this a not-yet-implemented or a not-working-as-expected situation?

[䖏]: https://en.wiktionary.org/wiki/%E4%96%8F#Chinese
[All languages combined/䖏]: https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E4%96%8F/%E4%96%8F/%E4%96%8F.html
[Chinese/䖏]: https://kaikki.org/dictionary/Chinese/meaning/%E4%96%8F/%E4%96%8F/%E4%96%8F.html

**Comment by xxyzz** [comment]
How about the implementation of #288? It returns:

```
[{'lang': 'Chinese', 'lang_code': 'zh', 'redirects': ['處'], 'word': '䖏'}]
```

**Comment by hftf** [comment]
> How about the implementation of #288? It returns:

Yeah, at a glance this would definitely work for me!

> The kaikki.org website probably can't support this new type of data.

What do you mean by this though?

**Comment by xxyzz** [comment]
OK, I'll merge it then.

I mean the code for generating kaikki.org needs update for this change, no need worry about it.
