### ISSUE TITLE
Turning extracted words into a single dictionary

### ISSUE THREAD

**Issue by jhdeov** [tatuylonen/wiktextract#29]
When I use Wiktextract, the output file `wikt.words` is a sequence of dictionaries. Is there a recommended way to turn this sequence into a single dictionary?

**Comment by kayleachampion** [comment]
+1, this would be a helpful improvement

**Comment by tatuylonen** [comment]
I could easily generate a single list of dictionaries.  The reason I don't currently do so is that the full data takes about 33GB when you load it into memory in Python (individual languages take much less).  It is easier to process with limited memory when it is one dictionary per line.

You can easily read all the data with code like this:
```
  import json
  ...
  all_data = []
  with open("data.json") as f:
    for line in f:
      if line:
        all_data.append(json.loads(line))
```

I'm worried that if I make it a single list, it is harder to process for people who don't have 64GB of main memory on their computers.  Though now you can also download pre-filtered data from [https://kaikki.org/dictionary/](https://kaikki.org/dictionary/).
