### ISSUE TITLE
Incomplete pronunciations for some multi-word wiktionary entries

### ISSUE THREAD

**Issue by mdecerbo** [tatuylonen/wiktextract#3]
Thanks for the helpful package! 

One thing I noticed: the pronunciations extracted for some multi-word wiktionary entries do not include the pronunciation for the first word. This is not true for every multi-word entry; just for some-- two I have found are [T. Rex](https://en.wiktionary.org/wiki/T._rex#English) and [Star Wars Day](https://en.wiktionary.org/wiki/Star_Wars_Day). An extract from the wiktionary dump demonstrating the problem on these two entries is attached.
[starwarsdaytrex.zip](https://github.com/tatuylonen/wiktextract/files/3035809/starwarsdaytrex.zip)

**Comment by tatuylonen** [comment]
I fixed a bug in pronunciation extraction today.  Star Wars Day now seems to be getting IPA pronunciations correctly.  T. Rex does not have pronunciation in Wiktionary (as of today), but T. rex has and that seems to be extracted correctly.
