### ISSUE TITLE
ImportError from wikitext

### ISSUE THREAD

**Issue by anetschka** [tatuylonen/wiktextract#30]
I have tried both installation from source and with pip. However, when trying to replicate the mwe, I get the following error from wikitext: 

from wiktextract import (WiktionaryConfig, parse_wiktionary,
                         wiktionary_languages, PARTS_OF_SPEECH)

>>>   from wikitextprocessor import Wtp, WikiNode, NodeKind, ALL_LANGUAGES
ImportError: cannot import name 'WikiNode' from 'wikitextprocessor' 

Any hints on how to make the installation work?

**Comment by tatuylonen** [comment]
Have you tried more recently?  This may have been glitch in the development version.  It is now getting close to the first release.

I've been using it daily for development (on several machines) and haven't seen anything like this in weeks.

**Comment by anetschka** [comment]
I have, firstly, patiently waited for a reply. I have, secondly, tried now with a newly pulled version of the library. On Windows 10, I still get the above error. On Ubuntu, I get: 

>>> from wiktextract import (WiktionaryConfig, parse_wiktionary, wiktionary_languages, PARTS_OF_SPEECH)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'WiktionaryConfig'

I don't think this issue should be closed.

**Comment by tatuylonen** [comment]
Could it be that you are missing wikitextprocessor?  I don't think it is yet installed automatically (this should change when I make the release, probably this weekend).  [I also need to update the documentation...]  As I responded in another case, I just tried creating a new virtual machine and installed from scratch there, without issues. 

I installed as follows:
```
... first made sure gcc, python3-dev, python3-pip are installed
git clone https://github.com/tatuylonen/wikitextprocessor
git clone https://github.com/tatuylonen/wiktextract
(cd wikitextprocessor && pip3 install -r requirements.txt && pip3 install -e .)
(cd wiktextract && pip3 install -r wiktextract/requirements.txt && pip3 install -e .)
... then I tried extraction:
wiktwords --all --all-languages --out temp enwiktionary-20201201-pages-articles.xml.bz2
```
All went smoothly and it started to run the extraction.

**Comment by anetschka** [comment]
I think I have tried this before and now I tried again. I am working on Windows 10 here. I can now import almost all classes from your introductory example, except wiktionary_languages:

ImportError: cannot import name 'wiktionary_languages' from 'wiktextract'

**Comment by tatuylonen** [comment]
While I don't think this is the cause of your problems, I just realized that wikitextprocessor (and wiktextract/wiktwords) is not likely to work with more than one thread/process on Windows (because Python multiprocessing package uses fork() on Linux but not on Windows as far as I know).  Specifying --num-threads=1 should work.  (I'm not able to test on Windows easily as I don't currently have any Windows machines.)

The problem is that the child processes need access to potentially gigabytes of data (information about pages/templates/Lua modules - the modules themselves are stored in the cache file, but the "index" is in memory).  It might be possible to load the global data on first operation in the subprocess, but it would be a somewhat complex change (definitely would need a proper means of testing).

**Comment by tatuylonen** [comment]
I've published version 1.99.3 on pypi.  Could you try installing now?

Installation instructions in README.md have also been updated.

I just tested by creating a fresh Ubuntu 20.04 virtual machine, using "apt update && apt install build-essential python3-dev python3-pip" and "pip3 install wiktextract", then fetched wikimedia dump using wget, and ran "wiktwords enwiktionary-20201222-pages-articles.xml.bz2" and it started running just fine.

You may also want to use the pre-extracted version at https://kaikki.org/dictionary if installation on Windows doesn't work.  I also welcome any patches to make it work on Windows.

**Comment by anetschka** [comment]
Hi Tatu, thanks for your updates and please accept my best wishes for the new year. I tested the new PyPi version of your module both an Windows and on my Ubuntu subsystem and I confirm that all imports work now, i.e. I successfully executed your example code up to the creation of the wikitextprocessor instance (ctx = Wtp()). No problems were encountered. I also pulled the repo once more and tried executing the unittests, but they failed on my system, probably due to an error in my test setup (nose didn't find the test file). I'd also like to thank you for the greatly extended documentation. As for me, this issue can be closed now. If encounter new problems in the actual parsing, I'll open a new issue.

**Comment by tatuylonen** [comment]
Thanks!  I tested running "nosetests" in the top-level directory on Linux, and it worked for me.
