### ISSUE TITLE
Compressed Download

### ISSUE THREAD

**Issue by tslater** [tatuylonen/wiktextract#31]
Awesome library. Even more awesome that you provide the download pre-computed. I'm wondering if there is a compressed download available (tar, gzip, or similar)? My internet connection is not very good, and I'm betting the data would compress nicely with all the duplicated JSON keys.

If I understand correctly, this is the master link for all languages in English? https://kaikki.org/dictionary/All%20languages%20combined/download-all-senses.json

Looking forward to this big release this week!! (or soon). Been watching for a while.

**Comment by tatuylonen** [comment]
For English, the link is currently https://kaikki.org/dictionary/English/download-all-senses.json.

I just implemented compressed .bz2 file generation in the script that produces the web site (+ related download links).  Only downloads for longer lists have the .bz2 file; individual words don't (that would have added close to 10M more generated files).  The compressed downloads should appear on kaikki.org in about 24 hours, unless something goes wrong with my overnight run, in which case it could be a few days.  The compressed downloads have .bz2 added to the file name (uncompressed downloads also remain available).

**Comment by tslater** [comment]
So awesome. Thanks!!!

**Comment by tatuylonen** [comment]
Note that the links may keep changing in the next couple of weeks.  I've just decided to put "kaikki.org" instead of "download" in the file name to be more descriptive, and I'm also now including language name.  I'll probably also add a version number/date into the name (with "latest" as an alternative to provide a stable path).  After a few weeks the paths should be stable.

**Comment by tslater** [comment]
That all sounds very good. We're excited for the stable release. Been watching the commits roll in. Thanks for all your hard work!
