### ISSUE TITLE
'Please specify a language code in the first parameter' in a lot of glosses?

### ISSUE THREAD

**Issue by zakeryooo** [tatuylonen/wiktextract#319]
I've tried the latest PyPi version (1.99.7) and the latest master branch but when converting the latest enwiktionary dumps

```
wiktwords --pronunciation --linkages --examples --etymologies --descendants --inflections --redirects --out data.json enwiktionary-20230820-pages-articles.xml
```

I'm getting a lot of parser warnings `Please specify a language code in the first parameter;` in the glosses (~22,500 occurrences of it in the dump).

The kaikki version has the same warnings too, i.e. on https://kaikki.org/dictionary/English/meaning/m/ma/male.html the second definition is `Characteristic of this sex/gender. Please specify a language code in the first parameter; the value "Compare masculine, manly." is not valid (see Wiktionary:List of languages).`

Is this a known issue or am I doing something wrong? Thanks

**Comment by xxyzz** [comment]
This is a bug in a SQL query that returns the wrong page("Template:Q" but should be "Template:q") in the wikitextprocessor package, I'll try to fix it.

**Comment by zakeryooo** [comment]
Thanks, perfect now!
