### ISSUE TITLE
Using branches to prevent "the repository may be broken on some days"

### ISSUE THREAD

**Issue by ErnestoBorio** [tatuylonen/wiktextract#32]
Hi, I guess you already have thought of this, but the whole point of source control is to always have a working code base you can build from, usually the master branch.  
And then you have dev branch which you can break as much as you like.

**Comment by tatuylonen** [comment]
Yes, I've since regretted starting to make the changes in master and it took several months longer than intended, but it is now at a point where I'm pretty much ready to make a release and move to working in a branch myself...
