### ISSUE TITLE
spurious "canonical" forms with terms like "x or y"

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#327]
See e.g. 

[true or false](https://kaikki.org/dictionary/All%20languages%20combined/meaning/t/tr/true%20or%20false.html):
```json
"forms": [
    {
      "form": "true",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "false",
      "tags": [
        "canonical"
      ]
    }
  ],
```

 [feast or famine](https://kaikki.org/dictionary/All%20languages%20combined/meaning/f/fe/feast%20or%20famine.html):
```json
"forms": [
    {
      "form": "feast",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "famine",
      "tags": [
        "canonical"
      ]
    }
  ],
```

[believe it or not](https://kaikki.org/dictionary/All%20languages%20combined/meaning/b/be/believe%20it%20or%20not.html):
```json
"forms": [
    {
      "form": "believe it",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "not",
      "tags": [
        "canonical"
      ]
    }
  ],
```

**Comment by kristian-clausal** [comment]
Well, the reason why this happens is pretty obvious. Probably needs a comparison to the article title somewhere. I'll take a look.

**Comment by kristian-clausal** [comment]
Turned out it was a trivial addition to the condition of an if block I made like six months ago to handle this exact problem, except for titles with commas! Hurray! Also, it wasn't in `decode_tags`.

**Comment by kristian-clausal** [comment]
Had a bug in this (which manifested an older bug that had possibly never triggered, but I digress) that should be fixed now: searched for `or` in title instead of ` or ` in title, which broke a bunch of Latin words ending in -or for some reason. Added a couple of tests for this at the same time.

**Comment by kristian-clausal** [comment]
Kaikki has updated now, and it seems the data is better for now. Closing this; if you find anything similarly wrong relating to ' or ' in titles, just post here and I'll reopen.
