### ISSUE TITLE
Extracting specific words

### ISSUE THREAD

**Issue by drkameleon** [tatuylonen/wiktextract#33]
Hi,

And congratulations for the amazing job you've done!

One question: is there any way I can sort of "filter" the extracted data and extract e.g. only a specific set of words?

**Comment by tatuylonen** [comment]
One way is to first run it with something like "wiktwords --cache /tmp/wikt-cache --pages-dir pages --all --all-languages enwiktionary-20201201-pages-articles.xml.bz2" (you can interrupt when it starts Phase 2, i.e., once it starts printing warnings).  After that, you can extract single words with something like "wiktwords --cache /tmp/wikt-cache --all --all-languages --page pages/Words/sa/sample.txt --out sample.out"  (you can also add --human-readable if you just want to investigate it yourself).
