### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by drkameleon** [tatuylonen/wiktextract#34]
Hi,

I've cloned the latest version of the repositories and have the following error:

```
  ... 7010000 raw pages collected
  ... 7020000 raw pages collected
  ... 7030000 raw pages collected
  ... 7040000 raw pages collected
  ... 7050000 raw pages collected
  ... 7060000 raw pages collected
  ... 7070000 raw pages collected
  ... 7080000 raw pages collected
  ... 7090000 raw pages collected
Analyzing which templates should be expanded before parsing
Second pass - processing pages
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/drkameleon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/drkameleon/Downloads/wikitextprocessor/wikitextprocessor/core.py", line 46, in phase2_page_handler
    ctx.start_page(title)
AttributeError: 'NoneType' object has no attribute 'start_page'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./wiktwords", line 228, in <module>
    parse_wiktionary(ctx, args.path, config, word_cb, capture_cb,
  File "/Users/drkameleon/Downloads/wiktextract/wiktextract/wiktionary.py", line 178, in parse_wiktionary
    for ret, stats in ctx.process(path, page_cb, phase1_only=phase1_only):
  File "/Users/drkameleon/Downloads/wikitextprocessor/wikitextprocessor/core.py", line 1241, in reprocess
    for success, ret in pool.imap_unordered(phase2_page_handler,
  File "/Users/drkameleon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'start_page'
```

How do I fix it?

**Comment by tatuylonen** [comment]
That code has since been rewritten.

**Comment by tatuylonen** [comment]
(Sorry already closed this, before noticing this was from yesterday, but now reopened)

I had it run through enwiktionary-20201201-pages-articles.xml.bz2 last night without problems.  Could you provide more information on how this occurred (which command line options etc)?  Clearly ctx is None in your case, but I haven't seen that error.

I usually test with something like "wiktwords --all --all-languages --out all-data.json enwiktionary-20201201-pages-articles.xml.bz2".

**Comment by drkameleon** [comment]
@tatuylonen Hi!

First of all, congratulations for the great work (I've been implementing and using something similar for years, although in Ruby - that's how I came across your project)

I've tested it again (on a DigitalOcean droplet, for CPU-performance reasons) and it did work.

I guess it had something to do with my local python configuration. (I'm not a Python guy at all and I always end up making the whole environment a mess...)

The options I've used in practically all of my tests are:
```
--all
--language English
--out words.json
```

**Comment by ngocsangyem** [comment]
I have the same error, I use this dump[link](https://dumps.wikimedia.org/enwiktionary/20210901/)

```
wiktwords --all --language English --out data.json enwiktionary-20210901-pages-articles.xml.bz2
```

**Comment by tatuylonen** [comment]
Could you

**Comment by tatuylonen** [comment]
Could you please make sure you have the latest versions of both wiktextract AND wikitextprocessor?  I just released new versions on pypi today.  I think this might happen if you have an older version of wikitextprocessor.  I did not see this error when I tested today on a new virtual machine (I used --all-languages instead of --language English, but I think it is unlikely to make a difference).

Which versions of wikitextprocessor or wiktextract are you using, or did you install both from the master branch (https://github.com/tatuylonen/wikitextprocessor and https://github.com/tatuylonen/wiktextract)?

**Comment by ngocsangyem** [comment]
Thanks, @tatuylonen , I just updated to the latest version and it works
