### ISSUE TITLE
https://kaikki.org is down

### ISSUE THREAD

**Issue by william-davies** [tatuylonen/wiktextract#341]
Thank you so much for uploading the pre-extracted data to https://kaikki.org. It's been super helpful and I really appreciate it.

I wanted to raise an issue just to let you know (if you don't already) that https://kaikki.org seems to be down right now. I hope you find time in your busy schedule to get such a helpful website back up.

Thank you!

**Comment by kristian-clausal** [comment]
Sorry, seems the physical server is down at another location: Tatu is going out of his way to check it, and hopefully it'll be up and running soon again.

**Comment by kristian-clausal** [comment]
Should be up again :+1:

**Comment by william-davies** [comment]
Yes it is, thank you very much!
