### ISSUE TITLE
wiktwords does not work

### ISSUE THREAD

**Issue by manugoswami** [tatuylonen/wiktextract#350]
Hi, 

Repeatedly below command fails and either there is error in the name of out file or the .bz2 file even when both are correct.
Not able to run wiktwords due to this . Kindly inform how to use wiktwords.

I am using conda python from cmd

wiktwords --outwiktionary.txt  enwiktionary-20230920-pages-articles-multistream.xml.bz2

Best regards,
Manu

**Comment by xxyzz** [comment]
Please use the non-multistream file: https://dumps.wikimedia.org/enwiktionary/20230920/enwiktionary-20230920-pages-articles.xml.bz2

**Comment by manugoswami** [comment]
Hi,
Many thanks for quick reply. Still this error is appearing. Kindly help.

wiktwords --outwiktionary.txt  enwiktionary-20230920-pages-articles.xml.bz2
                                                ^
SyntaxError: invalid syntax

Best regards,
Manu

**Comment by xxyzz** [comment]
Are you running the command as Python code? That's not gonna work.

I forget multistream bz2 file can be used by the `wiktwords` command because it'll be decompressed to the same xml file.

**Comment by manugoswami** [comment]
Hi , 

Many thanks again for quick response.

Yes I am running command as python code in conda python. Kindly inform correct way to run the command.

Best regards,
Manu Goswami

**Comment by xxyzz** [comment]
That is a shell command... you should run the command in a terminal.

**Comment by kristian-clausal** [comment]
`wiktwords` is a program, so you need to run it like a program; it uses the code in wiktextract and wikitextprocessor, and can be used as the base for something else if you want to make changes to it in Python, but to just run `wiktwords` you need to use a terminal, or the equivalent in Windows.

**Comment by manugoswami** [comment]
Hi,
Many thanks for your quick response.

Again i tried in terminal, Still error. I cannot see any witwords exe or batch or anything resembling command line program it is just a python script.

(base) D:\ons_4\wiktextract-master\wiktextract-master\wiktextract>python wiktwords.py --outwiktionary.txt  E:\ons_4\enwiktionary-20230920-pages-articles.xml.bz2
Traceback (most recent call last):
  File "D:\ons_4\wiktextract-master\wiktextract-master\wiktextract\wiktwords.py", line 23, in <module>
    from wikitextprocessor.dumpparser import analyze_and_overwrite_pages
ImportError: cannot import name 'analyze_and_overwrite_pages' from 'wikitextprocessor.dumpparser' (C:\ProgramData\Anaconda3\lib\site-packages\wikitextprocessor\dumpparser.py)

Best regards,
Manu

**Comment by kristian-clausal** [comment]
How did you install wikitextprocessor? Could you go through the install process? If Anaconda uses the version of wikitextprocessor from the pip repositories, it will be out of date.

**Comment by manugoswami** [comment]
Hi, 
Many Thanks again. Does it mean that wikitextprocessor is incompatiable with wiktextract and they have to be recompiled?

Below steps are done and successful
cd wiktextract
python -m venv .venv
source .venv/bin/activate
python -m pip install -U pip

Below is not successful
python -m pip install --use-pep517 .

Error

ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.


Best Regards,
Manu
-------------------------------------------------------------------------------------------------------



Hi,

Many thanks again.
I installed form pip install in conda python.


> Please read the install section in README file: https://github.com/tatuylonen/wiktextract#installing
> 
> You probably need to change the `source .venv/bin/activate` command if you're using Windows. I think the `.venv/bin/Activate.ps1` file is for powershell.
> 
> And here is the Python venv doc: https://docs.python.org/3/library/venv.html

**Comment by kristian-clausal** [comment]
What is the contents of your wiktextract folder? There should be a setup.py and pyproject.toml in the directory, otherwise something's wrong.

**Comment by manugoswami** [comment]
Hi,

Many Thanks again.

I have built wiktextract and now trying this command but repeatedly facing error

wiktwords --all --all-languages --out data.json enwiktionary-latest-pages-articles.xml.bz2


eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

(base) D:\ons_4\wiktextract-master>wiktwords --all --all-languages --out data.json enwiktionary-latest-pages-articles.xml.bz2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\manug\anaconda3\Scripts\wiktwords.exe\__main__.py", line 4, in <module>
  File "C:\Users\manug\anaconda3\Lib\site-packages\wiktextract\__init__.py", line 5, in <module>
    from .wiktionary import (parse_wiktionary, reprocess_wiktionary,
  File "C:\Users\manug\anaconda3\Lib\site-packages\wiktextract\wiktionary.py", line 20, in <module>
    from wikitextprocessor import Page
ImportError: cannot import name 'Page' from 'wikitextprocessor' (C:\Users\manug\anaconda3\Lib\site-packages\wikitextprocessor\__init__.py)


Best Regards,
Manu

**Comment by manugoswami** [comment]
Hi,
Trying to re-build wikitexprocessor ended up in below error 

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
LINK : fatal error LNK1104: cannot open file 'build\temp.win-amd64-cpython-311\Release\Users\manug\AppData\Local\Temp\pip-install-_qioe47i\lupa_b1f317e587b4473fb01f5fef37309777\third-party\lua51\src\lua51.cp311-win_amd64.exp'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lupa
Successfully built wiktextract wikitextprocessor
Failed to build lupa
ERROR: Could not build wheels for lupa, which is required to install pyproject.toml-based projects

Best Regards,
Manu

**Comment by kristian-clausal** [comment]
I'm sorry to say that I'm not familiar enough with Python on Windows to tell you anything about installation issues (hell, I don't know enough about pip on *Linux* either, for that matter). All I can think of is just uninstalling everything from before and trying again.

**Comment by xxyzz** [comment]
The last error you posted indicts a link error while building the [lupa](https://github.com/scoder/lupa) package, lupa 2.1 will soon be released then a prebuild package will be downloaded instead of build from source and hopefully that would fix the build error on your machine.

 I could write a `Dockerfile` that have all the necessary packages installed and exports the `wiktwords` command.

**Comment by xxyzz** [comment]
I tried to build the package on Windows yesterday but the build process failed with another error: https://github.com/xxyzz/wiktextract/actions/runs/6440359394/job/17489089718#step:4:13847

Maybe the temporary build path is too long or the build command arguments are too long but I can't fix the build error. You could try Linux and macOS, or wait for the new Lupa release.

**Comment by manugoswami** [comment]
Hi , Manu thanks for your kind support.  I simply changed the temp path to below and it worked. 
Kind regards, Manu


set TMP=d:\temp  
set TEMP=%TMP%
