### ISSUE TITLE
feature request: would it be possible for translations to be available on the website? 

### ISSUE THREAD

**Issue by vrnmthr** [tatuylonen/wiktextract#36]
the current word sense dump doesn't seem to include translations...

**Comment by vrnmthr** [comment]
otherwise, is there any way for me to extract translations given the 2.0 release? I can't build it locally and can't get it on pip3 right now...

**Comment by tatuylonen** [comment]
Translations should be on the web site.  They are currently stored with the word for with which they are encoded in Wiktionary (mostly English).  I just checked and they seem to be shown on the website now (there may have been issues in earlier days; the web site was last updated last night).  I also checked and they seem to be included in the downloaded JSON.

If you have an example where they are missing, could you be more specific (word, language)?

(I'll make the release over the weekend unless something critical comes up; after that downloading with pip3 should also work.  Currently you need to use "git clone https://github.com/tatuylonen/wiktextract" to followed by "cd wiktextract && python3 setup.py install -e ." - oh and you first need to do both setps for wikitextprocessor)
