### ISSUE TITLE
Wikimedia markup in sounds.ipa

### ISSUE THREAD

**Issue by DanielSWolf** [tatuylonen/wiktextract#39]
First of all, thank you for this great project! I once tried something similar myself, but gave up when I realized the effort involved in executing all the Lua code, including all the `require`s and external libraries. Great job!

I noticed that in your JSON data, some words contain Wikimedia markup code in `sounds.ipa`. Here is an example (formatting mine):

```json
{
  "pos": "noun",
  "heads": [{ "template_name": "en-noun" }],
  "forms": [{ "form": "anaphases", "tags": ["plural"] }],
  "wikipedia": ["anaphase"],
  "sounds": [
    { "ipa": "/\u02c8\u00e6n\u0259\u02ccfe\u026az/" },
    { "ipa": "[[File:Anaphase.svg|thumb|300px|schematic representation of a cell during anaphase]" }
  ],
  "word": "anaphase",
  "lang": "English",
  "lang_code": "en",
  "senses": [ ... ]
}
```

Across all languages, there seem to be about 200 cases of this.

**Comment by tatuylonen** [comment]
Thanks for reporting this.  The extraction of IPA strings is a bit of a kludge currently.  It basically searches for patterns of /.../ or [...].  This way the link matches even though it shouldn't.  One way to fix it might be to disallow the vertical bar inside the [...] pattern (I'm just not familiar enough with IPA to know for sure whether it can legally occur there).  Do you know if | is ever valid inside an IPA string?

**Comment by DanielSWolf** [comment]
I'm afraid `|` (U+007C VERTICAL LINE) is a valid IPA symbol. It's used to indicate a kind of pause ("minor break"). It's rather rare, but it's valid.

From the little I know about MediaWiki, its syntax uses double brackets: `[[...]]`. Brackets are not valid IPA characters. They can be used to enclose an IPA pronunciation, but are never part of the pronunciation itself. So double brackets are never part of a valid IPA pronunciation. Could that work for you?

**Comment by tatuylonen** [comment]
I just committed a fix to the main branch.
