### ISSUE TITLE
How to extract info for a single word?

### ISSUE THREAD

**Issue by ekaterinatretyak** [tatuylonen/wiktextract#398]
Hey,
Could you please help me to extract information for a single input word? What parameters should I use in parse_wiktionary method?

`parse_wiktionary(ctx, "~/enwiktionary-20231020-pages-articles.xml.bz2", config, word_cb)` - where should I paste the word "car", for example?

Thanks for you answer in advance.

**Comment by xxyzz** [comment]
[`parse_wiktionary()`](https://github.com/tatuylonen/wiktextract/blob/f66999a16682963197f5cae4c9bba96f684506b9/src/wiktextract/wiktionary.py#L88) can't be used to extract a single page. You could download extracted JSON data from kaikki.org or use the `--page` option of the `wiktwords` command.

**Comment by ekaterinatretyak** [comment]
Please tell me how to call `wiktwords` as a library? And where should I paste an input word?

**Comment by xxyzz** [comment]
You could take a look of the [`process_single_page()`](https://github.com/tatuylonen/wiktextract/blob/f66999a16682963197f5cae4c9bba96f684506b9/src/wiktextract/wiktwords.py#L61) function and modify the code for your needs. But I don't recommend you doing that because this project is supposed to be used as a shell command not a Python library.

**Comment by kristian-clausal** [comment]
*If* you want to use it as a library, take a look at what is done in wiktwords.py and wiktionary.py in particular. wiktwords.py is the user-facing portion that becomes the wiktwords command when wiktextract is installed, wiktionary.py acts as a bridge between wiktwords and the rest of wiktextract and wikitextprocessor.

Wikitextprocessor is used to parse the wikitext data in the generated database file, and then wiktextract tries to interpret the parse trees wikitextprocessor has generated as a source of data.

**Comment by kristian-clausal** [comment]
If you need any more help with something, please go ahead and open a new issue; this seems like it's quieted down, so closing it.
