### ISSUE TITLE
wiktextract does not seem to work with Afrikaans language

### ISSUE THREAD

**Issue by Code4SAFrankie** [tatuylonen/wiktextract#4]
Trying to extract Afrikaans with the following code returns 0 entries.

import json
import wiktextract

fh = open("output.json", "wb")
def word_cb(data):
    fh.write(json.dumps(data))

ctx = wiktextract.parse_wiktionary(
    r'E:\Downloads\WikipediaAF\afwiktionary-20190301-pages-articles.xml',
    word_cb,
    languages=["Afrikaans", "Translingual"])

print("{} English entries processed.".format(ctx.language_counts["Afrikaans"]))
print("{} bytes written to output.json".format(fh.tell()))

fh.close()

This is on Windows 10 using WinPython 

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

**Comment by tatuylonen** [comment]
The tool only supports parsing enwiktionary.  However, enwiktionary contains definitions for many languages.  I don't know how complete the coverage for Afrikaans is.  The other wiktionaries seem to have glosses and all tags in the separate language, and adding support for parsing non-english wiktionaries would be a significant effort.
