### ISSUE TITLE
external subpages are not parsed

### ISSUE THREAD

**Issue by vrnmthr** [tatuylonen/wiktextract#40]
I was looking through the data and the page for "book" (https://en.wiktionary.org/wiki/book#Translations) does not have translations actually listed on the page. It has a link to an external translation subpage (https://en.wiktionary.org/wiki/book/translations#Noun) which does not seem to be included with the data. 

There are ~100 odd of these (all listed here: https://en.wiktionary.org/wiki/Category:Translation_subpages) types of pages.

Is it possible to include these as well?

**Comment by tatuylonen** [comment]
You are correct and they absolutely should be parsed.  This is on my todo list (I've been working on other things in the last couple of months but I can now put some work into wiktextract again).

**Comment by tatuylonen** [comment]
I just implemented parsing translations from /translations subpages and committed the code in the main branch.
