### ISSUE TITLE
No head templates for Russian

### ISSUE THREAD

**Issue by jsannemo** [tatuylonen/wiktextract#405]
Russian has stopped getting head templates sometimes between https://github.com/tatuylonen/wiktextract/issues/314 and now. 

@kristian-clausal sadly I never checked a dumps since our above conversation, so it's possible that commit broke it?

**Comment by kristian-clausal** [comment]
Please give some examples. What is broken?

**Comment by jsannemo** [comment]
All Russian words, e.g. https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%B2/%D0%B2%D0%BE/%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81.html has lost the "head_templates" field in the JSON as far as I can tell

**Comment by jsannemo** [comment]
All Russian words, e.g. https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%B2/%D0%B2%D0%BE/%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81.html has lost the "head_templates" field in the JSON as far as I can tell

**Comment by kristian-clausal** [comment]
Thanks, I'll take a look at this probably next week.

**Comment by kristian-clausal** [comment]
@jsannemo Kaikki.org should update by tomorrow, hopefully xxyzz's bugfix will show, so keep your eyes peeled! :eye:

**Comment by jsannemo** [comment]
Head templates back, thanks for the quick turnaround! 😍

**Comment by kristian-clausal** [comment]
xxyzz fixed this ages ago, when the Trees of Valinor still lit the world, we just had trouble with kaikki.org, lol.
