### ISSUE TITLE
Outputting original wikitext

### ISSUE THREAD

**Issue by BrianSladek** [tatuylonen/wiktextract#41]
Would it be possible to output the original wikitext in the dumps? The original wikitext is useful for pulling out discrete metadata about the definition. For example, the original wikitext for the definition of "gave" is {{en-simple past of|give}}. If I had this wikitext, I could parse out the discrete metadata of tense=simple past and lemma = give which would be useful in my case because I want to be able to filter out definitions of inflected words from my dataset. 

This is a great tool, thanks.

**Comment by tatuylonen** [comment]
The type of tags you refer to (there are hundreds if not thousands of them in total across all the languages) are already available under the "heads" key in the word entry (please create an issue if you see a word where this is not the case - it is possible there are some tags it doesn't recognize for this).

These tags are further semantically parsed into "tags" and "forms" fields, so inspecting them might be an easier way to recognize inflected forms, at least if you want to work with multiple languages.  (I think "tags" is in a word sense, while "forms" is at word level)

There are the "form_of" and "alt_of" fields.  If the word was recognized as an inflection of another word, then "form_of" should be set to the base form.  Just checking for the presence of "form_of" might do what you want.  "alt_of" is used simularly if the word is recognized as an alternative form (e.g., abbreviation, dialectal form, regional variant) of another word.  I think these are always stored in the word sense when they exist.

**Comment by BrianSladek** [comment]
OK, great. Actually, I see now that this seems to be working pretty well for most words.

From my testing, it does seem to miss at least one important template: es-verb form of. Most Spanish verbs use this template.

For example,
[https://kaikki.org/dictionary/Spanish/meaning/a/ab/abres.json](url) should link to the lemma of abrir.
[https://kaikki.org/dictionary/Spanish/meaning/c/co/corres.json](url) should link to the lemma of correr.

**Comment by tatuylonen** [comment]
The problem was that tú was not recognized (tu was).  Thus forms that included tú in the description were not recognized.  I've just committed a fix in the main branch.
