### ISSUE TITLE
Chinese "redirects"

### ISSUE THREAD

**Issue by noinkling** [tatuylonen/wiktextract#43]
There are a lot of Chinese words using simplified characters that simply link to their traditional counterpart(s), for example: https://en.wiktionary.org/wiki/%E4%B8%80%E4%BC%9A%E5%84%BF

Some of these are just single characters, which may have multiple links since correspondence is not 1:1. They also carry a little information of their own. Example: https://en.wiktionary.org/wiki/%E5%84%BF#Chinese

Currently these entries don't seem to be included in any way.

**Comment by tatuylonen** [comment]
Wiktextract itself should extract redirects (and I just checked that at least some are included in its output).  However the tool that generates the web site doesn't currently handle them (and probably drops them from the JSON files that it outputs).

I should probably 1) make the original extracted raw JSON file available, and 2) implement support in the HTML generator. 

I added both to my TODO list.

**Comment by tatuylonen** [comment]
I've implemented copying the raw wiktextract output onto the website whenever it is updated.  There will a link at the end of the dictionary list page https://kaikki.org/dictionary/.  The web site generation with this update is currently running and the download link should appear on the site later today (in about 6 hours).

**Comment by tatuylonen** [comment]
I forgot to "git pull" the script that generates the web site (the generation is run on another machine), so the link should be there tomorrow...

**Comment by noinkling** [comment]
Thank you for implementing a link to the raw data, however it would still be much more manageable for these words to appear *somewhere* in the language-specific/post-processed data on the site. That's what I interpreted "implement support in the HTML generator" to mean, but I may have misunderstood. Is there any intent to do so?
