### ISSUE TITLE
French edition contains translations with no language code (trlang)

### ISSUE THREAD

**Issue by tatuylonen** [tatuylonen/wiktextract#467]
It looks like the French edition extraction contains translations with no language code, i.e., trlang is missing or null.

Also, the French edition uses part-of-speech values "onomatopoeia" and "typographic variant".  Generally, these would better be described as the proper part-of-speech and "onomatopoeic" tag and alt-of tag + alt_of field, respectively.  Is the actual part-of-speech available in the original data?

**Comment by xxyzz** [comment]
The translation language code is extracted from the template [T](https://fr.wiktionary.org/wiki/Modèle:T)'s first parameter, the template document says for unknown language the first parameter is not language code and I didn't notice this case.

The POS type is extracted from the subtitle "S" template's first parameter: https://fr.wiktionary.org/wiki/Wiktionnaire:Liste_des_sections_de_types_de_mots. I'm not sure what's the proper POS name of "onomatopée" and "variante typographique" so I use the closest English translation...
