### ISSUE TITLE
German edition extraction contains many entries with no senses, etc

### ISSUE THREAD

**Issue by tatuylonen** [tatuylonen/wiktextract#468]
There seem to be quite of a few entries in the German edition extraction with no senses.  It would be better to have at least one sense (if there simply is no gloss, add a sense with no gloss but the "no-gloss" tag).

Also, there is part-of-speech "lexeme".  It would be better to use one of the existing part-of-speech values, e.g.: "prefix", "suffix", "infix".

For auxiliary verbs, instead of part-of-speech "aux", it would be better to use part-of-speech "verb" and tag "auxiliary" (and possibly also "modal" where applicable).

These would make the data more consistent with the English edition, and I think that is important.

**Comment by xxyzz** [comment]
"no-gloss" tag was added in #565, and POS types fixed in #685. Sorry for overlook this issue...

And all check JSON errors are fixed for de edition. Close as resolved.
