### ISSUE TITLE
German edition extraction has "ipa" fields containing lists

### ISSUE THREAD

**Issue by tatuylonen** [tatuylonen/wiktextract#477]
The German edition extraction seems to have all "ipa" fields (under "sounds") as list.  The value should be a string.  If there are multiple alternative IPAs, they should be encoded as separate dicts under "sounds", preferably with "tags" field containing tags identifying how they differ.

**Comment by kristian-clausal** [comment]
I thought someone (or I?) had taken care of this, there were other issues similar to this). I'll take a look.

**Comment by tatuylonen** [comment]
Turns out the run did not re-extract, so it probably used a wiktextract version that was a few days old.

**Comment by kristian-clausal** [comment]
Actually we looked at this, and it turned out just to be something that I missed from my runs because for some reason my extractions were missing all "ipa"-fields! This needs to be fixed like it was in Spanish (and others?).

**Comment by kristian-clausal** [comment]
I missed a lot of things in my runs because I forgot `--all` when running Wiktwords... Oopsie daisy...

**Comment by kristian-clausal** [comment]
Closed as complete.
