### ISSUE TITLE
Zh-edition missing some entries

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#492]
https://zh.wiktionary.org/wiki/sauna#%E8%8A%AC%E8%98%AD%E8%AA%9E is missing, probably because the sense is not parsed correctly.

Either "f. ..." is just a mistake on that page, or it's a specific zh-edition syntax for lists.

**Comment by xxyzz** [comment]
Clearly a low quality page, don't expect much from these pages... Whole gloss in plain text and not in a list, `f.` is suppose to a feminine gender tag.

This page shouldn't be missing, only the second language block somehow was added to the first block.

We already put more effects than creating that page, lol.

**Comment by xxyzz** [comment]
Garbage in, garbage out... Page https://zh.wiktionary.org/wiki/sauna should be edited:

```diff
==西班牙语==
-f.  桑那浴，(芬兰式)蒸气浴{{-pt-}}
+f.  桑那浴，(芬兰式)蒸气浴
+==葡萄牙語==
桑拿浴
```

The header template should start at next line and the standard layout is using the wikitext `==` header.

**Comment by kristian-clausal** [comment]
Thanks, I wasn't sure about the specific ways of doing things on zh. Every wiktionary is so different... :cry:

**Comment by xxyzz** [comment]
The zh edition is not very different, many pages are copied directly from the en edition. But it has fewer active editors and it won't take long to find a page has red Lua errors...
