### ISSUE TITLE
Non-ASCII character error

### ISSUE THREAD

**Issue by abalvet** [tatuylonen/wiktextract#5]
Here is the message I get when I try to launch wiktwords wiktionary/frwiktionary-20190520-pages-articles-multistream.xml.bz2 --out fr.wiktionary.txt --language FRENCH --linkages

Traceback (most recent call last):
  File "/usr/local/bin/wiktwords", line 15, in <module>
    import wiktextract
  File "/usr/local/lib/python2.7/dist-packages/wiktextract/__init__.py", line 5, in <module>
    from wiktextract.wiktionary import parse_wiktionary, PARTS_OF_SPEECH
  File "/usr/local/lib/python2.7/dist-packages/wiktextract/wiktionary.py", line 295
SyntaxError: Non-ASCII character '\xce' in file /usr/local/lib/python2.7/dist-packages/wiktextract/wiktionary.py on line 295, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ZanSara** [comment]
Seems like you're running Python 2.7. The README states that this library has been tested only on Python 3 (https://github.com/tatuylonen/wiktextract#installing), so I guess you should upgrade your Python version.

**Comment by tatuylonen** [comment]
This tool only supports parsing the English Wiktionary.  However, the English wiktionary contains rather extensive definitions for French words.  I have, however, not tested parsing the French words and some tweaking is probably needed to capture inflection information, etc.
