### ISSUE TITLE
config.OTHER_SUBTITLES mixing strings and lists of strings

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#500]
I've been doing type annotations, and OTHER_SUBTITLES switching between strings in one source data file ('other_subtitles.json') and lists of alias strings another is messy, we should probably have better separation for that. The English extractor uses, for example, `wxr.config.OTHER_SUBTITLES["translations"]` as a string, assuming that it is a very specific term used in Translation sections and translation subpages, while the French one has a bunch of aliases and synonyms.

**Comment by xxyzz** [comment]
The fr edition's title JSON files also have a different meaning, the data are the first parameter values of the [S](https://fr.wiktionary.org/wiki/Modèle:S) title template. Maybe we should change all values in the "other_subtitles.json" file to list?

**Comment by kristian-clausal** [comment]
I think that lists should probably be kept for aliases, and 'definite' versions should be separate, in another file? `OTHER_SUBTITLES` is a bit too broad as a name, it doesn't say what it does. All the _SUBTITLES data collections are different, LINKAGE_SUBTITLES is a dict is "section name in language" -> "internal_name_for_section", POS_SUBTITLES is a dict where the values are dicts with fields containing data about the POS, and OTHER_SUBTITLES is a dict where the values are mixes of lists of strings and strings. Could use some cleaning up.

Other things: linkage_subtitles is "name in language" -> "our_internal_name_string", while other_subtitles is opposite, internal_name_string -> name. POS_subtitles is also "name" -> "internal_name".

**Comment by xxyzz** [comment]
I don't think the code needs to know whether a string is alias, separate them to different files also requires combine them when loading the files.

I think most title strings are used in extractor folders and if they are not used outside they could be hard coded in extractor code.

**Comment by xxyzz** [comment]
I think the title JSON files was added before we using separate extractors for different editions, and at that time the titles need to be loaded dynamically according to the dump file language code. But now because extractor code are loaded dynamically we don't need to do that. And all the title variables are indeed only used in extractor/* folders.

**Comment by kristian-clausal** [comment]
That is very true, switching to consts should be pretty easy then.

**Comment by kristian-clausal** [comment]
Closed as complete.
