### ISSUE TITLE
Bzipped JSON dump?

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#52]
I used to download the bzipped version of the JSON dump, because it's much smaller and hence also quicker to download. However, I just noticed that https://kaikki.org/dictionary/English/kaikki.org-dictionary-English.json.bz2 no longer exists. Is that just an oversight/temporary issue or are the bzipped dumps gone?

**Comment by tatuylonen** [comment]
The web server now automatically uses HTTP-level gzip compression for the transfer of all larger pages and files (whether download or browsing).  This is implemented using nginx gzip_static option, so there is actually a .gz file in the file system for all such files (and it is actually possible to download it using that path).  I think all modern browsers support HTTP-level compression these days.  (I don't know if wget/curl do though)

Thus providing separate compressed versions seemed redundant and added unnecessary complexity, so I removed it.  Is there still a real need for separate compressed files?  (If you still need a compressed version, adding .gz to the path should work)

**Comment by ChristianSi** [comment]
I use Python (request.urlretrieve) to redownload the file when it has changed. I've no idea whether that uses HTTP-level compression, but I've now switched to use .gz explicitly, and that works fine. Thanks!

A (very loosely) related question before I close this: I notice that many translation words now start with `^ `, e.g. the Turkish translations of "woman" include "^ gacı" and "^ cıvır". This seems to be the case whenever the word DOESN'T have its own entry. Is this a deliberate change? I didn't spot anything about it in the documentation.
