### ISSUE TITLE
Canonical form contains the word 'or'

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#526]
![Screenshot from 2024-02-28 22-49-48](https://github.com/tatuylonen/wiktextract/assets/24891609/feae868f-ee5c-4445-ba61-d0dfc7c7581c)
![Screenshot from 2024-02-28 22-49-59](https://github.com/tatuylonen/wiktextract/assets/24891609/091b7178-7423-4d85-ad73-2dfd98e5ea0c)
![Screenshot from 2024-02-28 22-50-09](https://github.com/tatuylonen/wiktextract/assets/24891609/fafe4409-b7c4-4942-b74c-5f79efd8bb15)

First issue here, sorry about any blunders. 

I am working on https://github.com/themoeway/kaikki-to-yomitan and run into little things like this every now and then.  I'd like to fix things myself, but when I tried setting up the project locally, IIRC, I got an ETA of ~5 days on `wiktwords --db-path en_20230801.db enwiktionary-20230801-pages-articles.xml.bz2`, so I gave it up. If there's a better way to get setup for testing changes I could give it another go.

**Comment by xxyzz** [comment]
You could try the `--page` commend argument to process a single page.

**Comment by kristian-clausal** [comment]
After you've created the .db 'cache' file you should not use the dump as a parameter anymore, otherwise you're just recreating the .db file and then starting the process. I'll take a look at this issue, it just needs a little kludge.

**Comment by kristian-clausal** [comment]
There, yet another re.sub call that should fix everything. :smiling_face_with_tear:... This might mess with words that end with ` or` *and* have heads that are extremely short, so I'll have to check that now, but that's unlikely.

**Comment by kristian-clausal** [comment]
It wasn't unlikely at all! Well, now this simply checks if the head ends with " or" and then checks if it ends with the title of the page, otherwise it removes the " or". `for ... else` is so weird; if you didn't happen to know (I always forget which way it goes because I never use it), a `for` loop can have an `else` that executes only if the loop terminates normally (without breaking).

**Comment by StefanVukovic99** [comment]
Thanks for the help guys!

>`--page` command argument to process a single page

have i understood correctly that I must have the .db file before running that? or does having the .db file just make it faster? also, how big (in GB) is the .db file, could i download it from somewhere instead of generating it locally?

**Comment by StefanVukovic99** [comment]
I'm running it on [colab](https://colab.research.google.com/drive/1O7BfGzYEkZwmL2nnNUnApap43ej7bs5a?usp=sharing) now. It's a lot faster than on my machine. Maybe they kick me out midway though, not sure.

**Comment by kristian-clausal** [comment]
Creating the .db file should not take that long, you're running the whole Wiktextract process (processing every page). I recently added the parameter `--skip-extraction` if you want to be sure that you're just doing dump file database caching.

**Comment by kristian-clausal** [comment]
An issue might be that "extraction" is ambiguous, and reads as both "extract pages from dump file to database" and "use wiktextract to process pages"...
