### ISSUE TITLE
57402336 Lua errors in 2024-03-01 dump (English edition)

### ISSUE THREAD

**Issue by tatuylonen** [tatuylonen/wiktextract#529]
Extraction from the latest dump (2024-04-01) fails with 57402336 Lua errors.  The vast majority seem to be the same error in loading links/templates:

Thesaurus:coward: ERROR: LUA error in #invoke('links/templates', 'l_term_t') parent ('Template:link', {1: 'en', 2: 'nancy', 3: 'nancy'}) at ['Thesaurus:coward', 'ws', '#if', '#if', '#if', '#if', 'l', '#invoke', '#invoke']
        Loading module failed in #invoke: links/templates
[string "Module:utilities/require when needed"]:6: attempt to index upvalue 'loaded' (a nil value)

girişmək/Azerbaijani/verb: ERROR: LUA error in #invoke('links/templates', 'l_term_t', 'notself=1') parent ('Template:l-self', {1: 'az', 'accel-form': 'negative|potential|1|s|subj', 2: 'girişəmməyəm'}) at ['girişmək', 'az-conj', 'l-self', '#invoke', '#invoke']
        Loading module failed in #invoke: links/templates
[string "Module:utilities/require when needed"]:6: attempt to index upvalue 'loaded' (a nil value)

Wiktextract category tree extraction: ERROR: LUA error in #invoke('links/templates', 'l_term_t', 'face=term') parent ('Template:mention', {1: 'en', 2: 'yesterday'}) at ['Wiktextract category tree extraction', 'm', '#invoke', '#invoke']
        Loading module failed in #invoke: links/templates
[string "Module:utilities/require when needed"]:6: attempt to index upvalue 'loaded' (a nil value)

**Comment by kristian-clausal** [comment]
`Module:utilities/require when needed` was created last month and is where the nil-index error seems to happen.

https://en.wiktionary.org/w/index.php?title=Module:utilities/require_when_needed&action=edit

```lua
local loaded = package.loaded
local require = require
local setmetatable = setmetatable

return function(text, key)
	local module = loaded[text]
```

Issue is with `package.loaded`, something that doesn't appear in any 'production' module code outside of Theknightwho's own snippets before this. It's basically a table of all currently loaded modules, and apparently 'nil' in our implementation. Usually module code would use `require`, which apparently does call package.loaded according to the documentation as a first step to check if there's anything there.

**Comment by xxyzz** [comment]
Use the [loader_cache](https://github.com/tatuylonen/wikitextprocessor/blob/a4ec33141b33d6ec7921b8903783ef49c2a34267/src/wikitextprocessor/lua/_sandbox_phase1.lua#L11) table as `package.loaded` probably could fix this Lua error.

**Comment by kristian-clausal** [comment]
Looking at the module code more closely:

```lua
return function(text, key)
	local module = loaded[text]  -- fails here because loaded is `nil`
	
	if module then
		return key and module[key] or module
	end
```

it handles a nil result from `package.loaded` gracefully (as it should). In this case, we don't need to have any content in `package.loaded` at all, just an empty table, which we can add to `_sandbox_phase1`:

```lua
-- package is not really used anywhere in the Wiktionary module
-- codebase, EXCEPT ja-translit uses package.loaders as a test
-- to check whether something can be loaded..?
-- Just to take care of this special case, we create a new
-- package table (inserted into the env["package"] slot later below,
-- with a new loaders table (not a function, but a list of functions)
-- where only the second entry returns a function that returns the
-- result of trying to get a new loader...
local new_package = { loaders = { nil, new_loader },
                      loaded = {} }
```

We already have a kludge here to handle some rare use of package.loaders for certain modules, so we can just add `package.loaded` at the same time, and hopefully nothing breaks.

I am still running on an old dump so it'll take a moment before I can test this properly on the material.

**Comment by kristian-clausal** [comment]
Got the new dump running, and yeah, having `package.loaded = {}` really seems to solve this issue.

I did not write tests for this, because we're not really implementing package.loaded correctly, and any test would be misleading and incorrect.
