### ISSUE TITLE
broken expansion and canonical form on German letters

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#533]
For the letter S (i think a couple others are also affected):

kaikki.org-dictionary-German.json:
```json
{
"head_templates": [
    {
       ...,
       "expansion": "S {{#if:|({{{tr}}}) |}}(upper case, lower case s)"
    }
], 
"forms": [{"form": "S {{#if:{{{tr|}}}|{{#ifexist:Wiktionary:{{{langname}}} transliteration|", "tags": ["canonical"]}...]
}
```

When i run wiktextract locally with the 20240202 dump it looks fine. However on 20240301 dump i get errors, and the output is missing a lot.
```
2024-03-08 14:55:21,341 INFO: Capturing words for: de
S: ERROR: LUA error in #invoke('qualifier/templates', 'qualifier_t') parent ('Template:qualifier', {1: 'Variations of letter S'}) at ['S', 'mul-script/Latn-list', '#switch', '#switch', 'mul-script/Latn/letters-list', '#switch', '#switch', 'qualifier', '#invoke', '#invoke']
...
```

EDIT: i see now #529, but don't understand the fix

**Comment by xxyzz** [comment]
This is probably because the wikitextprocessor code can't parse the [head-lite/core](https://en.wiktionary.org/wiki/Template:head-lite/core) template correctly.

**Comment by xxyzz** [comment]
I think it's a bug in [repl_templ()](https://github.com/tatuylonen/wikitextprocessor/blob/f2fbe0495f975c5b28b16aa1a8ba8640217efaa9/src/wikitextprocessor/core.py#L657), `m.starts` return the index of the original text not the matched group text.
