### ISSUE TITLE
Duplicate senses in English word "abstract"

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#535]
Please see here:

https://kaikki.org/dictionary/English/pos-adj/abstr_dot_--abyssopelagic%20water.html

**Comment by kristian-clausal** [comment]
Reopening to confirm this worked out.

Kaikki will take a while to update again (it's on manual because Tatu has made big changes to the whole pipeline; most recently we ran out of disk space :') ).

**Comment by yolpsoftware** [comment]
@kristian-clausal thanks for the fix!

Do you have some kind of versioning for the output? How can I see when the update on Kaikki is complete?

**Comment by kristian-clausal** [comment]
At the bottom of each page there is a date of generation, a date for the specific dump file from Wiktionary we use, and (when it gets added in again) the commit hashes of wiktextract and wikitextprocessor used in the processing.

**Comment by yolpsoftware** [comment]
Looking good now!

**Comment by kristian-clausal** [comment]
Great, closing as complete. :+1:
