### ISSUE TITLE
Category "English phrasal verb" missing in "turn up"

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#537]
The word "turn up" had, in an earlier version of the kaikki.org JSON outputs, the category "English phrasal verbs" in one of its senses.

Today, this category is missing from there, even though the Wiktionary entry still has the category:

https://kaikki.org/dictionary/English/meaning/t/tu/turn%20up.html
https://en.wiktionary.org/wiki/turn_up

Would be nice if this could be added again. Other phrasal verbs still have it:

https://kaikki.org/dictionary/English/meaning/r/ro/root%20around.html

**Comment by kristian-clausal** [comment]
Reopening after merging to give the poster a chance to check if it worked out.

**Comment by yolpsoftware** [comment]
@kristian-clausal Looking good, thanks!

So grateful for the work of you guys on this project 🙏🏻

**Comment by kristian-clausal** [comment]
Thanks, good to hear things are looking ok.
