### ISSUE TITLE
Server reports wrong file size for full dictionary

### ISSUE THREAD

**Issue by DanielSWolf** [tatuylonen/wiktextract#55]
The [full dictionary file](https://kaikki.org/dictionary/All%20languages%20combined/kaikki.org-dictionary-all.json) has a size of about 4 GB. However, when attempting to download it, the server reports a file size of only about 500 MB.

When downloading the file through a browser, this merely results in a broken progress indicator that quickly reaches 100%, then stays there. I'm downloading the file throught a script, and the fact that the actual file size is several times as large as the reported file size actually leads to an error in the library I use.

Here is the server response:

```text
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Wed, 02 Jun 2021 08:35:27 GMT
Content-Type: application/json
Content-Length: 516777480
Last-Modified: Mon, 31 May 2021 22:56:43 GMT
Connection: keep-alive
ETag: "60b569ab-1ecd6608"
Content-Encoding: gzip
Expires: Wed, 02 Jun 2021 09:35:27 GMT
Cache-Control: max-age=3600
```

**Comment by tatuylonen** [comment]
This is a rather interesting observation.  I'm not sure what HTTP is supposed to report as Content-Length when using "Content-Encoding: gzip".  It is reporting the size that actually gets transferred, not the uncompressed size.  This could be correct, a bug in nginx gzip_static option, or my configuration error.  I'll investigate tomorrow.

**Comment by tatuylonen** [comment]
Googling for this, it looks like the Content-Length should be the length of the encoded content when using Content-Encoding: gzip.  Thus it looks like it is sending the correct length.

Anyway, a link to the .gzip file is now on the web site and I understood from earlier emails that the issue had been solved for you so I'll close this ticket.
