### ISSUE TITLE
Translations can get duplicated if they are listed on separate pages

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#57]
The page https://en.wiktionary.org/wiki/iron/translations contains translations of "iron", but only for the noun.

On the [main word page](https://en.wiktionary.org/wiki/iron#English), "iron" is also listed as an adjective and a verb – in these cases, the translations are listed directly on the page.

In the Kaikki dump, however, the noun senses listed on the separate page (especially the most common sense, "chemical element Fe", but supposedly also the others) appear three times: they are considered translations not only of the noun, but also of the adjective and the verb.

I don't know if other words where translations are on a separate page have the same problem.

**Comment by tatuylonen** [comment]
This is a mysterious one. The duplicates are not coming through normal translation parsing.  The translations sub-page is being processed only once.  Also they are not being copied by disambiguation.  Still investigating it.

**Comment by tatuylonen** [comment]
I found the cause of this. The translations section under Noun was a subsection of Related terms, and the test for whether we are inside a part-of-speech section only looked at the immediately higher-level title.  As a result, it was storing the Noun translations in etym_data, which gets copied to all parts-of-speech under that etymology, and that led to duplication of the translations.

I just committed the fix and it should be reflected on the web site tomorrow.

**Comment by ChristianSi** [comment]
Nice, but it seems that you didn't yet deploy the fix? The latest dump (from 9 Jun) still has this issue.

**Comment by tatuylonen** [comment]
All my extraction/web site update runs since then have failed.  I finally found the main problem today (a list was reused instead of being copied in certain situations, and then it was expended into itself much later, which resulted in 64-million element category lists - without exception from Python! - which made things extremely slow).  The problem has been there for months but somehow only manifested itself now.  Unless something else breaks, the web site should finally update tonight.

**Comment by tatuylonen** [comment]
The update finally went through last night.  The issue looks fixed to me.

**Comment by ChristianSi** [comment]
Yeah, it's fixed now. Thanks again!

**Comment by ChristianSi** [comment]
I'm sorry, but I have to reopen this issue, because I've just noticed that various words still exhibit this behavior even in the latest dump. These include:

* wind (movement of air)
* desert (barren area)
* sould (the spirit or essence...)
* shark (fish)
* lead (chemical element)
* pen (writing tool)

**Comment by tatuylonen** [comment]
It seems that at least "desert" has the Translations subsection under "Related terms" in the section hierarchy, and the code is not handling this correctly.  As a result, the translations are being interpreted as related terms.  This needs to be fixed, but it looks like a different root cause.  (An alternative would be to fix these in Wiktionary, but I think I'd like to make the code work also in these cases.)

At least "shark" seems to be similar (Translations and several other sections are under Alternative forms).

"wind", however, seems to be something else and looks like duplicated translations.  I'll look into these, maybe tomorrow.

**Comment by tatuylonen** [comment]
I believe "lead" and "wind" are now fixed.  I implemented support for multiple Etymology sections on translation subpages.  Still working on the others.

**Comment by tatuylonen** [comment]
Looks like yesterday's fix caused a crash on about 50 pages, including e.g. "coffee".  Data is probably missing from those pages today.

**Comment by tatuylonen** [comment]
I've been thinking about how to fix the incorrect hierarchy issues (e.g., "desert").  There are hundreds if not thousands of such pages.  I'll probably solve it by fixing the subtitle hierarchy as a preprocessing step before parsing the page.  This will probably be only 50-200 lines of code and should be fairly robust.  Much easier to implement than changing the code to deal with the incorrect hierarchies.

I'll probably implement the change early next week; the next couple of days are too full of unrelated distractions.

**Comment by ChristianSi** [comment]
As far as I can tell, all the duplicated entries I've noticed are fixed in the latest dump.

However, various "good" definitions are missing as well, probably because of the crashes you mention, so this may be a preliminary state of affairs.

**Comment by tatuylonen** [comment]
I just committed a change that fixes up the subtitle hierarchy before parsing the page.  This seems to fix "desert", "shark", and "soul".  These fixes should be reflected on the website tomorrow.

Can you point out exactly what "good" definitions are missing (after the update tomorrow)?

**Comment by ChristianSi** [comment]
I can confirm that, as of the latest dump (date: 2021-06-18 14:36:45), all the duplicated entries I had noticed are fixed.

Missing "good" definitions include:

* acute (intense, sensitive, sharp)
* acute (urgent)
* age (generation)
* agenda (list of matters to be taken up)
* another (not the same; different)
* bit (small amount of something)

I notice that, except for "another", these entries all have a "See also translations at ..." note, so it's probably related to that and unrelated to the issue fixed here. In any case, it's a bug.

**Comment by tatuylonen** [comment]
What exactly is missing?  I couldn't find what was missing in "acute", "age", "agenda", "another" or "bit".  At least the translations for all senses seem to be present.  Note that in all of your examples the translations are under the sense.  Could it be that the "missing" definitions are the ones that have already been disambiguated and are under the sense?  (The current disambiguation code is very primitive and only disambiguates trivial cases, so many are left at the top level)

I noticed that antonyms were not correctly processed in word senses (e.g., the "Brief, quick, short" sense of "acute").  This has now been fixed.

The "see" and "See also translations" parts in translations are currently ignored.  I welcome ideas on how to best handle them (I don't think importing all translations from the referenced word would be appropriate).

**Comment by ChristianSi** [comment]
Yes, now I see the problem, and it may be on my side. Regarding "acute", some translations (96 altogether) are listed in a top-level "translations" object, while others are listed under the "senses" object. My parser expects them to be in one place OR the other, but not spread over both.

I will fix my code to look in both places and combine the results – I just hope that I won't get any duplicates in that manner. And admittedly I don't understand the logic behind this partial sense disambiguation – why do you consider "intense, sensitive, sharp" a sense, but not "(botany) having an acute angle"? On the Wiktionary page, both of these are listed in exactly the same manner, as far as I can see.

Ignoring the "See also translations" seems appropriate. Or possibly one could add a "see-also" field under the sense itself.

**Comment by ChristianSi** [comment]
I have fixed my code and were able to recover all the missing translations.
