### ISSUE TITLE
Categories "Animals" and "Insect" missing from "beetle"

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#577]
This might be related to #537, but I thought it's better to open a new ticket.

https://kaikki.org/dictionary/English/meaning/b/be/beetle.html

In an earlier version of the word "beetle", there was the category "Beetles" present, which still is on [the Wiktionary page](https://en.wiktionary.org/wiki/beetle). This category is used by us to map the word to "Insects", "Animals" etc. because "Beetles" is a subcategory of those.

A similar problem seems to exist here:

https://kaikki.org/dictionary/Italian/meaning/c/ca/cane.html

On [Wiktionary](), this is mapped to it:Animals, it:Canids, it:Chordates, it:Dogs, it:Vertebrates, but nothing of those categories is on kaikki.org

Thanks guys!

**Comment by xxyzz** [comment]
These category links are created from the "C" template at the end of a section, I suspect the template is not expanded.

**Comment by xxyzz** [comment]
Same bug and fixed by the linked pr, category will be added at the next kaikki.org update.

**Comment by yolpsoftware** [comment]
Some more examples if you want to check a few more:

https://en.wiktionary.org/wiki/basilisco (category `it:Reptiles`)
https://en.wiktionary.org/wiki/agnello (category `it:Sheep`)
https://en.wiktionary.org/wiki/branche (category `fr:Trees`)
https://en.wiktionary.org/wiki/dorada (cateogry `es:Fish`)

**Comment by xxyzz** [comment]
All fixed in the master branch, please wait for the kaikki.org update.

**Comment by xxyzz** [comment]
kaikki.org has updated and the missing category links should be restored.
