### ISSUE TITLE
Spanish extracts suddenly aren't outputting form_of

### ISSUE THREAD

**Issue by BrianSladek** [tatuylonen/wiktextract#58]
The extracts for many inflected words in Spanish used to output the lemma in the form_of field. Now, none of these extracts contain the form_of field at all. I believe these worked previously.

A few examples:
https://kaikki.org/dictionary/Spanish/meaning/a/ab/abro.json
https://kaikki.org/dictionary/Spanish/meaning/a/ab/abres.json
https://kaikki.org/dictionary/Spanish/meaning/f/fu/fue.json
https://kaikki.org/dictionary/Spanish/meaning/c/co/comes.json
https://kaikki.org/dictionary/Spanish/meaning/c/co/comen.json
https://kaikki.org/dictionary/Spanish/meaning/q/qu/quiero.json

Most verbs seem to have lost the form_of field. Adjectives seem to be working, but I haven't looked exhaustively. A few verbs do actually contain the lemma, for example: https://kaikki.org/dictionary/Spanish/meaning/c/co/come.json

**Comment by tatuylonen** [comment]
I made a change related to this a few days ago and at least all of these examples are now fixed.  (I'm aware of some other, probably unrelated form_of parsing issues that I need to look into this week)

**Comment by tatuylonen** [comment]
I just committed a fix for parsing the other form_of types that I was referring to in my previous reply.  https://kaikki.org should update by tomorrow (unless something goes wrong in the run).  Please let me know if you notice similar problems in the future.
