### ISSUE TITLE
Confusion of language and script

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#60]
Among the [translations](https://en.wiktionary.org/wiki/leaf#Translations) of the word "leaf" (sense: part of a plant), the Pali translation is listed in six different scripts: Burmese, Devanagari, Khmer, Latin, Sinhalese, Thai. One of these is correctly recognized as "lang": "Pali", with "Devanagari" among the "tags". The other five, however, are mislabeled as translations into Burmese, Khmer, Latin, Sinhalese, and Thai *language*. It may not be easy to recognize, but in such cases of nested translations these labels should be considered scripts, not languages.

I don't know if this only concerns Pali or also other languages, but I suppose that "leaf" is not the only word with this issue.

**Comment by tatuylonen** [comment]
I just fixed this one.  I basically implemented a list of names that are always interpreted as script names (and put into tags)
when used on the second level in nested translations.  The fix should be reflected on the web site tomorrow.

Please let me know if you encounter additional script names that should be added (it currently contains the script names from the "leaf" translations).

**Comment by ChristianSi** [comment]
Yeah, this is fixed now, thanks!

Francly I don't think I would notice if there are other script+language names with the same issue – but should I happen to notice any, I would let you know.
