### ISSUE TITLE
Confusing "no deprecated lang param usage" in etymology templates?

### ISSUE THREAD

**Issue by digitalheir** [tatuylonen/wiktextract#619]
Wiktionary entry for [scouse](https://en.wiktionary.org/wiki/scouse):
```
{{clipping of|en|lobscouse|dot=,}} of uncertain origin.
```

Kaikki output:
```
  "etymology_templates": [
    {
      "args": {
        "1": "Clipping of <span class='form-of-definition-link'><i class=\"Latn mention\" lang=\"en\">lobscouse</i></span>,",
        "lang": ""
      },
      "expansion": "Clipping of lobscouse,",
      "name": "no deprecated lang param usage"
    },
    {
      "args": {
        "1": "en",
        "2": "lobscouse",
        "dot": ","
      },
      "expansion": "Clipping of lobscouse,",
      "name": "clipping of"
    }
  ],
```
Why does the former exist? "no deprecated lang param usage"? Seems like an internal Wiktionary warning, not very useful to end users I'd say!

**Comment by xxyzz** [comment]
Template "clipping of" uses the "no deprecated lang param usage" template, the "etymology_templates" field contains all used templates, please see https://github.com/tatuylonen/wiktextract/issues/611#issuecomment-2095034784

**Comment by xxyzz** [comment]
A work around was committed in https://github.com/tatuylonen/wiktextract/commit/c46cdd8b6289aef5cb55a4c141c02dfa9747ae9a

**Comment by xxyzz** [comment]
Probably fine. `ADDITIONAL_EXPAND_TEMPLATES` pre-expands the template and `ignored_etymology_templates` removes the template from "etymology_templates" list.

**Comment by xxyzz** [comment]
Fixed on kaikki.org
