### ISSUE TITLE
part-of-speech question

### ISSUE THREAD

**Issue by danialjivraj** [tatuylonen/wiktextract#638]
Hello, I have a question regarding part-of-speech.

Some words can have more than one part of speech.
I wanted to ask if this tool can retrieve all parts of speech from a single word, for example the word "a" is a preposition, but also a noun, etc...

I have downloaded the JSON file online but it seems to only have one pos for every word.
I was wondering if there is a way or a specific command that can make it scrape all parts of speech for a single word.

I'm new with this tool so apologies if this comes as an obvious question.

**Comment by xxyzz** [comment]
All POS sections are extracted but one JSON object only has one POS. Different POS data are in different JSON objects i.e. one POS per line in the JSONL format file.
