### ISSUE TITLE
20240520 wiktionary dump files are currently broken

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#643]
https://phabricator.wikimedia.org/T365501

I'll try to change to use the 20240501 dump file on kaikki currently.

Might take a while (I don't really have good access). Worst case I'll poke Tatu.

**Comment by kristian-clausal** [comment]
It actually worked out fine (the issue was with the broken files that disk space ran out because of the huge log files, I believe). We'll truck along with the old dump files until the issue is fixed on the Wikimedia side of things.

**Comment by xxyzz** [comment]
Upstream bug fixed and kaikki.org is using 20240601 dump files, close as resolved.
