### ISSUE TITLE
Missing genitives in Danish

### ISSUE THREAD

**Issue by mtruyens** [tatuylonen/wiktextract#66]
(First of all: I absolutely really love your work!)

I happened to notice that certain genitives are missing in Danish, and it is not exactly clear to me why.

See for example "motorsav" (e.g., the genitive indefinite singular "motorsavs"), which does seem to be included on Wiktionary https://en.wiktionary.org/wiki/motorsav#Danish

**Comment by mtruyens** [comment]
I also noticed that some Danish adjective conjugations seem to be missing. For example, while adjective "bitter" is listed, inflected versions such as "bittert" and "bitre" are missing, even though Wiktionary's declension table does list them (https://en.wiktionary.org/wiki/bitter#Danish).

**Comment by tatuylonen** [comment]
The "forms" part of the word only contains information extracted from the word head, i.e., the line after "Noun" in this case.
It doesn't currently parse the Declension and Conjugation tables, but that is on my TODO list.  It will probably be a few weeks before I get there.  (The template & arguments used to generate the declension/conjugation tables should already be captured under "head"; they are useful for some applications.)

**Comment by mtruyens** [comment]
Thanks for the reply! 

I'm indeed already using some parts under "head"; in fact, with the current amount of information I could find everything I required for nouns/adjectives/verbs in Swedish and Norwegian — which is why it was so surprising that Danish missed some information...

The work you already did is amazing. I'm looking forward to the additions you are describing!

**Comment by tatuylonen** [comment]
I'm currently working on parsing the inflection tables but it will take at least several days, possibly weeks.  I especially love Swahili inflection tables, e.g.: https://en.wiktionary.org/wiki/udhi.  I never fully realized so many languages have so many inflections and that they could be described in so many different ways!

**Comment by mtruyens** [comment]
And knowing that a Finnish native (with its 17 or so cases) makes this comment, says a lot!

**Comment by tatuylonen** [comment]
I've now added the initial version of the code that parses conjugation and declension tables.  I just checked, and at least for motorsav the data (including genitive) seems to be there.  Same for bitter.  I haven't yet done extensive testing, but inflection tables for most major European languages should be properly extracted (I think Spanish still had some issues).  Many other languages work too, but I've not tested them.  There are also still many languages with more complex tables that need additional work.

It will help if you can do some checking on Danish inflections to make sure they are correct/reasonable.  Any suggestions for improvement are welcome.

**Comment by mtruyens** [comment]
Many thanks already. I will indeed do some checking in the next days, and let you know!

**Comment by tatuylonen** [comment]
Danish inflection table extraction should now work.  I've added tests for noun, verb, and adjective tables.  The examples you provided (motorsav, bitter) look correct.  (I'm not sure if data on kaikki.org is yet up to date on these, but should be after next update, probably by Monday).

Closing this issue as resolved.
