### ISSUE TITLE
Add Simple English Wiktionary

### ISSUE THREAD

**Issue by emanuelps2708** [tatuylonen/wiktextract#668]
Hi, I think it would be great to add Simple English Wiktionary, I noticed that there's a pr about adding it but it appears that it got forgotten.

**Comment by xxyzz** [comment]
That pr was created a long time ago and has conflicts. Besides, the dump file is only 7M, we tend to add larger editions.

**Comment by kristian-clausal** [comment]
On the flip-side, if the dump file is small that also means that the data is more manageable. If anyone is willing to take on the project, it will of course be welcomed.

**Comment by mark-leppa** [comment]
Simple Wiktionary is a smaller (49K words) but much more useful and practical dictionary for many projects. The current "complex" English extract weighs in at a hefty 2.2 GB and many of the terms are too obscure to be useful.

**Comment by kristian-clausal** [comment]
I am currently working on this, **but very slowly**. It will also double as a way to create a kind of documented tutorial for others who might want to make extractors in the future; my aim is to use a lot of comments and to write how-to-do stuff. Simple English Wiktionary is very small, and its entry layout is pretty simple and consistent, so it's a good example without getting as bogged in as you would with a larger edition.

**Comment by kristian-clausal** [comment]
I've added Simple English to kaikki's smaller editions, but it is definitely not perfect.

**Comment by emanuelps2708** [comment]
Thank you so much for adding it ;)
