### ISSUE TITLE
Spurious question mark at the end of translations

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#67]
Two days ago a question mark, preceded by a space, has started to appear at the end of various translations in the English dump. Examples include:

abstract  
hi: सारांश, निचोड ?  
mr: सारांश ?, गोषवारा ?

acetate  
fr: acétate ?  
hi: शुक्त ?

aluminium  
hi: एल्युमिनियम ?, स्फटयातु ?  
mr: ऍल्युमिनियम ?

anthropology  
gu: નૃવંશશાસ્ત્ર ?  

Argentina  
gu: આર્જંટિના ?  
mr: अर्जेन्टीना ?  
ur: ارجنٹائن‎ ?, ارجینٹینا‎ ?

aubergine  
hi: बैंगनी ?  
ru: тёмнофиолетовый ?, баклажа́новый ?  
ur: بینگنی‎ ?

Brindisi  
es: Bríndisi ?  
fr: Brindisi ?

bumblebee  
gu: બબલબી ?  
mr: भोंवर ?, भृंग ?, भ्रमर ?

conspiracy  
mr: कट ?

exile  
ar: نَفْي‎ ?  
hi: निर्वासन ?

The question mark is indeed shown in Wiktionary with a mouseover that says "gender incomplete". I suppose this is new, at least I cannot remember having seen it before.

It would be good to ignore it when extracting the translations – though it may be a bit tricky to distinguish these cases from the cases where the translation themselves ends with a question mark.

**Comment by tatuylonen** [comment]
I just fixed this.  I had introduced a bug a few days ago that stripped "?" from the form indicators to be handled, when I was supposed to only strip it from the tags to be added (I use it to indicate that the combination of form indicators is suspicious and that a warning should be issued).  Let me know if it persists in the next dump.

**Comment by tatuylonen** [comment]
The update failed last night... I had forgotten an "assert False" from latest debugging and hadn't run tests before going home...  Hopefully in five hours from now the site will update.

**Comment by tatuylonen** [comment]
I'm having trouble getting the extraction to run successfully.  I seem to have introduced a bug that causes some pages to process really slowly or possibly hang completely.  I just haven't been able to identify any such word yet and thus haven't been able to debug the problem so far.

**Comment by ChristianSi** [comment]
All the spurious question marks are gone again. Or most of them anyway. Very good!
