### ISSUE TITLE
zh-form template missing in extract for Chinese words

### ISSUE THREAD

**Issue by jiong3** [tatuylonen/wiktextract#676]
The form template seems to be missing from the Chinese entries, e.g. https://en.wiktionary.org/wiki/%E6%A9%9F%E8%BB%8A would have the following zh-form template:
{{zh-forms|s=机车}}
; “motorcycle”
: {{zh-etym-short|機器腳踏車}}.

I would like to use this information to know the simplified version (s=) of the word, if there is one.

**Comment by xxyzz** [comment]
This is fixed on kaikki.org, close as resolved.

**Comment by jiong3** [comment]
Great, thank you!
