### ISSUE TITLE
Are there any quotations included in the dataset?

### ISSUE THREAD

**Issue by KawaiiNotHawaii** [tatuylonen/wiktextract#69]
wiktionary has several quotations per meanings, do they also get extracted?

**Comment by tatuylonen** [comment]
The usage examples are not currently extracted but extracting them is on my todo list (I don't expect it to be very difficult).

**Comment by tatuylonen** [comment]
I made some improvements to usage example extraction in the last couple of days.  They are now cleaned better, the source ("ref" field in the extraction) is now identified more reliably, and I also added an "english" field for English translations that are present in many non-English usage examples.  This way the "text" field is now a cleaner usage example in the relevant language.
