### ISSUE TITLE
Related work: dbnary and wikiparse

### ISSUE THREAD

**Issue by frankier** [tatuylonen/wiktextract#7]
Hi. This looks like a great tool. You say that this is the most extensive Wiktionary extractor. I believe this is the case, but for comparison I'd like to draw your attention to Dbnary http://kaiko.getalp.org/about-dbnary/ which may be competitive, as well as my own tool, https://github.com/frankier/wikiparse which is much for limited.

**Comment by tatuylonen** [comment]
Thanks, I've added a section in the README that refers to these.
