### ISSUE TITLE
Some wrong base forms in German (contain translation)

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#70]
This is caused by pages of this sort: 
https://en.wiktionary.org/wiki/Jahre
https://en.wiktionary.org/wiki/Wurzeln
After the base word, they have the translation in quotes, which causes the form_of entry to be incorrect (like Jahr "years" instead of simply Jahr).

**Comment by tatuylonen** [comment]
I just fixed this and tested on these two words.  The change should be reflected on https://kaikki.org tomorrow.
