### ISSUE TITLE
Senses containing the words "form of" are often incorrectly outputted with the form_of field.

### ISSUE THREAD

**Issue by BrianSladek** [tatuylonen/wiktextract#72]
If a sense contains "form of" anywhere in the text (even if the wikitext does not contain the "form of" template), the form_of field is populated.

For example, the word "larva" contains a definition that reads "A form of a recently born or hatched animal that is quite different from its adult stage." This results in wiktextract incorrectly identifying the definition as a lemma in the output:
form_of": [{"word": "a recently born or hatched animal that is quite different from its adult stage"}].

The same is true for the word "her" which contains a definition that reads "The form of she used after a preposition or as the object of a verb; that woman, that ship, etc.". The "lemma" of "her" is given as: "form_of": [{"word": "she used after a preposition or as the object of a verb", "extra": "that woman, that ship, etc"}]. 

There are several thousand cases of this error in the English extract on which I'm testing.

**Comment by BrianSladek** [comment]
After more thorough testing, it's not only "form of" that's causing this issue. It looks like the presence of the label of any wikitext template (class of, diminutive of, person of, etc.) will cause a lemma to be incorrectly assigned.

For example, the gloss of "sake" is "A class of Japanese rice wines made from polished rice and typically about 20% alcohol by volume." and the form_of returned from wiktextract is "Japanese rice wines made from polished rice and typically about 20% alcohol by volume".

**Comment by tatuylonen** [comment]
I recently noticed this too.  Basically anything that can be interpreted as "tags" followed by "of" will cause this (and it ignores a/an/the in the beginning), and it is clearly incorrect.  I'll try to fix it next week (probably by separately listing those tags that are allowed in this kind of alt_of/form_of interpretation, and probably disallowing the a/an/the skipping).

**Comment by tatuylonen** [comment]
The second issue (e.g. "the female given name Jacqueline or Jacquelyn") is trickier.  I'll see if I can do something about it.  Perhaps I could extract all alt_of/form_of values longer than say two words and that aren't defined as words in the dictionary, and see if it is a relatively small number of patterns that could be handled separately.
