### ISSUE TITLE
Missing tags for German 'Butter'

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#732]
![image](https://github.com/user-attachments/assets/38c6fc58-a955-4725-a0a2-dcbc94369c4c)
![image](https://github.com/user-attachments/assets/5abf083a-6142-48cc-8e6d-96e08510308d)
![image](https://github.com/user-attachments/assets/b4ea0bac-eb3c-4961-a347-9174d4ac2544)

(downstream: https://github.com/themoeway/kaikki-to-yomitan/issues/116#issuecomment-2241390914)

**Comment by xxyzz** [comment]
Please use texts and links in future issues.
