### ISSUE TITLE
A few entries missing

### ISSUE THREAD

**Issue by GrimPixel** [tatuylonen/wiktextract#743]
In Korean and Vietnamese files, `"word": "事"` is not found, while they are not empty in the [Wiktionary entry](https://en.wiktionary.org/wiki/%E4%BA%8B).

**Comment by xxyzz** [comment]
That page puts the "rel-bottom" template at a wrong place and expands broken HTML with an unclosed "div" tag, should be fixed in next month's dump file.

**Comment by xxyzz** [comment]
Fixed on kaikki.org
