### ISSUE TITLE
`colloquial` tag missing for German form `frägst`

### ISSUE THREAD

**Issue by not-my-profile** [tatuylonen/wiktextract#745]
https://en.wiktionary.org/wiki/fragen#Conjugation

Note the colloquial footnote after `frägst`:

![image](https://github.com/user-attachments/assets/4b982431-4205-489d-9817-c242e6e267ea)

However the extracted JSON doesn't contain the `colloquial` tag:

```json
    {
      "form": "fragst",
      "source": "conjugation",
      "tags": [
        "indicative",
        "present",
        "second-person",
        "singular"
      ]
    },
    {
      "form": "frägst",
      "source": "conjugation",
      "tags": [
        "indicative",
        "present",
        "second-person",
        "singular"
      ]
    },
```

https://kaikki.org/dictionary/German/meaning/f/fr/fragen.html

**Comment by xxyzz** [comment]
I tried to edit the "inflection.py" file but don't know where to change to save the data extracted from these `sup` HTML tags. @kristian-clausal please take a look.

**Comment by kristian-clausal** [comment]
I'm back from vacation, so I'll take a look at this.
