### ISSUE TITLE
German prepositions' canonical form contains '[with dative]'

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#760]
German prepositions `von`, `mit`, `an` etc. have the extra info `[with dative]` in their canonical forms. Similar to #667.

Example, `von`: https://kaikki.org/dictionary/German/meaning/v/vo/von.html

**Comment by kristian-clausal** [comment]
`Template:+obj` was replaced last month with a new module on the wiktionary side, which pulled the rug from under the old regex. I'll try to figure out if we can see what the output can look like and update the regex.

**Comment by kristian-clausal** [comment]
Yeah, we closed #667 on Jun 26, and the template+module was changed on Jun 30th, which also broke all the Czech stuff in #667 again. But, if we the output is consistent (hopefully), this should be an easy change. It just seems to add some HTML elements and... What is `<templatestyles>`..?

**Comment by kristian-clausal** [comment]
Should be fixed, at least partially for the stuff we've seen, with #762. This will only catch the new `[with ... = ....]` format (without the plus `+` that used to be there), but there might be more complex forms of the output out there. However, until those pop up, I'm not going to pre-emptively fix it with this commit, this fix is just to get back to status quo ante buggum. Now to fix the tests.
