### ISSUE TITLE
ImportError: cannot import name 'MAGIC_FIRST' from 'wikitextprocessor'

### ISSUE THREAD

**Issue by crashangelbr** [tatuylonen/wiktextract#77]
Whats this error?

**Comment by tatuylonen** [comment]
Which version of wiktextract and wikitextprocessor and how did you install them?  Which file is triggering this error?

The error suggests that your wiktextract and wikitextprocessor versions are incompatible (perhaps you have a too old version of wikitextprocessor - the master branch of wiktextract expects the master branch version of wikitextprocessor too).

Currently the versions in pypi are a bit dated, so I would recommend installing directly from https://github.com/tatuylonen/wikitextprocessor and https://github.com/wiktextract.  However as far as I know the versions in pypi should also work assuming you have both packages at the latest version.

**Comment by checkup21** [comment]
Installed both versions from git. Issue is still there.

**Comment by tatuylonen** [comment]
I just published new versions of both wiktextract and wikitextprocessor on pypi.  I'm currently testing them on a fresh virtual machine and wiktwords seems to work (at least I don't get the error you got).  For this test I installed the new versions from pypi with pip3.
