### ISSUE TITLE
Some of the most common Korean words are missing from kaikki

### ISSUE THREAD

**Issue by joshuawu** [tatuylonen/wiktextract#790]
Some of the most common Korean words are missing from [the Korean JSONL on kaikki.org](https://kaikki.org/dictionary/Korean/kaikki.org-dictionary-Korean.jsonl), including the most common Korean word [것](https://en.wiktionary.org/wiki/것).
They all have entries on English Wiktionary for the verbatim word form.

1. [것](https://en.wiktionary.org/wiki/것)
2. [때문](https://en.wiktionary.org/wiki/때문)
3. [데](https://en.wiktionary.org/wiki/데)
4. [뿐](https://en.wiktionary.org/wiki/뿐)
5. [듯](https://en.wiktionary.org/wiki/듯)
6. [만큼](https://en.wiktionary.org/wiki/만큼)
7. [번째](https://en.wiktionary.org/wiki/번째)
8. [듯이](https://en.wiktionary.org/wiki/듯이)
9. [나름](https://en.wiktionary.org/wiki/나름)
10. [대비](https://en.wiktionary.org/wiki/대비)
11. [고속도로](https://en.wiktionary.org/wiki/고속도로)

**Comment by kristian-clausal** [comment]
At first I thought it was because those entries have a POS heading "Dependent noun", but seems it's something else. I'll take a look.

**Comment by kristian-clausal** [comment]
[대비](https://en.wiktionary.org/wiki/%EB%8C%80%EB%B9%84) is for the language "Jeju", and the gloss is "socks".

**Comment by kristian-clausal** [comment]
Nevermind, it was "Dependent noun", I just had to add it to *two* different dicts that seems identical... Need to clean these up.

**Comment by joshuawu** [comment]
(the below is just an observation)

> [대비](https://en.wiktionary.org/wiki/%EB%8C%80%EB%B9%84) is for the language "Jeju", and the gloss is "socks".

My bad, although it *is* a very common Korean word used as [sense #4 in the Korean Wiktionary](https://ko.wiktionary.org/wiki/%EB%8C%80%EB%B9%84). The English Wiktionary only lists sense no. 2 which is Jeju dialect and of Japanese etymology.
