### ISSUE TITLE
split glosses of Spanish entries in enwiktionary extraction

### ISSUE THREAD

**Issue by jhammen** [tatuylonen/wiktextract#795]
Hello,

I'm working with Spanish entries in the enwiktionary extraction, I see many verb senses split into two glosses.

As an example, the page "[sabe](https://en.wiktionary.org/wiki/sabe#Spanish)", the two verb senses each yield [two separate glosses](https://kaikki.org/dictionary/Spanish/meaning/s/sa/sabe.html):

```
      "glosses": [
        "inflection of saber:",
        "third-person singular present indicative"
      ],
...

      "glosses": [
        "inflection of saber:",
        "second-person singular imperative"
      ],
```
I thank you in advance for your thoughts on this.

**Comment by xxyzz** [comment]
Nested gloss lists on Wiktionary are extracted in this format.

**Comment by kristian-clausal** [comment]
Yes, this is intended behavior; the different entries in "glosses", in this case, represent the hierarchy. Because the entry looked like:

```
# inflection of saber:
## third-person singular present indicative
## second-person singular imperative
```

it's simple to just reuse the first line for each subgloss.

**Comment by jhammen** [comment]
I agree the entry represents two different senses and I see what you're saying about sharing the top level.

It does mean that glosses may need to be combined for some applications but this does not seem difficult.

I thank you for the information and thank you also for your work on this great resource.

**Comment by jhammen** [comment]
After further work, I have to reopen this for reconsideration.

In the above text there are indeed two senses, but there are only two glosses, one for each sense. There are not four glosses here.

Also I notice now the "form_of" field is not being filled in this case.

My suggestion is to prepend the heading to the actual glosses (and also include the correct "form_of" field):

```
"glosses": ["inflection of saber: third-person singular present indicative"],
...
form_of": [{ "word": "saber" }

"glosses": ["inflection of saber: second-person singular imperative"],
...
form_of": [{ "word": "saber" }]
```
      
I understand this is not easy due to the hierarchy in the source but right now information about this hierarchy is *lost* when it is flattened in this way. This is not good. Creating extra "glosses" out of the headers is simply not helpful downstream.

You are pushing this problem to the end user where the information that is lost must be restored via ugly and expensive post-processing.

I understand it's likely easier to parse things this way but it is simply not useful. Note it is not consistent with verb forms that only have a single sense, e.g.:

```
"word" : "supe",
...
"glosses": ["first-person singular preterite indicative of saber"],
...
"form_of": [{"word": "saber"} ]
```

I hope you will please reconsider fixing this, or at least leaving this issue open for others who run into this problem and those who may be willing to fix it.

**Comment by jhammen** [comment]
In case this is helpful for others, here is a basic script that makes the changes mentioned above: it combines the glosses and adds "form_of" to the given file and creates a new file with the changes.

```
import json
import re
import sys

infile = sys.argv[1]
outfile = infile + ".esverbfix.jsonl"


def wict_jsonl():
    with open(infile, 'r') as f:
        for line in f:
            yield json.loads(line.strip())


with open(outfile, 'w', encoding='utf-8') as outfile:
    for item in wict_jsonl():
        for sense in item['senses']:
            if 'glosses' in sense: 
                base = None
                prepend = None
                new_glosses = []
                for gloss in sense['glosses']:
                    match = re.search('inflection of ([a-z]+):', gloss)                
                    if match:
                        prepend = gloss
                        base = match.group(1)
                    elif prepend:
                        new_glosses.append(prepend + " " + gloss)
                        prepend = None
                if len(new_glosses):
                    sense['glosses'] = new_glosses
                    sense['form_of'] = [{ "word": base }]
        json.dump(item, outfile, ensure_ascii=False)
        outfile.write("\n")
        
print("done.")
```

This solves the issue for me but I still hope you will consider doing something like this for the original dumps..

**Comment by kristian-clausal** [comment]
I don't know what you're asking for here. The `glosses` field is hierarchical data. It's a list of strings, starting from the top level and following a path to the lowest node, breadcrumbing each level (usually only one, sometimes two, there are some with three). The `glosses` field is effectively one gloss that you can always join together with something simple like `" ".join(data.glosses)` is needed.

Each sense has only one `glosses` field, and its named that because it is a list. We want to keep fields that are lists in the plural; if it was only one string, it would be `gloss`.

**Comment by kristian-clausal** [comment]
As for the missing `form_of` field, that's because of the structure of these entries. We need to make a new kludge to handle that.

**Comment by kristian-clausal** [comment]
PR #873 should add `form_of` fields more consistently to sense entries under `senses` now. This part of the code is already very tricky to navigate, and adding the `form_of` senses to specific senses makes sense if you have a situation where someone's made an entry combining polysemous stuff under the same umbrella, say having the 'natural' unstratified inflection entry next to a meaning of the word that has gathered some specific meaning.

**Comment by jhammen** [comment]
Thank you for the information and the fix, this should solve my problem.

In particular I was indeed not understanding the meaning of multiple glosses, I was processing them as a list. I see they are meant to represent hierarchy so indeed no information is actually lost. I was wrong to say this above.

This means all I really needed was the form_of fix, which I will test on the next export.

I apologize for the confusion, working with this "semi-structured" data is often frustrating, the data you provide is actually a big part of the solution so I thank you again for providing this work!

**Comment by jhammen** [comment]
the "form_of" fix works great, thank you!
