### ISSUE TITLE
Regex error in clean_value() function

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wiktextract#799]
I think there is a typo in the `clean_value` function, [Change <sub> ... </sub> to _](https://github.com/tatuylonen/wiktextract/blob/master/src/wiktextract/clean.py#L1496) (line: 1496)

```python
    # Change <sub> ... </sub> to _
    title = re.sub(r"(?si)<sub\b[^>]*>\s*</sup\s*>", "", title)
```
it should be
```python
    # Change <sub> ... </sub> to _
    title = re.sub(r"(?si)<sub\b[^>]*>\s*</sub\s*>", "", title)
```

**Comment by kristian-clausal** [comment]
Good catch!

**Comment by kristian-clausal** [comment]
Committed a correction, should be correct now.
