### ISSUE TITLE
wrong pronounciation parsing for enwiktionary

### ISSUE THREAD

**Issue by maria-terekhina** [tatuylonen/wiktextract#8]
For some one-word entries, wiktwords provides wrong pronunciation information: in the 'ipa' key there is a language code instead of the transcription and the place of the language code is empty.

Some examples:

{'word': 'covfefe', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'heads': [{'1': '~', 'template_name': 'en-noun'}], 'senses': [{'glosses': ['A word used in a tweet by Donald Trump, the meaning of which (probably "coverage") was subject to speculation.'], 'nonglosses': ['A word used in a tweet by Donald Trump, the meaning of which (probably "coverage") was subject to speculation.'], 'wikipedia': ['Donald Trump']}, {'glosses': ['Coffee.'], 'tags': ['mostly', 'uncountable', 'humorous', 'informal']}], 'pos': 'noun'}
{'word': 'peninitial', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'heads': [{'1': '-', 'template_name': 'en-adj'}], 'senses': [{'glosses': ['Falling in the position after initial position; second.'], 'tags': ['linguistics', 'chiefly']}], 'pos': 'adj'}
{'word': 'breenge', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'heads': [{'template_name': 'en-noun'}], 'senses': [{'glosses': ['A plunge, a violent movement.'], 'tags': ['Scotland']}], 'pos': 'noun'}
{'word': 'breenge', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'heads': [{'1': 'breeng', 'pres_ptc2': 'breengeing', 'template_name': 'en-verb'}], 'senses': [{'glosses': ['To lunge forward, to dash ahead, to move recklessly.'], 'tags': ['Scotland', 'intransitive']}], 'pos': 'verb'}
{'word': 'Taz', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'senses': [{'glosses': ['A nickname for someone very active, ferocious or with a great appetite.']}], 'pos': 'name'}
{'word': 'Portakabin', 'lang': 'English', 'pronunciations': [{'accent': ['UK'], 'ipa': [['', 'en']]}], 'heads': [{'template_name': 'en-noun'}], 'senses': [{'glosses': ['A type of mobile building.']}], 'isbn': ['9780852929414', '9780330463034', '9780748118403'], 'pos': 'noun'}
{'word': 'mouthbreeder', 'lang': 'English', 'pronunciations': [{'accent': ['RP'], 'ipa': [['', 'en']]}, {'accent': ['GA'], 'ipa': [['', 'en']]}], 'hyphenation': [['en', 'mouth', 'breed', 'er']], 'heads': [{'template_name': 'en-noun'}], 'senses': [{'glosses': ['synonym of en'], 'tags': ['zoology'], 'alt_of': ['en']}], 'categories': ['English words suffixed with -er (agent noun)'], 'pos': 'noun'}
{'word': 'mouthbreeder', 'lang': 'English', 'pronunciations': [{'accent': ['RP'], 'ipa': [['', 'en']]}, {'accent': ['GA'], 'ipa': [['', 'en']]}], 'hyphenation': [['en', 'mouth', 'breed', 'er']], 'heads': [{'template_name': 'en-noun'}], 'senses': [{'glosses': ['synonym of en'], 'tags': ['zoology'], 'alt_of': ['en']}], 'categories': ['English words suffixed with -er (agent noun)'], 'pos': 'noun'}
{'word': 'Boudica', 'lang': 'English', 'pronunciations': [{'ipa': [['', 'en']]}], 'senses': [{'glosses': ['A queen of the British Iceni tribe that led an uprising against the occupying forces of the Roman Empire, died c. CE 61.']}], 'isbn': ['9781446445013'], 'pos': 'name'}

**Comment by tatuylonen** [comment]
Thanks, turns out IPA parsing was completely broken in this version. I've now committed a version that should fix this.  Sorry about the long delays in looking into this.
