### ISSUE TITLE
Error trying to download simple english wiktionary data

### ISSUE THREAD

**Issue by emanuelps2708** [tatuylonen/wiktextract#855]
Hi, sorry if this is not the right place to report this but I recently noticed that you added the Simple English wiktionary edition, however I get en error when I try to access at https://kaikki.org/simplewiktionary/
![image](https://github.com/user-attachments/assets/33921929-5c5c-4ba6-8a1c-9dbd62961046)

**Comment by xxyzz** [comment]
Simple Wiktionary is not added to kaikki.org server yet, you could run the latest code to extract the dump file locally.

**Comment by kristian-clausal** [comment]
The first run of SEW seems to have gone wrong and failed, but the regeneration script assumes that if there is a failure there is still an old run left... But why do the logs not mention it failing, why doesn't it appear at all??? I mean, if the link was added (by me), why doesn't the other stuff work... I'll take a look.

**Comment by kristian-clausal** [comment]
I missed *ONE* place. Should work out now.

**Comment by kristian-clausal** [comment]
Simple English Wiktionary is now finally available! Please take a look at https://kaikki.org/simplewiktionary/
