### ISSUE TITLE
Missing German "bis"

### ISSUE THREAD

**Issue by Alex-Programs** [tatuylonen/wiktextract#869]
Lowercase bis (https://en.wiktionary.org/wiki/bis#German) is a common word in German, yet the Wiktionary dataset only contains https://en.wiktionary.org/wiki/Bis#German .

`rg '"word": "Bis"' raw-wiktextract-data.jsonl | rg '"lang": "German"' > to_look_at.jsonl`

```
{"senses": [{"links": [["music", "music"], ["B-sharp", "B-sharp"]], "categories": ["German entries with incorrect language header", "German lemmas", "German neuter nouns", "German nouns", "Pages with 2 entries", "de:Music"], "raw_glosses": ["(music) B-sharp"], "topics": ["entertainment", "lifestyle", "music"], "glosses": ["B-sharp"], "tags": ["neuter", "strong"]}], "pos": "noun", "head_templates": [{"name": "de-noun", "args": {"1": "n,-,-"}, "expansion": "Bis n (strong, genitive Bis, plural Bis)"}], "forms": [{"form": "Bis", "tags": ["genitive"]}, {"form": "Bis", "tags": ["plural"]}, {"form": "strong", "source": "declension", "tags": ["table-tags"]}, {"form": "de-ndecl", "source": "declension", "tags": ["inflection-template"]}, {"form": "Bis", "tags": ["nominative", "singular"], "source": "declension"}, {"form": "Bis", "tags": ["definite", "nominative", "plural"], "source": "declension"}, {"form": "Bis", "tags": ["genitive", "singular"], "source": "declension"}, {"form": "Bis", "tags": ["definite", "genitive", "plural"], "source": "declension"}, {"form": "Bis", "tags": ["dative", "singular"], "source": "declension"}, {"form": "Bis", "tags": ["dative", "definite", "plural"], "source": "declension"}, {"form": "Bis", "tags": ["accusative", "singular"], "source": "declension"}, {"form": "Bis", "tags": ["accusative", "definite", "plural"], "source": "declension"}], "inflection_templates": [{"name": "de-ndecl", "args": {"1": "n,-,-"}}], "word": "Bis", "lang": "German", "lang_code": "de", "categories": ["Pages with 2 entries"]}
```

`rg '"word": "bis"' raw-wiktextract-data.jsonl | rg '"lang": "German"' > to_look_at.jsonl`

Gets quite a few results - I've attached the file. It includes:
- Biß, an archaic form
- "Encore", with some translations to bis in various languages.
- The same with "Adobe"
- "Until" and "Till", this time recognising that it's the German translation.
- Various more false positives

Nowhere, however, is an entry for the German term "bis" - only the uppercase variant, which means something completely different.

I can't quite recall what variant I'm using. I think it's https://kaikki.org/dictionary/All%20languages%20combined/words/kaikki.org-dictionary-all-words.jsonl, and I do have the hash:
```
[alex@alexpc nuenki-dictionary]$ sha256sum raw-wiktextract-data.jsonl 
67bae507fd84ca75bf2f6743801b9ff3df4ca97862034ae2ee47e25703b757f2  raw-wiktextract-data.jsonl
```

I'm currently redownloading to check.

I've also tested this using my processing program, and it concurs - there is a word for "Bis", but not "bis". But I did most of the checking via ripgrep incase the problem is with my program.

Perhaps I'm interpreting the data wrong? Should I be taking the obsolete form and extracting data about bis from it?

[to_look_at.txt](https://github.com/user-attachments/files/17367246/to_look_at.txt)

Edit: I believe I am using https://kaikki.org/dictionary/raw-wiktextract-data.jsonl from https://kaikki.org/dictionary/rawdata.html .

**Comment by xxyzz** [comment]
There is a wrong `references` tag at the end of "Cimbrian" language section which breaks the rest wikitext, fixed on Wiktionary, should be included in the next dump file.

**Comment by Alex-Programs** [comment]
Thanks!
