### ISSUE TITLE
Incorrect canonical forms for some Russian words

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#88]
Some words, for example 
https://en.wiktionary.org/wiki/%D0%B2%D0%B8%D1%81%D0%BA%D0%B8 or
https://en.wiktionary.org/wiki/%D0%B2%D0%B5%D0%BD%D0%B0
contain an incorrect canonical form. In addition to the word, a string like "n inan or" is being appended.

PS: This project is very helpful. 👍

**Comment by Vuizur** [comment]
I also noticed that in some rare cases strings like "n inan f" are recognized as their own form, like in the case of https://en.wiktionary.org/wiki/%D0%BF%D0%BE%D0%B3%D0%B0%D0%BD%D0%BA%D0%B8

**Comment by tatuylonen** [comment]
I just fixed these cases.  Thanks for pointing them out.  Please let me know if you find any other similar ones.

**Comment by tatuylonen** [comment]
The fixes should be visible on https://kaikki.org tomorrow, unless something goes wrong with my overnight update run.
