### ISSUE TITLE
Some examples missing in Spanish edition

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#880]
The page for en-es 'read' (https://es.wiktionary.org/wiki/read) has examples for senses 1, 4, 6, and 7. But the processed JSON (https://kaikki.org/eswiktionary/Ingl%C3%A9s/meaning/r/re/read.html) has an example only for sense 1.

**Comment by kristian-clausal** [comment]
The Spanish edition of Wiktionary uses `; ... :` style wikitext definitions for sense and glosses, and it also seems to mix how new lines of definitions work... It's a bit tricky, so I'm not going to touch it, but xxyzz should be able to take a look when he's less busy with other things.
