### ISSUE TITLE
Images in glosses

### ISSUE THREAD

**Issue by rbozan** [tatuylonen/wiktextract#902]
https://en.m.wiktionary.org/wiki/spout#English

There's an image rendered here which shows what a spout is. If you look at Kaikki this image is directly copied over to the gloss: https://kaikki.org/dictionary/All%20languages%20combined/meaning/s/sp/spout.html

Is this the correct place this image should be in or is there perhaps a different designated field for this image ?

**Comment by xxyzz** [comment]
regex at here https://github.com/tatuylonen/wiktextract/blob/b666add71ce653ad8b893d94fb1e020acec31c75/src/wiktextract/clean.py#L1545-L1551

can't match the last empty arg in `[[File:Spout (PSF).png|thumb|]]`, and it seems we can't reuse regex pattern in wikitextprocessor?

**Comment by kristian-clausal** [comment]
We ignore images and discard the data. I'll modify the regex.

**Comment by kristian-clausal** [comment]
Yeah, all this needed was a `\|*` at the end to handle dangling pipes. It makes the regex a bit less efficient (I bet there's more backtracking), but making efficient regex out of this seems difficult.
