### ISSUE TITLE
Term labels sometimes mistaken as forms

### ISSUE THREAD

**Issue by Ian-07** [tatuylonen/wiktextract#906]
For some pages that use the {{term-label}} template, wiktextract is incorrectly adding some of those labels to the list of forms.

From [vai](https://en.wiktionary.org/wiki/vai) on Wiktionary:

> vai (plural [vais](https://en.wiktionary.org/wiki/vais#English)) ([Bangladesh](https://en.wikipedia.org/wiki/Bangladeshi_English), [West Bengal](https://en.wikipedia.org/wiki/West_Bengal), chiefly [Benglish](https://en.wikipedia.org/wiki/Benglish))

From [vai](https://kaikki.org/dictionary/All%20languages%20combined/meaning/v/va/vai.html) on kaikki.org:

```
  "forms": [
    {
      "form": "vais",
      "tags": [
        "plural"
      ]
    },
    {
      "form": "Benglish",
      "tags": [
        "West-Bengal"
      ]
    }
  ],
```

**Comment by kristian-clausal** [comment]
Happily, this was a simple fix; wiktextract didn't recognise 'Benglish' as a valid taggable string, so it assumed it had to be a weird inflected form. Adding 'Benglish' to `uppercase_tags` fixes things in this specific instance.

**Comment by Ian-07** [comment]
Here is another example of this which this time doesn't seem to be related to uppercase_tags: [chuunibyou](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/ch/chuunibyou.html), [Flanderization](https://kaikki.org/dictionary/All%20languages%20combined/meaning/F/Fl/Flanderization.html), and [Nuzlocke](https://kaikki.org/dictionary/All%20languages%20combined/meaning/N/Nu/Nuzlocke.html) all use the {{term-label}} template with the "fandom slang" label, and all of them erroneously have "lifestyle" as one of the forms.

**Comment by kristian-clausal** [comment]
Kaikki has finally updated after bug fixes (I had the flu for a week, but there were also computer bugs *badumtsh*), please take a look if you have the time.

**Comment by Ian-07** [comment]
Everything looks good now, thanks.
