### ISSUE TITLE
Forms or grammatical features for a given data type 

### ISSUE THREAD

**Issue by OmarAI2003** [tatuylonen/wiktextract#918]
How can I find all the forms that a given data type for a given language has?

**Comment by xxyzz** [comment]
Not sure what you mean "data type" but you can download the raw JSONL file at https://kaikki.org/dictionary/rawdata.html and write some code to extract the data you want. English edition's JSON structure can be found at https://kaikki.org/dictionary/errors/mapping/index.html and non-en editions' JSON schema files: https://tatuylonen.github.io/wiktextract/

**Comment by OmarAI2003** [comment]
Hi @xxyzz, sorry for my ambiguous issue description, and thanks for replying. Basically, what I mean by data type is that for a given data type (i.e., lexical category like a noun or a verb) in a given language, I'd like to know all the possible grammatical features that the lexemes in this lexical category in this language can take. An example of a lexeme that's a Danish noun is [here](https://www.wikidata.org/wiki/Lexeme:L54603).

**Comment by xxyzz** [comment]
You can get the forms of a word in the "[forms](https://kaikki.org/dictionary/errors/mapping/index/forms.html)" field, part of speech type is in the "[pos](https://kaikki.org/dictionary/errors/mapping/index/pos.html)" field and "categories" list. Inflected form page has "form_of" field and "[form-of](https://kaikki.org/dictionary/errors/mapping/index/form_of.html)" tag in "tags" list.

Your second post is about Wikidata, but this package extracts Wiktionary, you should use Wikidata's [SPARQL query](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/A_gentle_introduction_to_the_Wikidata_Query_Service) to get data in there.

**Comment by kristian-clausal** [comment]
Yes, unfortunately Wiktionary data does not explicitly have what you're looking for, it's 'just' a dictionary. There is data there (at least for some languages) in the sense that many language will have entries for inflected forms, which contain keywords explaining that "syödessä" is the '[inessive](https://en.wikipedia.org/wiki/inessive_case) of second [active](https://en.wiktionary.org/wiki/Appendix:Glossary#active_voice) [infinitive](https://en.wiktionary.org/wiki/Appendix:Glossary#infinitive) of [syödä](https://en.wiktionary.org/wiki/sy%C3%B6d%C3%A4#Finnish)', **and** we attempt to parse these specific things as tag data, so you can scrape *some* of that to get an incomplete picture. But what you're really looking for is an exhaustive grammar of each language, or a linguistic description, or something like the data in the WALS project if you're more into the typological side of things.
