### ISSUE TITLE
Parsing non-English Wiktionaries

### ISSUE THREAD

**Issue by williamjr** [tatuylonen/wiktextract#92]
Hello,

Thank you for this immensely valuable resource.

I am involved in several projects that make use of Kaikki's pre-extracted data in tools and resources for language learning.

We are aiming to expand support for language learners who are not native speakers of English. We are wondering what would be required to add support for other languages to this project, and whether we might be able to help. The readme here states

> While there are currently no active plans to support parsing non-English wiktionaries, I'm considering it. Now that this builds on wikitextprocessor and expands templates and Lua macros, it would be fairly straightforward to build support for other languages too - and even make the extraction configurable so that only a configuration file would need to be created for a processing a Wiktionary in a new language.

Would a maintainer consider building non-English support in the coming weeks, such that adding support for a language would be as simple as creating a config file?

If not, would maintainers be willing to work with and accept PRs from contributors attempting to add this support? How much Lua skill would be required to make this contribution?

Best,
Bill

**Comment by marreromarco** [comment]
**Would it be possible to parse the German Wiktionary ?**

It has more than 700,000 audio files that would be very valuable for language learners !

**Comment by tatuylonen** [comment]
I'm hoping to look into this in the spring.  I want to finish work on the English edition first (particularly inflection table extraction, some issues in handling Chinese dialects/languages, and some more quality control).

I'll probably first make it easier to add support for other language editions, and then implement support for a couple of language editions to myself, and then welcome help from others to implement the configuration files for other languages.  Implementing support for a language edition pretty much requires understanding the language in question, so it is hard to do without help from someone who understands the language.

**Comment by marreromarco** [comment]
I could help with German and Spanish if you need help to add support to those languages.

 Thanks for your great work !

**Comment by MarkMcCaskey** [comment]
I'm in a very similar position. The Wiktionary data and this tool are extremely valuable, thank you very much for building it, maintaining it, and sharing it.

I'd also love support for other languages, specifically Japanese, Chinese (mandarin simplified + traditional), German, French, Spanish, and Korean.

We can help out with configuration files for Japanese and Chinese and maybe German. I'd also be happy to help out with anything else needed to make this happen.

Thanks again, this project has been fantastically useful for us.

**Comment by williamjr** [comment]
Hello @tatuylonen! Just wanted to check in on the status of this enhancement. It seems like the users of this project are eager to contribute to this!

**Comment by tslater** [comment]
@tatuylonen Very excited to hear that. Let us know if you need any help, either in the development, or in testing the configuration of language-specific work.

**Comment by xxyzz** [comment]
Hi everyone, I moved the subtitle text to JSON files so each Wiktionary language can have their own text stored in different JSON files. I have tested the code to extract at least the gloss data from the Chinese dump file. The code is at the "non-english" branch of my fork repo: https://github.com/xxyzz/wiktextract/tree/non-english

I'll create a draft pull request if the maintainer agrees.

**Comment by xxyzz** [comment]
I got this error while parsing this page: https://zh.wiktionary.org/wiki/%E6%88%91%E5%80%91

```
我們/漢語: ERROR: LUA error in #invoke ('wikipedia', 'wikipedia_box') parent ('Template:Wikipedia', {}) at ['我們', 'Wikipedia', '#invoke']
[string "_sandbox_phase2"]:205: Could not find module wikipedia: module not found
stack traceback:
        [C]: in function 'error'
        [string "_sandbox_phase2"]:205: in function <[string "_sandbox_phase2"]:140>
        Traceback (most recent call last):
        File "/home/x/git/wiktextract/.venv/lib/python3.10/site-packages/wikitextprocessor/luaexec.py", line 572, in call_lua_sandbox
    ret = ctx.lua_invoke(modname, modfn, frame, ctx.title, timeout)
        File "lupa/_lupa.pyx", line 587, in lupa._lupa._LuaObject.__call__
        File "lupa/_lupa.pyx", line 1333, in lupa._lupa.call_lua
        File "lupa/_lupa.pyx", line 1359, in lupa._lupa.execute_lua_call
        File "lupa/_lupa.pyx", line 1295, in lupa._lupa.raise_lua_error
        lupa._lupa.LuaError: [string "_sandbox_phase2"]:205: Could not find module wikipedia: module not found
stack traceback:
        [C]: in function 'error'
        [string "_sandbox_phase2"]:205: in function <[string "_sandbox_phase2"]:140>
```

The wikitextprocessor code raises this "module not found" error while expanding the Wikipedia template, I don't know how to solve this error. The English Wiktionary dump file has similar template, I'm not sure what went wrong...

**Comment by kristian-clausal** [comment]
That looks like it might be the exact same problem I've had with Lua/Lupa crashes. Tatu took a look at it yesterday, it might be a version issue mismatch: requirements.txt has an older version of Lupa, and some of the code might rely on behavior from a newer version. At a pinch, updating those python libraries might work, and we hope later to have a fix to it in general, but that might take a few weeks because of scheduling issues.

**Comment by xxyzz** [comment]
I have checked the packages but I have the latest version installed(lupa 1.13), that's because the "setup.py" in the wikitextprocessor project doesn't specify the package version. Maybe the error is caused by something else.

**Comment by xxyzz** [comment]
Hi everyone, I parsed the Chinese Wiktionary dump file and uploaded the JSON files for 23 languages at here: https://github.com/xxyzz/wiktextract/actions/runs/3105855453

**Comment by garfieldnate** [comment]
RE: version differences, I discovered while trying to parse the Simple English Wiktionary that Wiktionary uses Lua 5.1, which is considerably older than the latest and contains some functions that are now missing. I needed some polyfills to get the Simple English Wiktionary to parse: https://github.com/tatuylonen/wikitextprocessor/pull/9.

**Comment by aehlke** [comment]
> Hi everyone, I moved the subtitle text to JSON files so each Wiktionary language can have their own text stored in different JSON files. I have tested the code to extract at least the gloss data from the Chinese dump file. The code is at the "non-english" branch of my fork repo: https://github.com/xxyzz/wiktextract/tree/non-english
> 
> I'll create a draft pull request if the maintainer agrees.

can this tool be used to generate japanese wiktionary data too?

**Comment by xxyzz** [comment]
> can this tool be used to generate japanese wiktionary data too?

I think wiktextract could extract most Wiktionary dump files, but it currently can't extract the Japanese Wiktionary because we haven't implement the extractor code for the ja edition.

**Comment by aehlke** [comment]
Thanks for confirming!

**Comment by bqv** [comment]
Can Finnish edition be parsed?

**Comment by xxyzz** [comment]
All Wiktionary dump files can be parsed but need to be implemented. Currently we don't have plan to add code for Finnish Wiktionary. It seems to use a common layout, however the dump file size(62M) is smaller then all the editions we extracted so far.

We added [Japanese Wiktionary](https://kaikki.org/jawiktionary/rawdata.html) and [Polish Wiktionary](https://kaikki.org/plwiktionary/rawdata.html) this week. There are 5 more non-en edition data on kaikki.org.

**Comment by kristian-clausal** [comment]
Finnish wiktionary shouldn't be too difficult (and makes sense because Tatu and I are Finnish), but there are no plans.

**Comment by ngoclt** [comment]
> Finnish wiktionary shouldn't be too difficult (and makes sense because Tatu and I are Finnish), but there are no plans.

Hi, 
Firstly, thank you for all of the work you put here. I'm wondering is there any plan or estimation when you will support Finnish extraction? 

BR,

**Comment by kristian-clausal** [comment]
> > Finnish wiktionary shouldn't be too difficult (and makes sense because Tatu and I are Finnish), but there are no plans.
> 
> Hi, Firstly, thank you for all of the work you put here. I'm wondering is there any plan or estimation when you will support Finnish extraction?
> 
> BR,

Like I said two months ago, there are no plans.
