### ISSUE TITLE
Some French past participle forms have an incorrect form_of

### ISSUE THREAD

**Issue by rgossiaux** [tatuylonen/wiktextract#94]
Noticed a lot of French past participle forms have a sense with ```form_of: [{"word": "the past participle of X"}]``` instead of ```form_of: [{"word": "X"}]``` For example, see https://kaikki.org/dictionary/All%20languages%20combined/meaning/g/gr/grandis.html 

"grandis" is a form of "grandir", not of the string "the past participle of grandir".

**Comment by tatuylonen** [comment]
I just committed a fix for this.  It should be reflected on https://kaikki.org tomorrow.  I also fixed some other errors in parsing inflected form descriptions on the same page ("first/second-person" was not understood correctly).

Please let me know if you notice other similar issues.

**Comment by rgossiaux** [comment]
Brilliant, thank you!

I'm making extensive use of this project in a project of my own so I might send a few more issues (and/or PRs, if I can deal with the python multiprocessing/Mac issue to set up the project locally) your way. Thanks for your hard work!
