### ISSUE TITLE
Conjugation templates expansion

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#96]
If I understand correctly, the new version is able to run / expand Lua templates.

How can I run / expand the Wiktionary conjugation templates?

For example, the irregular German word `gehen` just has

```
  "inflection": [
    {
      "1": "gehen",
      "template_name": "de-conj"
    }
  ],
```

https://kaikki.org/dictionary/German/meaning/g/ge/gehen.html

So it seems most of the conjugation information is contained in the template `de-conj`.

How can I extract this information to get `gehen, ging, gegangen` etc.?

**Comment by tatuylonen** [comment]
I'm working on parsing the inflection tables.  In the meantime, if you wish to expand them, something like the following should work.  Note that you will need a cache file to do that; to generate the cache file, use something like "wiktwords --cache wikt-cache --out temp enwiktionary-<date>-pages-articles.xml.bz2".

import wikitextprocessor
wtp = wikitextprocessor.Wtp(cache_file="wikt-cache")
wtp.start_page("gehen")
text = wtp.expand("{{de-conj|gehen}}")
print(text)

For most languages, the inflection templates expand to wikitext tables, which you can parse with wtp.parse(text).  You could
also directly call
    tree = wtp.parse("{{de-conj|gehen}}", expand_all=True)
and then process the parsed tree.

The main problem is that the tables are quite different for different languages, and some of them are very complex.

**Comment by yolpsoftware** [comment]
Thank you!

Will you publish your work for the easier languages first? For example, the English conjugation is very simple, so it might be reasonable to publish English and Spanish before completing Euskara or Japanese.

**Comment by tatuylonen** [comment]
Just a FYI, I moved the inflection templates to "inflection_templates" field and change their format to be more uniform with other template lists (except I don't include the "expansion" field for inflection templates, as it is quite big and would increase the extracted data size significantly, perhaps double it).

Yes, I'll start with the easier tables.  You'll probably start seeing data from the conjugation/declension tables next week or the following week.

I don't think English uses conjugation/declension tables.  The data from the word head is already parsed into the "forms" field (e.g., verb forms, plurals, comparatives, superlatives).

**Comment by yolpsoftware** [comment]
That would be awesome, seeing data as early as next or the following week!

Although English conjugation is quite easy / not very interesting, Wiktionary indeed has English conjugation tables, e.g. https://en.wiktionary.org/wiki/go:

![image](https://user-images.githubusercontent.com/1302357/142700770-6e984c9a-b2ce-4de6-84c1-a4af09b58f64.png)

**Comment by tatuylonen** [comment]
I just committed the very first version of the inflection extraction code.  The merge into wiktextract is *VERY* new and has not yet been tested much.  Before the integration I tested the code separately on most major European languages (Spanish still has issues).  It is likely to work on simpler tables for most languages, but needs a lot more testing and a still a lot of bug fixing.

I started my overnight update, and if it succeeds (I estimate around 50% probability after today's changes), the extracted inflection data should be available at https://kaikki.org by around noon tomorrow (Thursday).  The data is not yet in the visible HTML, so you will need to look at the JSON.  The inflections are parsed into "forms" and have a "source" field to distinguish them from those parsed from the word head.

**Comment by yolpsoftware** [comment]
Thank you Tatu, gonna have a look!

**Comment by tatuylonen** [comment]
The run failed last night (11k Python exceptions - I'll have to fix some bugs and try again).  The run was taking 9 hours before inflection extraction, but surprisingly inflection extraction only seems to add maybe half an hour.

**Comment by tatuylonen** [comment]
Inflection data is now included on https://kaikki.org/dictionary/rawdata.html.  The data is also visible on the pages for individual words (though currently only when you go look at the JSON).  I haven't yet done any extensive evaluation, but I think simpler and many fairly complex tables should be correctly parsed.  There are still issues (I think Spanish is affected, but otherwise major European languages should probably be ok).  I've fixed various issues for other languages as well, but I don't yet have a clear understanding of how well they are currently parsed.

Feedback is appreciated.  For now, probably best to limit bug reports to the major European languages.  I'll continue working on this next week.

**Comment by yolpsoftware** [comment]
I just checked the following pages:

Irregular verbs:

https://kaikki.org/dictionary/German/meaning/g/ge/gehen.html
https://kaikki.org/dictionary/French/meaning/a/al/aller.html
https://kaikki.org/dictionary/Dutch/meaning/g/ga/gaan.html

Regular verbs:
https://kaikki.org/dictionary/German/meaning/a/ar/arbeiten.html
https://kaikki.org/dictionary/French/meaning/p/pa/passer.html

When clicking on "Show JSON for raw wiktextract data", I cannot see any new inflection data. There is the `inflection_templates` section with the reference conjugation template (e.g. `"name": "fr-conj-auto"`), but that was also there previously.

What am I missing?

**Comment by tatuylonen** [comment]
The forms extracted from the inflection tables are stored under "forms", with a "source" field indicating where they came from.  

All of the examples you listed except "gaan" seemed to have forms extracted from Conjugation/Declension tables under "forms".  "gaan" had an unrecognized header in the inflection table, which caused parsing that table to fail (probably affected a lot of Dutch verbs).  I fixed parsing of "gaan" (Dutch and also some issues in Navajo); that fix should be reflected on https://kaikki.org tomorrow.

A separate matter is that some words (e.g. aller/French) now have forms such as "present indicative of être + past participle".  I think this information is useful, but this is not exactly an inflected form directly. Any suggestions whether to leave these as-is or what to do with them? One option could be a "note" field similar to what is already done for translations.

**Comment by yolpsoftware** [comment]
Thanks, gonna have a look at the forms.

The "être + participle" seems to be an artifact of the special handling of French compound conjugations in the template:

https://en.wiktionary.org/wiki/aller#French

Spanish and Italian both have the same compounds as French ("je suis allé", "io sono andato", "yo hé ido"), but their templates just state the participle and the auxiliary verb:

https://en.wiktionary.org/wiki/andare#Italian
https://en.wiktionary.org/wiki/ir#Spanish

To me, the French template seems to offer more information, but it is not really more helpful than the Italian and Spanish ones. I don't think I will ever use these compound conjugation entries.

What *could* be helpful would be the complete expansion of the compound conjugations:

> je suis allé(e), tu es allé(e), il/elle est allé(e), nous sommes allé(e)s, vous êtes allé(e)s, ils/elles sont allé(e)s
> io sono andato/andata, tu sei andato/andata, lui/lei è andato/andata, noi siamo andati/andate, voi siete andati/andate, loro sono andati/andate

But for this you would also need an inflection on the participle, and it seems the templates don't have these.

**Comment by tatuylonen** [comment]
I'm closing this issue since there is no clear action pending.  Inflection table extraction works for most major European languages; I'm still testing and fixing bugs for other languages (and also fixing less common cases for European languages).

**Comment by yolpsoftware** [comment]
@tatuylonen there is no way you can expand the complete expansion of the compound conjugations, like

> je suis allé(e), tu es allé(e), il/elle est allé(e), nous sommes allé(e)s, vous êtes allé(e)s, ils/elles sont allé(e)s
> io sono andato/andata, tu sei andato/andata, lui/lei è andato/andata, noi siamo andati/andate, voi siete andati/andate, loro sono andati/andate

The interesting thing about this is that the participle changes under gender and number.
